### ISSUE TITLE
Selecting the button while it’s active will make it stop

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1001]
When users select the TTS button it changes to the active icon which is a pause button.  If users select the button again it will stop the speaking. 
Starting TTS again will restart it from the beginning of that section.  TTS will only read the section which can be the prompt, and individual step, or the math editor.

**Comment by benetechMatt** [comment]
![active and inactive TTS buttons.  inactive is a speaker icon, active is a pause button. Both have a hover state with a black border around them with a 5 pixels of padding](https://user-images.githubusercontent.com/49413678/75821259-8c95e280-5d63-11ea-871e-8fb11cba8f83.png)

**Comment by alexrcabral** [comment]
@benetechMatt Since it restarts from the beginning, it should be a stop button rather than a pause button. Pause implies that it will start speaking from where it left off.

**Comment by benetechMatt** [comment]
Changing stop button to a stop icon of a square.,
![stop button with icon as a square stop icon.  White square in a black circle](https://user-images.githubusercontent.com/49413678/77599179-e9ec0200-6ed1-11ea-8dce-0b2a9cee94e0.png)

**Comment by bpmcneilly** [comment]
From a visual standpoint, my only comments about these buttons are that the currently displayed "hover state", where an outline is provided to the buttons, should also be applied as a visual indication of keyboard focus.

**Comment by jscholes** [comment]
@benetechMatt and @alexrcabral - We've provided all accessibility comments from our side.  Any thoughts?

**Comment by alexrcabral** [comment]
@jscholes and @bpmcneilly thanks for the input 

Confirming that the outline used for the "hover" state should be applied as an indication of keyboard focus

**Comment by johnhbenetech** [comment]
@alexrcabral So just as a consideration, we have the capability to do both pause and stop/restart actions. Let us know if that changes your design decision. If not we will continue with the stop/restart approach

**Comment by alexrcabral** [comment]
@johnhbenetech Thanks for the consideration. The ability to stop/restart a phrase will likely be most beneficial for students since the primary use is working through short math phrases. I'll keep it in mind for the planned TTS user testing though. 

For this issue we should continue forward with the stop/restart approach

**Comment by abaranowska1** [comment]
**Tested with success**
- When users select the TTS button it changes to the active icon which is a stop button. If users select the button again it will stop the speaking.
- Starting TTS again will restart it from the beginning of that section. TTS will only read the section which can be the prompt, and individual step, or the math editor.
- Also the frame is visible around the active icon 
![image](https://user-images.githubusercontent.com/61964176/86338801-10e56d00-bc53-11ea-9d0f-c0ee893543f1.png)
