### ISSUE TITLE
Add personalization settings button to problem page

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1011]

**Comment by benetechMatt** [comment]
![mockup of problem solving page with the user icon in the upper right corner. The "?" help menu button is left of that.](https://user-images.githubusercontent.com/49413678/75728531-b391dd00-5cad-11ea-93a4-d34176917844.png)

Add the user profile button just the same as it's displayed on the dashboard

**Comment by johnhbenetech** [comment]
this isn't in line with #1031 please update

**Comment by benetechMatt** [comment]
Closing this issue as #1031 will resolve the problem
