### ISSUE TITLE
Students can tell which sets they have completed and which ones they have not

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1026]

**Comment by benetechMatt** [comment]
![mockup of the student dashboard. Problem sets are broken up into two sections, "incomplete" and "completed". Incomplete: is the first heading and all sets that have been opened and not completed are listed below in a list. Completed: is a heading below the incomplete sets list. ](https://user-images.githubusercontent.com/49413678/75598694-5a366d80-5a63-11ea-8e16-4d31b7d5282a.png)

Problems are considered complete if the student has made at least one change and clicked "finished" or "next problem".  this is addressed in another issue.

**Comment by alexrcabral** [comment]
I would argue to not have these as discrete categories. This takes away from students' ability to organize their work in a way that makes the most sense for them. (Eg types of assignments, who assigned them, the difficulty of the assignment, when they're due, the chronological order, etc)

Instead, there could be a label applied, eg a green check mark, to show that the problem set has been completed (the "finish" button clicked on all problems). 

Alternatively, a small number to say how many of the total problems have been completed. e.g. "6/8 problems completed". This would also scale with the number of problems a student has completed rather than a done/not done dichotomy.

**Comment by johnhbenetech** [comment]
Do we really want 'next button' to count as finished? I imagine students would use that to skip problems or resume later?

**Comment by alexrcabral** [comment]
@johnhbenetech Agreed -- the UX review of this above mentions this exclusively as the finish button clicked on all problems. Not just adding a step, and not tied to navigating away from the problem (next or previous button or otherwise).

**Comment by benetechMatt** [comment]
@alexrcabral I like the idea of listing the number of problems completed for all sets.  Would a checkbox for students to select that says "completed" be useful?  It could be automatically checked when students meet the criteria as described before.  Students could uncheck sets and check sets that are "done" but didn't meet our criteria

**Comment by alexrcabral** [comment]
@benetechMatt A check**mark** could be useful, but a check**box** adds unnecessarily to cognitive load. It's one more thing that a student has to remember to click, and adds extra actions with little to no added value for the student.

**Comment by benetechMatt** [comment]
When students have clicked "finished" for all problems, the set will be marked as "finished".  This is indicated with a green check mark on the dashboard and displaying the number of problems completed out of the total (ie. 8/8)

@alexrcabral does that sound good until the ability to organize sets is added later?

**Comment by alexrcabral** [comment]
Sounds good -- I actually just finished a mockup for this. 

Updates: 
1. Number of problems completed (denoted by clicking the "finish" button) listed to the left as a ratio of the total number of problems completed. E.g. 5/9 Problems Completed 
2. If all problems in a set have been completed, a green checkmark (#288500) will show between the number of problems completed and the three button menu. 

<img alt="mockup" src="https://user-images.githubusercontent.com/47576069/77212204-7c9c3380-6ac3-11ea-8a82-eee25ce403ea.png">


<img width="300" alt="green-checkmark" src="https://user-images.githubusercontent.com/47576069/77212211-7f972400-6ac3-11ea-9d95-e14588756b30.png">

**Comment by jscholes** [comment]
The "Incomplete: and "Completed:" heading text doesn't come across as visually distinct enough, to identify its purpose as heading text.  During implementation, the appropriate HTML heading elements should be used, so this may not end up being an issue.

**Comment by bpmcneilly** [comment]
Looking through this, having just been thinking about #966, as @jscholes and I have mentioned the information density of including the problem solutions, would it be possible to use these same icons for completed sets & completed problems? 

The check icon currently suggested as a solution to indicate completion could be reused, creating some consistency in identifying what is completed, while also reducing the amount of text needed to be added on the page?

**Comment by jscholes** [comment]
CC @benetechMatt and @alexrcabral - We've provided all accessibility comments from our side.  Any thoughts?

**Comment by johnhbenetech** [comment]
@alexrcabral any input on this? We can kick out of this sprint if it needs more discussion

**Comment by alexrcabral** [comment]
@jscholes Solid point. Since the design was changed to the checkmark with the number problems solved out of total, these would all be listed under the existing heading "Recent Sets" rather than "Incomplete" and "Completed". "Recent Sets" should also have the appropriate HTML heading elements. 

@bpmcneilly I like the idea of having the consistency between the problem level view as well for #966 and #967. I think this would be best to discuss on call since it affects other aspects of the dashboard, such as surfacing answers.

**Comment by johnhbenetech** [comment]
@rupeshparab sounds like we can go forward with the design from this comment
https://github.com/benetech/MathShare/issues/1026#issuecomment-601944977

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on qa env

**Verified cases**
- Clicking buttons on problem view
-- Finish
-- Previous
-- Next
- Controlling the homepage if the count of solved problems per set is correct

**Summary**
The number of solved problems within the problem set is displayed correctly on the homepage. Only the "Finish" button checks the problem as solved. After finishing all of the problems within a set, the green checkmark is displayed in the right place.

**Attachment**
![ms 1026](https://user-images.githubusercontent.com/51324797/82669932-929db000-9c3c-11ea-855c-a01b9b7db56d.png)
