### ISSUE TITLE
Text button putting in code

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1029]

**Comment by benetechMatt** [comment]
When a user selects the "text" button it outputs \text{}. Any text entered in the {} does not save to the next step. \text{} disappears when I click outside the editor
![screenshot of the issue](https://user-images.githubusercontent.com/49413678/76102902-512f2a00-5f96-11ea-8002-2d07fa2c2949.png)

**Comment by johnhbenetech** [comment]
@benetechMatt with the mathlive update that tries to automatically understand when you're typing text vs. math do you still think we need this button at all?

If we still want this functionality, we'd likely need to pull in @NSoiffer for an opinion on a better way to pull this off.

**Comment by benetechMatt** [comment]
I'm in favor of not having the text button.  @alexrcabral thoughts on this? 
Currently users have to know that they need to enter a space before the text and you can't start typing text at the beginning of the equation input box

**Comment by johnhbenetech** [comment]
Would be good to get @NSoiffer opinion on this

**Comment by johnhbenetech** [comment]
For now i'll change this task to just removing the text button. We will look at #1030 once we have input from @NSoiffer

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on QA env

**Verified cases**
- Browsing operations palette during resolving equation as
-- Teacher
-- Student
-- not logged in user

**Summary**
Text button is removed from palette for all kind of users.

**Attachment**
Exemplary screenshot of palette for Student user:

![1029](https://user-images.githubusercontent.com/51324797/80369287-515cef00-888e-11ea-88d5-2188cfb1b61e.png)
