### ISSUE TITLE
focus "add step" alert on the annotation text field

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#104]
The "Add Step" button should not be grayed out in this case and should instead, throw up a dialog box that reads "Please provide a description of your work using the annotation field,"

**Comment by NSoiffer** [comment]
Done. I tried to get it to push the focus into the text box, but for some reason it isn't doing that. Because of that, I'm leaving the issue open.

**Comment by kkrawczyk123** [comment]
Add Step button remains active and it is not grayed out when a comment is not added. After choosing it without adding a comment dialog message is displayed “Warning: Please provide a description of your work.” and focus has been added to the annotation text field.
