### ISSUE TITLE
Add a palette button to support insertion of text in the math editing box

### ISSUE THREAD

**Issue by NSoiffer** [benetech/MathShare#105]
Users need a way to enter units such as "km" and "gal" as text (non italic display). mathlive supports `\text{...}` to do this. We should add a palette button to do this and a shortcut (not sure what).

I'm not sure what the button should look like. Maybe "Add text" or "Add unit"? Potentially, we could color the text to make it clear that it isn't math.

This button can also be used to add text such as "if", "then" or "when".

**Comment by sueannma** [comment]
from Neil: we need some UX change to indicate switching to text mode

**Comment by sueannma** [comment]
I was thinking something like "abc" or the "T" that's sometimes used in other apps, such a the following: 
![image](https://user-images.githubusercontent.com/7883873/41528027-c9673a72-729d-11e8-964b-c4d301c72c78.png)
![image](https://user-images.githubusercontent.com/7883873/41528062-dbca6a7c-729d-11e8-9917-5d6de8b45f40.png)

**Comment by afijal** [comment]
@johnhbenetech 
Here is a button with tooltip
![image](https://user-images.githubusercontent.com/2682379/45217530-b7a19200-b2a4-11e8-9796-93948fa53cef.png)
After pressing it we launch mathlive commandMode with command \text{} already pasted and let user write the text
![image](https://user-images.githubusercontent.com/2682379/45217571-df90f580-b2a4-11e8-903e-e4e63d285084.png)
and here is example final result
![screenshot from 2018-09-07 13-46-45](https://user-images.githubusercontent.com/2682379/45217583-e7509a00-b2a4-11e8-8755-6744fb86b847.png)
Is it fine? We can discuss it here or at our Monday's meeting.

**Comment by kkrawczyk123** [comment]
Text button and shortcuts work in the same way. I have noticed issue connected to space button and reported in https://github.com/benetech/MathShare/issues/495.
