### ISSUE TITLE
Unsaved step shows up in other problems

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1057]
Video of issue http://youtu.be/pkSMk3c3y9I
If the user adds an explanation to a step, does not save the work, and goes to another problem, the explanation shows up in the new problem.

This does not happen if:
- the user saves their work
- The user reloads the page

When going from one problem to the next, the equation from the previous problem briefly displays in the equation editor.  it is quickly replaced by the correct equation for the problem.

Steps and equations from a previous problems should not show up in other problems.  

Unsaved changes do not need to be saved for the user when they leave a problem.

**Comment by benetechMatt** [comment]
reviewed and works as expected

**Comment by abaranowska1** [comment]
**Tested with success**
Now I see that every user should choose whether they want to discard or save changes after clicking "All problems" button.
I cannot reproduce the mentioned bug anymore so I believe that is was fixed. 
If the user adds an explanation to a step, does not save the work, and goes to another problem, the explanation didn't show up in the new problem.
![Uploading giff.gif…]()
