### ISSUE TITLE
Remove intercom button for students

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1061]
Currently the intercom button shows up when the user has signed in and indicated they are a student.  The user is not added to the intercom mailing and tracking system.

It's fine if the intercom button still shows up when users are in the help center

**Comment by benetechMatt** [comment]
Tested with a student account.  The user is not added to intercom automatically like they are when signing up as a teacher.  Once the user sends us a message they are added to Intercom as a user.  At this point the users name and email is sent to Intercom which is a data privacy issue.

**Comment by benetechMatt** [comment]
reviewed and works as expected

**Comment by abaranowska1** [comment]
**Testes with success**

Intercom button is removed for student's accounts, but the intercom button still shows up when users are in the help center - it's fine. 

Teacher view: Intercom button shows up
![All Problem Sets - Benetech Mathshare - Mozilla Firefox_189](https://user-images.githubusercontent.com/61964176/80692270-a3da1d80-8ad1-11ea-89ea-635bd65e962b.png)
Student view: Intercom button is removed
![All Problem Sets - Benetech Mathshare - Mozilla Firefox_190](https://user-images.githubusercontent.com/61964176/80692314-b05e7600-8ad1-11ea-97ec-037df4e197a9.png)
Intercom button shows up in the help center
![Benetech Help Center - Mozilla Firefox_191](https://user-images.githubusercontent.com/61964176/80692380-c3714600-8ad1-11ea-834b-9d05925c77f3.png)
