### ISSUE TITLE
Help users that are not signed in save and return to their work

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1064]
One idea is adding a "bookmark work" link

**Comment by jscholes** [comment]
> One idea is adding a "bookmark work" link

How do you envisage this working?  In a recent announcement, Apple indicated that web apps will not be allowed to store local data for longer than seven days:

https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

So the best approach would probably be to tell users that MathShare will work with their browser's standard bookmarking/favourites system (obviously ensuring that such an assertion is technically true).

**Comment by benetechMatt** [comment]
moving to #1073

**Comment by alexrcabral** [comment]
Closing this issue since it's covered by #1073
