### ISSUE TITLE
Move "example problem set" to "pre-made sets" list

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1065]

**Comment by benetechMatt** [comment]
Example problem set should be at the first item in "pre-made sets"

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on QA env

**Verified cases**
- Opening the homepage
-- user signed in through Google
-- user signed in through Microsoft
-- user not signed in

**Summary**
In all of the cases "Example Problem Set" is available as the first position in "Pre-Made Sets" section.

**Attachment**
Exemplary view:
![ms 1065](https://user-images.githubusercontent.com/51324797/80353812-354d5380-8876-11ea-8987-c5b6e004bd96.png)
