### ISSUE TITLE
Changes to sign in modal

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1067]
Remove "log in" text. Only have "Sign in"
Right align "continue without signing in" text and make it slightly smaller than the main text. 
Remove extra space at bottom

![mockup of new sign in modal. changes text to only say "sign in". visually de-emphasizes "continue without signing in" link at the bottom by decreasing font size slightly and moving from center to right align](https://user-images.githubusercontent.com/49413678/77600441-fa05e080-6ed5-11ea-890b-7216f1b18410.png)

**Comment by benetechMatt** [comment]
related to #973

**Comment by benetechMatt** [comment]
Adopt the text found in https://github.com/benetech/MathShare/issues/973#issuecomment-604173153

**Comment by alexrcabral** [comment]
This was completed and released in v1.1.0
