### ISSUE TITLE
Add "Other" user option

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1074]
In addition to "Student" and "Teacher" roles when signing up, add "Other" as an option.  

This role has the same dashboard and abilities as Teachers.  

"Other" users should be added to Intercom and have their role as a "Other" so we can send relevant messaging

**Comment by benetechMatt** [comment]
Change the category to "Other" instead of "Parent"
Add user to Intercom, indicate they are an "other" user type
Take user directly to the dashboard instead of asking what grade/role as is done for "Teacher" users

**Comment by alexrcabral** [comment]
Added to this issue: We need to be able to differentiate between logged-in and not-logged-in users. 

The primary purpose of the log-ins right now is to give us insight into who is currently using Mathshare and how they're using it -- e.g. workflow differences in authenticated vs. unauthenticated users.

On first sign up, users should be given a token identifier "T", "S", "O"(Teacher/Student/Other). This should be sent to Google Analytics. If a user has previously signed up but has not been given the token identifier, and if it cannot be assessed which role they chose when they first signed up, they should be given the identifier "U" (Undefined) the next time they log in.

This identifier should be associated with future sessions so we can differentiate between logged-in and not-logged-in users. 

To clarify: 

- When a user signs up for the first time, they should be associated with the token 
- When they log in for later sessions, those sessions should still be associated with the token
- If the same user is **not** logged in during subsequent sessions, those sessions should **not** be associated with the token

**Comment by johnhbenetech** [comment]
Hi @rupeshparab I added a custom dimension for google analytics called "UserType" we can also send a "UserType" value to Intercom

Let's go with:
Teacher
Student
Other
OptOut
Undefined


Note: if you look at #964 we will add an option for user to opt out of usertype tracking. "OptOut" will be used for those users and "Undefined" will be used for unauthenticated users

**Comment by alexrcabral** [comment]
@johnhbenetech's update looks good 

@rupeshparab 
Please let me know if you additional more input from me before proceeding

**Comment by rupeshparab** [comment]
@alexrcabral 
I have posted a doubt on the PR: https://github.com/benetech/MathShare/pull/1111#issuecomment-622234814

**Comment by alexrcabral** [comment]
@rupeshparab Thanks for the clarification around Students having a single step in the sign-in process. 

I think in this case "Next" still makes sense, since it proceeds to a redirect, and the success message will give the student visibility into the sign-up state change. It also works if we need to add more to the sign-up process for students in the future, such as choosing personalization settings prior to the redirect.

**Comment by abaranowska1** [comment]
**Tested with success**
Other option was added, this role has the same dashboard and abilities as Teachers.
![Screenshot from 2020-05-12 14-05-35](https://user-images.githubusercontent.com/61964176/81816371-87a39b00-952b-11ea-8ebb-7256df1fc8e0.png)
