### ISSUE TITLE
Link to privacy policy app footer

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1075]
Add a link titled "Privacy Policy" to the dark gray footer. 
URL https://mathshare.benetech.org/#/privacy

Placed between the Youtube link and the copyright text. Add padding of 10px to both sides 
![screenshot with an arrow pointing to where the text will go in the footer](https://user-images.githubusercontent.com/49413678/77689170-3a656d00-6f6f-11ea-865f-d8ff0edee6c0.png)

**Comment by abaranowska1** [comment]
**Tested with success**
A link titled "Privacy Policy" was added to the dark gray footer and it is placed between the Youtube link and the copyright text. 
After click, user goes to https://mathshare.benetech.org/#/privacy
![image](https://user-images.githubusercontent.com/61964176/80368654-553c4180-888d-11ea-99b4-dd0d34da7df9.png)
