### ISSUE TITLE
Display Layout issues on sign-up page

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#1079]
Strange button placement. On firefox during sign up process (havent tested other combinations yet)

![screenshot of overlapping buttons](https://user-images.githubusercontent.com/12927553/77772261-d6e24a80-7015-11ea-8a05-bfa63399d577.png)

**Comment by rupeshparab** [comment]
Was able to replicate the issue on Firefox, have fixed the CSS for firefox

**Comment by benetechMatt** [comment]
Is there a way for me to view the page without signing up with a new account?

**Comment by johnhbenetech** [comment]
QA, this seems related to #1142 
If this is still present, we can close this issue out and deal with it there

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified on:**

- Google Chrome Version 81.0.4044.92
 ![image](https://user-images.githubusercontent.com/61964176/80347176-41ccae80-886c-11ea-836a-73fd98e35398.png)

- Firefox Browser 75.0
 ![image](https://user-images.githubusercontent.com/61964176/80347184-46916280-886c-11ea-921c-1f13287f6d3d.png)

- Microsoft Edge Version 81.0.416.64 
 ![image](https://user-images.githubusercontent.com/61964176/80347348-7c364b80-886c-11ea-9a32-36e17c7e493d.png)

**Verified cases:**
I was checking buttons placement during signup process on Chrome, Firefox and Edge browsers, the issue didn't occur
