### ISSUE TITLE
clearer language on add problem modal

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1080]
Some users think they are supposed to enter a problem number, equation, and title under the headings instead of the math editor because the fields don't line up. Change "Title" to "Prompt
Remove "#" as it confuses some users

**Comment by benetechMatt** [comment]
![screenshot of the modal for adding problems.  no problems have been added.](https://user-images.githubusercontent.com/49413678/77811433-3406ec00-7068-11ea-979b-22a2a16dc689.png)

One solution is to align the headings with their math editor. Add the problem number to the left of the equation editor field. Decrease the spacing between the headings and the math editor when no problems have been added.

**Comment by alexrcabral** [comment]
That described solution is fine. Listing for clarity's sake: 

1. "Title" should be changed to "Prompt" 
2. The heading "Equation" should be moved to the left to align with the main math box below it 
3. The updated heading "Prompt" should be moved to the right to align with the prompt box. 
4. All three headings -- "#", "Equation", and "Prompt" -- should be moved closer to the entry boxes (decreased padding).

I will also add
5. The default text in the description box should be changed from "Use the microphone button or type to add problem title (required)" to "Use the microphone button or type to add problem prompt"

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:** 
- "Title" was changed to "Prompt"
- The heading "Equation" should was moved to the left to align with the main math box below it
- The updated heading "Prompt" was moved to the right to align with the prompt box.
- All headings, "Equation" and "Prompt" - was moved closer to the entry boxes 
- "#" was removed d
- The default text in the description box changed from "Use the microphone button or type to add problem title (required)" to "Use the microphone button or type to add problem prompt (required)"

![image](https://user-images.githubusercontent.com/61964176/80370848-33dd5480-8891-11ea-86ce-7f36a82bf5ee.png)
