### ISSUE TITLE
Add "Getting Started" to top navigation bar

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1083]
Create the page similar to how the privacy policy is done
Add the link to the top navigation bar
dependent on #1082 for content
Link must be trackable via google analytics

**Comment by benetechMatt** [comment]
dependent on #1082 for content

**Comment by benetechMatt** [comment]
![Mockup with "getting started" link of white text and an underline next to the help menu button in the top navigation bar](https://user-images.githubusercontent.com/49413678/77802405-c7302980-7048-11ea-978f-9fc3b0779b4f.png)

**Comment by benetechMatt** [comment]
Link must be trackable via google analytics

**Comment by johnhbenetech** [comment]
awaiting content

**Comment by johnhbenetech** [comment]
content for page:
https://benetech.box.com/s/m040cviwz5vvqnpmb5qo1nqbf0ku2fut

**Comment by johnhbenetech** [comment]
This was intended to be a page on the site itself (HTML). So please create a new page /gettingstarted using the markup from the file
