### ISSUE TITLE
Add vertical padding between items in the help menu

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1084]
Menu items in the help menu are visually cramped and can make selection difficult for some users. Add 4px of vertical padding to the top and bottom of menu items in the help menu
![screenshot of open help menu](https://user-images.githubusercontent.com/49413678/77801908-c8148b80-7047-11ea-8044-eb8813fbcc1f.png)

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on QA env

**Verified cases**
- Opening help menu
- Comparing this to the screenshot from original post

**Summary**
A new help menu seems more spacious.

**Attachment**
Screenshot of help menu

![ms qa](https://user-images.githubusercontent.com/51324797/81146533-c60fe780-8f78-11ea-8112-9b4840b192cb.png)
