### ISSUE TITLE
Change "new problem set" to "Create a problem set"

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1085]

**Comment by benetechMatt** [comment]
This makes the copy actionable
![mockup of with text change on the button](https://user-images.githubusercontent.com/49413678/77802038-0d38bd80-7048-11ea-863d-c6c8aea09a09.png)

**Comment by abaranowska1** [comment]
**Tested with success**
Confirmed that button changed the name from "New problem set" to "Create a problem set"
![image](https://user-images.githubusercontent.com/61964176/80351162-249ade80-8872-11ea-94fe-ca1aa785f952.png)
