### ISSUE TITLE
Remove "more options" menu and add "duplicate" button in it's place

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1090]

**Comment by benetechMatt** [comment]
Issue #1091 removes the "share to twitter" button.  This makes the "more options" button unnecessary in the problem set view because it only has one item, "duplicate".

For the 5 different views (including the preview view #1025 )

Edit view:
Edit icon for editing the title

Solve view:
No edit icon for editing the title
Duplicate button

Review view:
no duplicate or edit buttons

Preview view:
Duplicate button


![mockup showing the duplicate button with no label to the right of the problem set title](https://user-images.githubusercontent.com/49413678/77809711-e76ae300-705e-11ea-9e9f-76ce8d5af6dc.png)

**Comment by alexrcabral** [comment]
@benetechMatt Isn't this changed from the call this morning?

Separate section for problem set creators with problem set level controls. A three dot menu on the problem set (for all users) which contains the share problem set option.

**Comment by benetechMatt** [comment]
closing this issue due to changes in #1086
