### ISSUE TITLE
remove "share to twitter" link

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1091]
Remove the "share to twitter" link from the "More Options" button.
1. Dashboard more options on each problem set
2. Problem set page next to the set title

This feature has not been used and is not something we want to have displayed for students.  For simplicity we are going to remove it completely. Will evaluate the benefit of social media sharing for teachers in the future

**Comment by abaranowska1** [comment]
**Tested with success**
Confirmed that "Share to twitter" link is removed from "More Options" button.
![image](https://user-images.githubusercontent.com/61964176/80357645-93c90080-887b-11ea-9cc7-b82155c9e2a5.png)
