### ISSUE TITLE
Make explaining steps optional for users when they are completing steps to problem sets they created.

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1093]
This is aimed at students and unauthenticated users that may be students that want to use Mathshare on their own.
If a student or unauthenticated user adds steps to a set that they did not create they should be required to explain the step.

**Comment by alexrcabral** [comment]
This is a step in the right direction, though it doesn't solve the larger underlying problem. Ultimately this should be a toggleable control on the problem set level. Whoever "owns" the set that is being solved should dictate whether an explanation is required, with the default of it being non-required.

@benetechMatt If this a difficult change to do now on the product/technical side we can push the issue through as-is, and I'll put in a new issue in the MVP backlog to address this.

**Comment by alexrcabral** [comment]
Update: having the larger problem set controls runs into issues with differences between controls of different views (teacher vs student vs unauthenticated user). Adding a new issue #1094

**Comment by benetechMatt** [comment]
In discussion with John and Alex.
Historical default is all steps require an explanation.
A modal will show up when assigning/sharing the set. Has a checkbox asking if you want to require explanation.

add mockup

**Comment by benetechMatt** [comment]
Closing this issue and accomplishing goal via #1094
