### ISSUE TITLE
Allow step descriptions to be optional with a toggle

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1094]
Problem: As a student who is familiar with the steps of a particular type of problem, I am frustrated and waste time when trying to explain my steps where it's not needed. 

Solution: It should not be required to enter an explanation unless explicitly required by the problem set creator. 

Ultimately this should be a toggleable control on the problem set level. Whoever "owns" the set that is being solved should dictate whether an explanation is required, with the default of it being non-required.

This should be located with similar problem set level controls, such as designating which groups of math tools are used for the problem sets. Possible roadblocks: palette controls are moving in the MVP and are planned to have different levels of access for teachers/students/unauthenticated users. 

Related to story #1013 and issue #1093

**Comment by benetechMatt** [comment]
![mockup of modal for share a link to the problem set.  ](https://user-images.githubusercontent.com/49413678/78322181-9a41b200-7533-11ea-92f6-565855f4a369.png)

**Comment by benetechMatt** [comment]
This sharing modal appears when users (teachers) select the "share problem set" button. Below the title and explanation there is the label and checkbox that would require anyone this problem set to explain each step.

Heading: Share Problem Set
below the heading is an explanation of why these links should be used vs. the "share answers" button.

- Allows students to answer questions
- Allows educators to copy and re-use  this  problem set

Below the reasons is the checkbox for requiring steps


![mockup of modal for share a link to the problem set.  ](https://user-images.githubusercontent.com/49413678/78322181-9a41b200-7533-11ea-92f6-565855f4a369.png)

**Comment by alexrcabral** [comment]
@benetechMatt Isn't this changed from the call this morning?

Separate section for problem set creators with problem set level controls. A three dot menu on the problem set (for all users) which contains the share problem set option.

**Comment by benetechMatt** [comment]
Addressed in issue #1086

**Comment by benetechMatt** [comment]
In the problem set controls added with issue #1129, there is the ability to change whether descriptions are required for each step. The ability to not require descriptions for every step has been requested by educators and will be necessary for students creating their own problem sets to complete.

The box is checked by default. un-checking the box will allow users to add steps without adding a description. This change is not retroactive to /solve/ sets that had already been started.

**Comment by benetechMatt** [comment]
Changing this action to a toggle as it will immediately affect the users ability to add steps with or without adding a description. 
Label: Require explanations
Toggle switch is placed to the right of the label.
![mockup of problem set controls showing this option with a toggle on the right side of the label](https://user-images.githubusercontent.com/49413678/79629274-db2def00-810d-11ea-8f98-440e0fbacd1c.png)

**Comment by johnhbenetech** [comment]
waiting on #1129

**Comment by jscholes** [comment]
Surfacing this as an issue which has not undergone accessibility review, but is marked as ready for development.

CC @alexrcabral

**Comment by alexrcabral** [comment]
Colour contrast confirmed 8.23:1 for active state and 6.02:1 for inactive state, which is acceptable for UI components. 

As confirmation per @jscholes' suggestion, as long as this has the typical focus indicator and will be marked up as a button with aria-pressed, it's good to continue with development.

**Comment by abaranowska1** [comment]
From QA side 

Verified cases: 
![image](https://user-images.githubusercontent.com/61964176/84249959-b3ef0f00-ab0b-11ea-9104-550f1a18ce4c.png)
- **"Require explanation" toggle button is inactive by default** @johnhbenetech @benetechMatt Shouldn't be checked by default ?
- "Require explanation" active - the user shouldn't add a description to the steps
- "Require explanation" inactive - the user should add a description to the steps 
- Toggle switch is placed to the right of the label
- It is not retroactive to /solve/ sets that had already been started.

**Verified on:**

- QA instance
- Ubuntu 16.04 OS
- Mozilla Firefox v. 77.0.1

**Comment by johnhbenetech** [comment]
@alexrcabral confirm the default is explanations are not required?
