### ISSUE TITLE
Prepare selenium tests for load testing

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#1103]
Create a Selenium test that does the core user workflow:
* Create a problem set with a few problems
* Generate assign link
* Visits solve URL
* Adds/Saves steps to a few problems
* Generate submit URL
* View read-only version

**Comment by rupeshparab** [comment]
I have added the automation scripts here:
https://github.com/benetech/MathShare/tree/development/automation

**Comment by johnhbenetech** [comment]
No QA needed
