### ISSUE TITLE
Bug: Font personalization

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1113]
Problem: As a signed-in user, fonts don't update despite choosing an alternate font (e.g. "Comic Sans").

<img width="395" alt="Screen shot of the personalization settings modal with Comic Sans selected" src="https://user-images.githubusercontent.com/47576069/78723521-6d4d2080-78e0-11ea-89e3-47375b1f280d.png">
<img width="1175" alt="Screen shot of the dashboard with the default font. The message in the corner states that the personalization settings have been updated" src="https://user-images.githubusercontent.com/47576069/78723522-6e7e4d80-78e0-11ea-88f3-f80cd0f8b9f4.png">

Solution: Should be updated so fonts update correctly.

**Comment by johnhbenetech** [comment]
moving this forward - scoped enough for dev

**Comment by rupeshparab** [comment]
I think this might have been tried on prod and not QA, the prod version had some placeholders as font files were not available at that time.
This is a demo of the feature on QA: https://www.loom.com/share/a484441ec77f4b43abac18cf1d1cfc05

Comic Sans is not a dropdown open in the working version

**Comment by johnhbenetech** [comment]
QA, confirm working on qa instance

**Comment by abaranowska1** [comment]
**Tested with success** 
Confirmed that font personalization works on QA instance 
![font](https://user-images.githubusercontent.com/61964176/80366907-6172cf80-888a-11ea-982a-3ae461e677e8.gif)
