### ISSUE TITLE
Add problem set controls

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1129]

**Comment by benetechMatt** [comment]
problem set owners, whether they created the set or not, need the ability to change some problem set level settings and share a solvable version of the set.  The allow for this we are adding a problem set controls box which is only available for problem set owners.
Actions users can take:
- Customize the math tools palettes
- Change whether descriptions are required for each step
- Share a /solve/ link to users

![Mockup showing the problem set controls box. It's located between the set title and the problems. The box has a dark orange border and a light gray background. At the top is an h2 "problem set controls".  on the left side are the math palettes and required description controls.  on the right is the "share problem set" button.](https://user-images.githubusercontent.com/49413678/79224343-8a25ae80-7e20-11ea-81b8-17c2ca38798c.png)

**Comment by benetechMatt** [comment]
updated mockup. 

problem set owners, whether they created the set or not, need the ability to change some problem set level settings and share a solvable version of the set. The allow for this we are adding a problem set controls box which is only available for problem set owners.

The border of the controls box is #A7C5DA, background #FAFAFA. The box width matches that of three problem cards.

Actions users can take:
- Customize the math tools palettes. button label "Customize math palettes". Selecting this opens the same modal as when the set is first created.
- Change whether descriptions are required for each step. Addressed in #1094. checkbox label "Require description for each step".
- Share a /solve/ link to users. label "Share Problem Set". selecting the button opens the share problem set modal as described in #1086

![updated mockup](https://user-images.githubusercontent.com/49413678/79628990-4cb86e00-810b-11ea-89ff-45d6b836d2b5.png)

**Comment by johnhbenetech** [comment]
@benetechMatt What does problem set 'owner' mean. You say both of the following:
* "whether they created the set or not"
* "is only available for problem set owners"

Are we actually talking about user accounts here? Like what if a set was created by an unauthenticated user?

Or is the task simply to show these controls to anyone at the '/edit' view for a set?

**Comment by benetechMatt** [comment]
Yes, talking about user accounts. 

If the user is not signed in and they access the /edit link it should then be assumed the user is the owner.

Is it possible to tell if set has an owner when it’s accessed via a link? @johnhbenetech

**Comment by johnhbenetech** [comment]
@benetechMatt I guess let me ask it an easier way... In what cases should we NOT show these controls to someone looking at the '/edit' view?

**Comment by benetechMatt** [comment]
There would never be a situation where the controls are NOT shown to someone looking at the /edit view.  If we later lock down editing abilities to just owners then that would affect more than just these controls so there is no point to hiding just controls.

**Comment by jscholes** [comment]
Surfacing this as an issue which has not undergone accessibility review, but is marked as ready for development.

CC @alexrcabral

**Comment by johnhbenetech** [comment]
@alexrcabral another question that came up in a development meeting:

If a problem set creator uses the 'change math symbols' button to switch a problem set from palette A to palette B. Which of the following should happen:

1. Palette B should show for all previously created share/edit/solve/etc links as well as those going forward. This option is actually the quickest to accomplish technically.

2. Palette A should still show for any previously created links, but going forward all created links should show palette B.

**Comment by alexrcabral** [comment]
@johnhbenetech 
2. Palette A should still show for any previously created links, but going forward all created links should show palette B. 

While retroactively changing problem sets could be useful for a number of changes, it would run into issues with things like changed first steps or changed prompts. I think it would be beneficial to follow the same framework for all changes so teachers don't get confused around what does or doesn't update retroactively.

**Comment by alexrcabral** [comment]
As confirmation on the accessibility side, this should be good to continue with development so long as it follows heading-related best practice.

**Comment by abaranowska1** [comment]
From QA side: 

**Question:**

1. "Chang math symbols" button change palette on every single problem in the problem set, is it expected result or should we have an option to choose in which problem we want to change pallet?

![Peek 2020-06-10 09-47](https://user-images.githubusercontent.com/61964176/84241282-9025cc00-aaff-11ea-8706-0d6f7983ff09.gif)


**Verified cases:** 
- Problem set controls table is added
![image](https://user-images.githubusercontent.com/61964176/84241347-a6cc2300-aaff-11ea-9ed0-e54a3c14f972.png)
- Problem set controls include "Require Explanations and Include my work when sharing" radio buttons and it works during sharing 
![image](https://user-images.githubusercontent.com/61964176/84241396-b3e91200-aaff-11ea-8b33-1954896ee3f2.png)
- Chang math symbols button is added and change pallet as in the above comment "Palette A should still show for any previously created links, but going forward all created links should show palette B."
- Problem Set owners can change settings in their problem sets
- Unmarked "Require Explanations" allow to adding steps without description
- Marked "Require Explanations" required  steps with description
- Unmarked "Include my work when sharing" share problem without user answers
- Marked "Include my work when sharing" share problem with user answers
- Share My Answer and Share Problem Set buttons share data as expected ( with and without answers ) 

**Verified on:**
- Problem set controls verified on the teacher, student, other and unauthenticated user
- QA instance
- Ubuntu 16.04 OS
- Mozilla Firefox v. 77.0.1

**Comment by johnhbenetech** [comment]
@abaranowska1 pallette should apply to all problems, so I think we are all good

**Comment by abaranowska1** [comment]
@johnhbenetech Ok, thanks. Now I can close it.
