### ISSUE TITLE
Make the math editor text box grow in height dynamically so that text does not bleed beyond the editor box

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#113]
refer to screenshots in issue #110

**Comment by afijal** [comment]
![image](https://user-images.githubusercontent.com/2682379/41858516-63455e24-789a-11e8-821a-c8f23bcdc321.png)

**Comment by afijal** [comment]
So I've tried to hack it in various ways but I couldn't get to the stage when it worked and looked well with every scenario, @NSoiffer would it be possible to expose height of field in MathField from MathLive, or I'm missing something and it is already possible to get it's height?

**Comment by johnhbenetech** [comment]
my opinion is as long as this doesn't affect a screen reader's ability to voice the content, i'm fine with it.

**Comment by sueannma** [comment]
I think as long as we're okay to provide a height that allows for a few layers of fractions, this should be fine to start. We might encounter accessibility issues that will require a different accommodation later (same with the horizontal scroll), but let's address that when we get there.

**Comment by kkrawczyk123** [comment]
I confirm that my work area is not expanding anymore and a scroll is showing when content does not fit into a regular window. It seems that screen readers consider multi-layers of fractions independently of the scroll and an expanding field.
