### ISSUE TITLE
Creators can create a key for problems / problem set

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1131]

**Comment by alexrcabral** [comment]
Problem: As a teacher, I want to be able to create a key for my problem set, while still being able to share the set with my students without revealing the answers. 

Solution: When sharing the problem set, there should be a toggle option to share work, default inactive. When the toggle is inactive, the link is a default link which creates a duplicate workable version of the set, with all work blank. If the toggle is set to active, the link will update automatically. This second link will create a duplicate workable version of the set, with the work filled to the extent that it was at time of duplication.

**Comment by benetechMatt** [comment]
![mockup showing this setting in the problem set controls.](https://user-images.githubusercontent.com/49413678/79629262-b46fb880-810d-11ea-9a0e-343b3af62268.png)

**Comment by johnhbenetech** [comment]
I having trouble parsing through this. Can you provide some examples of what this would look like?

Also what would happen if they toggled it inactive after they had previously enabled it and attached work?

**Comment by benetechMatt** [comment]
Let’s hold on this issue.

________________________________

**Comment by benetechMatt** [comment]
Changing this setting is not retroactive to work that been started. Example:
1. teacher shares with the "include my work when showing" option on and assigns via link
2. student 1 opens the link and begins the problem set and edits the teacher's steps
3. teacher changes the "include my work" setting to off and does not re-share the link.
4. Student 1 opens their work and it looks the same as before
5. Student 2 opens the set link and they do not see any work in the steps.  only the prompts.

**Comment by johnhbenetech** [comment]
That's fine, I still dont understand what "work" means in this context. With the changes performed in #816 - isn't this possible already? How would we decide what should be considered a 'prompt' vs. 'prompt requiring more than one step' vs 'work' when deciding what to remove?

**Comment by benetechMatt** [comment]
"Work" means adding additional steps.
#816 only addresses the need for educators to add steps to a problem after it's been created.  The need here is for educators to change whether the work is in the problem set when students begin solving the problems.

**Comment by johnhbenetech** [comment]
@benetechMatt So we can just assume anything that isn't the prompt is "work".

Or to put simply, when 'include my work' is OFF - only the prompts are sent?

**Comment by benetechMatt** [comment]
Yes, anything that isn't the prompt is 'work'.  Since it's not possible to edit step 1 when working the problem your last statement is a good summary.

**Comment by jscholes** [comment]
Surfacing this as an issue which has not undergone accessibility review, but is marked as ready for development.

CC @alexrcabral

**Comment by alexrcabral** [comment]
@jscholes 
Issue surfaced in previous conversation: 

> Why not have a sharing-related modal or form, and surface this as a check box for a particular sharing action? Having it be a toggle which applies to a link somehow is super non-obvious.

I think this is a really fair point, and something I was considering previously. Originally we landed on this design because there was no unified sharing modal, so it was the only way to have an effect on sharing to Google Classroom or Microsoft Teams. 

Now I think it makes sense to be located with the other two related problem set options: requiring explanations, and math palettes. These cannot only be accessed through a sharing modal because they also effect the experience for owners of the problem set who are also going through to solve it, including students who are creating their own practice problems.

**Comment by johnhbenetech** [comment]
@alexrcabral Please provide final decision and new mockups if needed by EOD (or we will need to spike this to next sprint)

**Comment by alexrcabral** [comment]
@johnhbenetech Final decision continuing forward unless I hear otherwise from @jscholes. 
Mockups are not changing for this issue.

**Comment by alexrcabral** [comment]
Summary: 

When sharing the problem set, there should be a toggle option to "Include my work when sharing". Work is defined as any steps & step descriptions added to the problems aside from the initial prompt. This toggle is by default inactive, and any change to the toggle is remembered and persists within that owner's problem set. 

![Mockup showing the title "Problem set controls:", with two toggleable options beneath it. "Require explanations" is shown as active, and "Include my work when sharing" is shown as inactive.](https://user-images.githubusercontent.com/49413678/79629262-b46fb880-810d-11ea-9a0e-343b3af62268.png)

### Inactive 
While the toggle is inactive, any sharing of the set results in a duplicate /solve view of the set, with only the prompt & first step shared. 

### Active 
When the toggle is set to active, any sharing of the set results in a duplicate /solve view of the set, with the prompt, first step, **and any following steps/step descriptions** shared as well.

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**
![image](https://user-images.githubusercontent.com/61964176/84244682-4986a080-ab04-11ea-90d1-c2af5e6bfa86.png)
-  "Include my work when sharing" toggle is inactive by default 
- Any change to the toggle is remembered and persists within that owner's problem set
- Changing this setting is not retroactive to work that been started
- When the toggle is set to active, any sharing of the set results in a duplicate /solve view of the set, with the prompt, first step, and any following steps/step descriptions shared as well.
- While the toggle is inactive, any sharing of the set results in a duplicate /solve view of the set, with only the prompt & first step shared.
![Peek 2020-06-10 10-29](https://user-images.githubusercontent.com/61964176/84245450-5952b480-ab05-11ea-88f1-eb6da79a4d9d.gif)
