### ISSUE TITLE
Division / Fractions don't show up in problem preview

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1137]
Bug: Division bars don't show up in the problem set preview. 

<img width="1343" alt="Screen shot of problem set titled Review: Solving for x. Two of the problems contain division, such as x/4 - 5 = 3. The fraction bar between the x and the 4 is not shown." src="https://user-images.githubusercontent.com/47576069/79603190-b5b6cc00-80a0-11ea-9f62-1ab937be9010.png">

<img width="1321" alt="Screen shot of the individual problem view, showing x/4 - 5 = 3 displaying with the fraction bar." src="https://user-images.githubusercontent.com/47576069/79602927-3a551a80-80a0-11ea-95e1-3f50482c84a9.png">

This should be fixed to display properly.

**Comment by johnhbenetech** [comment]
@alexrcabral can you give:
environment
example URL
browser + OS

**Comment by alexrcabral** [comment]
This bug is no longer occurring for me in the current build so it's likely fixed, though I'll keep an eye out.
