### ISSUE TITLE
After select only one, two or three from four available pallets still, all are available during creating a new problem

### ISSUE THREAD

**Issue by abaranowska1** [benetech/MathShare#1139]
**Describe the bug**
After select only one, two or three from four available pallets still, all are available during creating a new problem.

**To Reproduce**
1. Log in as Teacher via google account'
2. Click on 'Create a Problem Set'
3. Mark only Edit and Operators Palletes ( another two checkboxes shouldn't be marked )
4. Click 'Next'
5. Click 'Add new Problem'

**Actual result**
All pallets are displayed
**Expected behavior**
Only selected pallets should display

**Screenshots**
![palettes](https://user-images.githubusercontent.com/61964176/79749190-10edf600-830f-11ea-8da1-21568ff14cc6.gif)

**Desktop:**
 - OS: [Ubuntu 16.04]
 - Browser [Chrome, Firefox]
 - Version [Version 81.0.4044.92 (Official Build) (64-bit); Version 75.0 (64-bit)]

**Comment by benetechMatt** [comment]
I don't know if this is a bug or was originally intentional.  When the set is opened in the /solve view via the share link only the selected palettes are available. Now that students are using this same method for creating their own problem sets it makes sense that this should be changed to the expected behavior as  listed by @abaranowska1. 
@alexrcabral agree?

**Comment by alexrcabral** [comment]
Agreed with @abaranowska1, this should be changed to the expected behavior: only the selected palettes should show up on problem set creation.

**Comment by abaranowska1** [comment]
**Tested with success**

After select only one, two or three from four available pallets still, chosen pallets are available during creating a new problem. There is also an edit pallet option related to the issue: #1129 

![Peek 2020-06-10 13-12](https://user-images.githubusercontent.com/61964176/84262578-21a43680-ab1e-11ea-9254-f6aebc94d3d9.gif)
![gif](https://user-images.githubusercontent.com/61964176/84262586-24069080-ab1e-11ea-9d0a-897944cda5ea.gif)
