### ISSUE TITLE
User is logged out after opening Problem set from the Library

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/MathShare#1143]
**Describe the bug**
When the user opens Problem set from the external Library, user is not logged in.

**To Reproduce**
1. Log in
2. Click Explore Problem Set Library link
3. On Google sheet click chosen Problem set

**Expected behavior**
User should be sent to chosen Problem set and stay logged in. At this moment user is logged out.

**Screenshots**
![ms bug](https://user-images.githubusercontent.com/51324797/79764060-2837de00-8325-11ea-896e-24372d29e09b.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Browser: Chrome
 - Version: 80.0.3987.149

**Comment by rupeshparab** [comment]
Problem set library has links of sets on Production
If a user logs in QA env and opens a set from the library, the user would need to login again as both have different session because of different environments

**Comment by johnhbenetech** [comment]
@rupeshparab thanks that makes sense.

@bognasoldev89 we can wait till this is released to prob and double check, but I think this is safe to close for now

**Comment by bognasoldev89** [comment]
@rupeshparab thanks for information!

@johnhbenetech sure, we'll remember about this
