### ISSUE TITLE
3 dot tree is not working on Problem set page

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/MathShare#1151]
**Describe the bug**
Options for Problem set from its page are not available. "Duplicate set" is visible after clicking 3 dots but it's not clickable.

**To Reproduce**
1. Log in
2. Create Problem set
3. Open Problem set
4. Click 3 dots right to Problem sets name

**Expected behavior**
The displayed menu is clickable and responsive.

**Screenshots**
Gif of unclickable menu on Problem set page:
![ms bug](https://user-images.githubusercontent.com/51324797/80361899-fae9b380-8881-11ea-862d-87cb8a4c9ef9.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Browser: Chrome 
 - Version: 80.0.3987.149

**Additional context**
The issue was noticed during testing #844

**Comment by rupeshparab** [comment]
Pushed a fix for this

**Comment by abaranowska1** [comment]
The displayed menu is clickable and responsive. 
![tea](https://user-images.githubusercontent.com/61964176/80468445-79585b00-893f-11ea-9ca9-2345d796174c.gif)
@rupeshparab 
Problem Set is duplicated after click on this option, but only for Teacher account. It could be related to this issue  https://github.com/benetech/MathShare/issues/1157

**Comment by rupeshparab** [comment]
@abaranowska1 
Have commented about the existing working of Recent Sets on #1157
