### ISSUE TITLE
Student's problem sets are not saved in Recent Problem after create 

### ISSUE THREAD

**Issue by abaranowska1** [benetech/MathShare#1157]
**Describe the bug**
Student's problem sets are not saved in the Recent Problem after create, so there is also not available to duplicate problem set by click 3 dot tree near the title on Problem Set page.

**To Reproduce**
1. Go to Mathsahe and log in as Student
2. Click on Create a Problem Set button on the Homepage
3. Add problem, try to duplicate set by click 3 dot tree near the title
4. Go back to Home Page

**Actual result:**
Just created Problem Set is not displayed on Recent Sets list 

**Expected behavior**
New Problem Sets should display on Recent Sets list 

**Screenshots**
Here you can see that after create problem by Student, Recent Sets list is not updated. 
![stu](https://user-images.githubusercontent.com/61964176/80472543-271a3880-8945-11ea-8219-da09dd06592c.gif)

**Desktop:**
 - OS: Ubuntu 16.04
 - Browser Google Chrome Version 81.0.4044.92,Firefox Browser 75.0

**Comment by rupeshparab** [comment]
Currently Recent sets shows different data based on type of the user
For Teachers, it will show the Problem Sets they have created
For Students, it shows the Problem Sets which the student has started solving

**Comment by abaranowska1** [comment]
@rupeshparab 
Still, I'm not sure if it is expected result:
![Peek 2020-04-30 15-37](https://user-images.githubusercontent.com/61964176/80717279-072b7600-8af9-11ea-8292-af26407288e5.gif)
I tried to start solving a problem created by the user and it is not displayed in Recent sets.

**Comment by alexrcabral** [comment]
@johnhbenetech & @abaranowska1 
Thanks for surfacing this!
I've created the new issue #1175 in product backlog to address it.
