### ISSUE TITLE
Update copyright 

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1170]
Change 2019 to 2020 in the copyright of the universal footer

**Comment by sinabahram** [comment]
Just a quick note that this can be a computed value to avoid text changes each year.

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on QA env

**Verified cases**
- Going through MS app and checking the universal footer

**Summary**
Year on the universal footer is always 2020.

**Attachments**
Exemplary screenshots from different pages:
![ms 1170 1](https://user-images.githubusercontent.com/51324797/81792009-bf005080-9507-11ea-8db8-02c4b8aa36fa.png)
![ms 1170 2](https://user-images.githubusercontent.com/51324797/81792011-bf98e700-9507-11ea-86e8-e614382064c5.png)
![ms 1170 3](https://user-images.githubusercontent.com/51324797/81792014-c0317d80-9507-11ea-95cb-15f5b1055877.png)
