### ISSUE TITLE
blank screen bug

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1174]
From a teacher:
"I've been using mathshare for a few weeks now, and it's been working well! Thank you for creating this! I do think I will use it in my classroom going forward.

My students and I haven't run into any glitches so far, until today. One of my students ran into a blank page when trying to do his assignment today.

Any ideas?"

christina.irvine@guhsdaz.org

![image_6487327](https://user-images.githubusercontent.com/49413678/80772167-6ac69b00-8b1b-11ea-8e21-104b6f068170.jpg)

I've requested information about the browser, how often it happens, and what happens they they reload the page.

**Comment by benetechMatt** [comment]
followup from the teacher on 5-4-20
"I followed up with my student, and he was never able to load the page. The same thing happened to him today with the new assignment I posted. Two other students ran into this problem. I forgot to ask what version of Safari he is using. I'll let you know when I hear back from him."

**Comment by johnhbenetech** [comment]
We will need a lot more details before we can do anything with this.

Example problem sets, OS version, browser version.

**Comment by alexrcabral** [comment]
@benetechMatt checking back in on this, were you able to get further context from talking with the teacher? 

e.g. example problem sets / assignment link that's causing the issues, OS version, browser version, how it was assigned

**Comment by benetechMatt** [comment]
Have not received a response from the user on this issue. Now that school is over it's unlikely we can replicate it on their end
