### ISSUE TITLE
Incorrect heading positioning on problem set solve view

### ISSUE THREAD

**Issue by jscholes** [benetech/MathShare#1183]
On the `/solve` view for a problem set, the "Actions for this Problem Set" heading is incorrectly positioned after the "Problems in this Set" heading (right before the list of problems).  On `/edit`, the heading layout is correct.  It needs to be consistent across both views.

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on qa env

**Verified cases**
- comparing /edit and /solve views

**Summary**
Heading is positioned in the same way on both views.

**Attachments**
- edit view
![ms 1183 edit](https://user-images.githubusercontent.com/51324797/82660592-edc6a700-9c2a-11ea-9f6e-f04679c67e6c.png)

- solve view
![ms 1183 solve](https://user-images.githubusercontent.com/51324797/82660603-f323f180-9c2a-11ea-9607-83b451e1b681.png)
