### ISSUE TITLE
Carry out analytics audit

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#1188]
Evaluate tools to capture google analytics and intercom event tracking that occurs in the application. During the next full regression testing, document the page elements/actions that are tracked on each application view.

**Comment by bognasoldev89** [comment]
@johnhbenetech as mentioned on the call, we didn't find a good tool covering google analytics and intercom, so will go with [google analytics debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) and use it during regression.
cc @abaranowska1
