### ISSUE TITLE
Dynamically shift the editor section down as the history grow

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#119]
The goal here is to minimize the space taken up by the history section and make the tool more intuitive for users who were inclined to click there. 

Refer to design mocks available at: https://9rrjf0.axshare.com/home.html
![image](https://user-images.githubusercontent.com/7883873/40878179-0e8605a6-6642-11e8-80c0-9ffd05bc85dc.png)

**Comment by johnhbenetech** [comment]
For clarity, here's the specific interaction we need:
https://gfycat.com/DisfiguredSilentGossamerwingedbutterfly

**Comment by afijal** [comment]
should be fine now

**Comment by oskarhinc** [comment]
It works as expected now.
