### ISSUE TITLE
Subscript and superscript displays brackets

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1190]
Curly brackets are added When using the sub or superscript buttons in the live and QA versions.

![screenshot showing the issue on a chemical equation entered ](https://user-images.githubusercontent.com/49413678/81987024-84c5aa80-95fe-11ea-97ba-0229c0a2e4db.png)

**Comment by benetechMatt** [comment]
Problem set showing this issue mathshare.benetech.org/#/app/problemSet/view/73HITH6ZXBHIG

**Comment by alexrcabral** [comment]
Thanks for surfacing this Matt! 

I was able to reproduce this. The issue seems to be just with the buttons on our side, since the shortcuts ^ and _ are working successfully. I also checked this on MathLive and the superscript/subscript buttons are currently working there.

**Comment by benetechMatt** [comment]
They had worked on production in the past during some of my testing for science equations but I don't have a specific date. It was weeks ago

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**
- After click subscript and superscript values displays without curly brackets
![Peek 2020-05-22 12-57](https://user-images.githubusercontent.com/61964176/82662507-4481b000-9c2e-11ea-8c8f-eab4f82d27af.gif)

**Verified on:**
-QA environment
- Firefox v 75.0
- Google Chrome v. 81.0.4044.92

**Comment by abaranowska1** [comment]
@johnhbenetech I retested this ticket due to #1214 . Still it works fine, after click subscript and superscript values displays without curly brackets

**Verified on:**

- QA environment
- Firefox v 76.0.1
- Google Chrome v. 83.0.4103.61
- Ubuntu 18.04.4 OS
