### ISSUE TITLE
additional steps not showing up bug

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1191]
When creating a new problem, additional steps do not show up on the shared link unless the creator of the set views a problem again. 
process to duplicate the error
1. create a problem and open it
2. add a step and select finish
3. open the share link in a new tab and view the problem steps.  the second step will now show up
4. go back to the original problem set and open the problem, see that the second step was saved and displays.
5. copy the share link again and open it
6. select the problem on the /solve version and the second step now displays

video of the issue https://www.loom.com/share/cc150e860ac4432babc7ed2e647cb8b4

**Comment by johnhbenetech** [comment]
@benetechMatt thanks, can you try a few things:

1. When you first open the problem in the solve view can you refresh the browser and clear cache refresh to see if the second step appears?

2. Instead of using the 'finish to add' the step, can you use the actual 'add step' button then finish and see if it still happens

This will help narrow it down

**Comment by benetechMatt** [comment]
@johnhbenetech 
1. when going to the /solve view refreshing the page and clearing the cache did not make a difference.  refreshing the /edit page did cause the second step to show up in /solve.  

2. Selecting 'add step' instead of finish did not make a difference

I tested this for additional steps and it has the same issue.

**Comment by johnhbenetech** [comment]
@benetechMatt one more thing (for now)

Can you try waiting 10s after clicking finish before you click the share button?

**Comment by benetechMatt** [comment]
waiting 10s didn't make a difference.  
discovered another odd thing of the numbering changed /edit on the left /solve on the right.  the new problem I added is just " solve 8"
![image](https://user-images.githubusercontent.com/49413678/81992364-eb4fc600-9608-11ea-81b1-c1be9b89da50.png)

**Comment by rupeshparab** [comment]
I have merged fix for both issues in QA env and raised the PRs for master

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on qa env

**Verified cases**
- Creating Problem set -> a few problems
- Providing answers for some of them
- Sharing permalink
- Opening link and checking problems details
- Checking problems numeration

**Summary**
I always got every problem and answers if provided by a shared link. Numeration is consistent.

**Attachment**
- Sharing problem set with one problem with answers:
![ms 1191](https://user-images.githubusercontent.com/51324797/82554454-3ec09780-9b66-11ea-9a58-7f2b0f469cec.gif)

- Sharing problem set with a few problems with answers:
![ms 1191 3](https://user-images.githubusercontent.com/51324797/82554481-4ed87700-9b66-11ea-8697-d5dee62a9d57.gif)

- Comparing problems numeration:
![ms 1191 2](https://user-images.githubusercontent.com/51324797/82554510-61eb4700-9b66-11ea-88a0-8ecc399cd957.gif)
