### ISSUE TITLE
Bug: 'Create Problem Set' no longer working if you go into example set and return back to homepage

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#1199]
To reproduce:
* Go to QA Dashboard
* Click into one of the example sets
* Go back to dashboard
* Try clicking 'create problem set'

Button doesn't seem to do anything in this case nor does it log any network activity of JS errors.

It does however work the first time on the dashboard.

**Comment by johnhbenetech** [comment]
@rupeshparab please investigate if related to recent backend/step changes

**Comment by rupeshparab** [comment]
this bug was introduced in this feature: https://github.com/benetech/MathShare/issues/973, I have merged its fix in QA env

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on qa env

**Verified cases**
- following reproduction steps for
-- teacher
-- student
-- not signed in user

**Summary**
This issue no longer occurs

**Attachment**
Exemplary gif:
![ms 1199](https://user-images.githubusercontent.com/51324797/82315718-01c09d80-99cc-11ea-83d9-3a7c8abb3b34.gif)
