### ISSUE TITLE
"All problems" link does not take users to the problem set when opening links to specific problems

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1204]
I opened a link to a specific problem https://mathshare.benetech.org/#/app/problem/edit/MKDDO4MAUSZHK
When I clicked "all problems" it took me back to a new browser window instead of the problem set.  This happens if I'm editing the set or if I'm solving problems and whether I'm the set owner or not

**Comment by benetechMatt** [comment]
I'm thinking they user should be redirected to the problem set and then follow rules the same as if they had been shared the correct problem set link

**Comment by abaranowska1** [comment]
**Tested with success**
I can't reproduce the bug, every time when I clicked "All problems" button users are taken to the problem set view. In my opinion, it was fixed.
![Peek 2020-06-04 11-47](https://user-images.githubusercontent.com/61964176/83742187-6a10af80-a659-11ea-8dd4-e996e2d65e16.gif)
