### ISSUE TITLE
Add non-student roles, job title, and grades into Intercom

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1206]
For anyone that does not select that they are a student when signing up, this information should be added to Intercom as new custom fields
Role - teacher, non-teacher, etc. 
grade
job title

Is there any additional information currently being asked or collected when users sign up?

**Comment by benetechMatt** [comment]
would also like the change to be retroactive

**Comment by alexrcabral** [comment]
@benetechMatt That's the full list of information currently being asked during Teacher sign up, so I don't believe there's information in addition to that.

**Comment by alexrcabral** [comment]
To clarify, this is asking for "user types", as well as "grades" and "role" for the teacher user type.

**Comment by benetechMatt** [comment]
@johnhbenetech has added this information retroactively to Intercom. New fields of "Grade" "UserType" and "UserRole
Grade: K-5, 6-8, 9-12, 13+, none
UserType: teacher, other
UserRole: Teacher, technology coach, media specialist, special education, educator, curriculum, developer, administrator

@johnhbenetech will this information now automatically go to Intercom for new users as well?

**Comment by johnhbenetech** [comment]
@benetechMatt I want to do an audit of that, so if it's okay I can put this in the backlog

**Comment by rupeshparab** [comment]
I have updated the role key to userRole

**Comment by johnhbenetech** [comment]
@rupeshparab something is still off here. The user get's registered in intercom, but still doesnt have the custom attributes.

I sniffed all the network packets and I dont see that data being passed to intercom. I see several events being passed - but they dont include the additional fields - nor are they in the initial ping.

Please audit the implementation as I wonder if there is some change to how intercom expects these values. They reference IntercomSettings instead of just passing in the event:
https://www.intercom.com/help/en/articles/179-send-custom-user-attributes-to-intercom#how-do-i-do-it

I worry the current react library we are using is dead. We probably need to pull it out and replace it with this one:
https://github.com/devrnt/react-use-intercom

Let me know if I'm missing something obvious

**Comment by rupeshparab** [comment]
@johnhbenetech 
I checked it on QA, saw some warnings from Intercom: 'Intercom not initialized yet'.
It seems Intercom is not getting initialised by the time we are calling its api and it doesn't queue the requests to send the events after initailizing.

Also the library has been inactive for some time: https://github.com/nhagen/react-intercom/issues/73

Will integrate react-use-intercom in its place

**Comment by johnhbenetech** [comment]
Hey @rupeshparab, I still think there is something going on here which warrants a closer look:

I think there are two issues here potentially:

1. I created a new mathshare user on QA and it doesn't seem that they ever made it into Intercom. I guess it's possible it takes longer than I think for Intercom to display a new user, but inspecting the network traffic I see the event getting sent but I don't see the user email anywhere in the header or the form body, so I wonder if intercom is getting an event without an email:

![Intercom Trace](https://user-images.githubusercontent.com/12927553/88098227-0b4abb00-cb5f-11ea-9c0f-55deb988000f.png)

2. I think we also need to change where this data is sent. I think we should actually be using custom attributes and not an event for user details specifically:
https://www.intercom.com/help/en/articles/2433372-custom-attributes-vs-events-what-s-the-difference

So those same data keys should be used, they just need to be passed to the component like here:
https://github.com/nhagen/react-intercom/issues/31

I think we might be able to handle this with react-intercom as a quick fix, but should still get an estimate for how long we think it might take to switch to react-use-intercom.

**Comment by johnhbenetech** [comment]
Also here's the trace of the first intercom ping (before the event), user details seems to be blank:

![Intercom Ping Trace](https://user-images.githubusercontent.com/12927553/88099879-67aeda00-cb61-11ea-81f7-b9a000c16657.png)

**Comment by rupeshparab** [comment]
@johnhbenetech 
Custom attribute seems to be solving the issue
Ping:
![image](https://user-images.githubusercontent.com/6897505/88217445-2eb75800-cc7c-11ea-9f3f-c91d397cdace.png)

Event:
![image](https://user-images.githubusercontent.com/6897505/88217508-45f64580-cc7c-11ea-8f21-abb7897e1b33.png)


I will checkout the react-use-intercom for ETA on porting our current intercom api calls to it

**Comment by johnhbenetech** [comment]
@rupeshparab This still isn't functioning as expected. We no longer need to pass the userType, userRole, and grades as metadata within an event.

Instead we need to pass them as part of the intercomAttributes as keys in addition to user_id, email, name

**Comment by rupeshparab** [comment]
@johnhbenetech 
I have moved the user-details event data to custom attributes
![image](https://user-images.githubusercontent.com/6897505/88303069-30d4f180-cd24-11ea-9712-07ecc91a5763.png)

**Comment by johnhbenetech** [comment]
Sorry @rupeshparab one more fix (it's my fault for not looking into this more)

So userType and userRole are working great now, thanks!

Unfortunately Intercom does not accept arrays for values, only text. So we will need to concatenate the array into a string (with comma-separated values, so like: "K-5,6-8,9-12,13+"

Let me know if you have other questions, sorry again!

**Comment by rupeshparab** [comment]
No worries John, I have pushed a fix for it

**Comment by johnhbenetech** [comment]
Working!
