### ISSUE TITLE
Added color scheme to design

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#121]
- apply blue on white binder paper color scheme (good to think about customization/settings later)
- notice how the palette section is grouped by color

![image](https://user-images.githubusercontent.com/12927553/41332970-b9ac4d00-6e94-11e8-955a-cb5342345cc6.png)

**Comment by oskarhinc** [comment]
@johnhbenetech I've got some questions about the grouping:
1. Should there be three rows of buttons?
2. The placing of the buttons should look rather like the purple or green ones (additional row or additional column) or maybe exactly like the screenshot?
3. On the screenshot, I can see two 'minus' signs, one 'plus' and additionally one 'plus/minus'. In the code, there's only 'plus/minus'. How to handle it?
4. In the code, I've found also 'stack below' button, not visible on provided screenshot. Should it be in the yellow group?

**Comment by johnhbenetech** [comment]
I separated out background change work as #156 

Let's go with the following for now:
![image](https://user-images.githubusercontent.com/12927553/41553438-ab6d8db6-72e6-11e8-998f-e7ff743a0246.png)

I will check with the user-facing team to see if we need to add the other buttons

**Comment by oskarhinc** [comment]
Thanks for clarification John! I'll stick to the provided design.
