### ISSUE TITLE
"My work" cannot be deleted by "Backspace and Delete" keyboard buttons on QA instance 

### ISSUE THREAD

**Issue by abaranowska1** [benetech/MathShare#1214]
**Description**
"My work" cannot be deleted by "Backspace and Delete" keyboard buttons on QA instance 

**To Reproduce**
1. Go to 'https://mathshare-qa.diagramcenter.org'
2. Go to one of the Problem
3. Type something in "My work" field 
4. Try to delete inputs by keyboard buttons

**Expected behavior**
Data should be deleted after click Backspace/Delete buttons

**Screenshots**
I cannot delete typed values 
![Peek 2020-05-25 16-52](https://user-images.githubusercontent.com/61964176/82823649-3e970380-9ea8-11ea-8597-dca1bfae910f.gif)

![image](https://user-images.githubusercontent.com/61964176/82869102-00442780-9f2e-11ea-89f1-7353d7bd503a.png)

**Desktop:**
 - OS: [Ubuntu 16.04]
 - Browser [Chrome v.81.0.4044.92, Firefox v.76.0.1]

**Additional context**
It works on a production https://mathshare.benetech.org/#/ instance

**Comment by johnhbenetech** [comment]
@rupeshparab can you take a look at this?

**Comment by rupeshparab** [comment]
I tried using delete and backspace after selecting text from keyboard as well as mouse, it seems to be working for me
the only case when it doesn't work is if I select the text and the move focus somewhere else

@johnhbenetech can you check if you can replicate this?

**Comment by johnhbenetech** [comment]
@rupeshparab seems to be specific to Ubuntu oddly

You get a "TypeError: r is undefined" in main.js - so not that helpful/

@alexrcabral can you help prioritize a bug that seems to only affect Ubuntu OS?

**Comment by johnhbenetech** [comment]
Also as a reminder @rupeshparab it doesnt occur on prod, so probably broken by a recent change. Maybe mathlive upgrade?

**Comment by rupeshparab** [comment]
@johnhbenetech 
I have reverted the MathLive upgrade PR temporarily to check if the upgrade is causing this issue.

@abaranowska1 
Can you please retry if backspace is still now working on Ubuntu?

**Comment by abaranowska1** [comment]
@rupeshparab Now it works :+1:

**Comment by rupeshparab** [comment]
@abaranowska1 Thanks for checking it

@johnhbenetech 
It seems this issue was caused because of the MathLive upgrade.

**Comment by johnhbenetech** [comment]
@rupeshparab can you try taking the latest mathlive and see if this issue was repaired there? If not we can revert and raise a big report.

I know we upgraded in order to fix some issues from other tasks so I don't want to completely roll back unless we have to

**Comment by rupeshparab** [comment]
@johnhbenetech 
I have upgraded mathlive to 0.52.0, everything seems to we working locally on the new version

@abaranowska1 Can you check if you are facing the backspace issue on Ubuntu?

**Comment by johnhbenetech** [comment]
@rupeshparab Now the whole problem view page doesnt load with a bunch of JS console output. Ok so I guess let's roll back to the working version for now. 

@abaranowska1 Once the rollback is done please retest #1182 and #1190

**Comment by rupeshparab** [comment]
@johnhbenetech 
I have reverted the upgrade

**Comment by alexrcabral** [comment]
@johnhbenetech In regards to priority, if it's between staying in sync with MathLive and being fully operational on Ubuntu, I would prioritize the MathLive update. We can also surface bugs to Arno as needed.

**Comment by abaranowska1** [comment]
@rupeshparab 
Once again I confirmed that now I didn't notice any issue with backspace/delete on MathShare QA instance using new Ubuntu 18.04.4 OS
