### ISSUE TITLE
Add text and icon labels

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#122]
- sections of the palette should be labelled underneath
- add step (with + icon)
- done (with thumbs up icon)
- note: merge the "solved" and "save work" into a single "done" button
- clear all

![image](https://user-images.githubusercontent.com/7883873/40878222-b3ed72b8-6642-11e8-871a-28c4db8de780.png)

**Comment by johnhbenetech** [comment]
Icons:

Add step
![icons8_xbox_cross_100px](https://user-images.githubusercontent.com/12927553/41518818-4899da04-7279-11e8-8beb-9c0549f6c8d7.png)

Done
![icons8_thumbs_up_96px](https://user-images.githubusercontent.com/12927553/41518838-5b551bf4-7279-11e8-8205-200d45c1a73f.png)

Clear all
![icons8_unavailable_96px_1](https://user-images.githubusercontent.com/12927553/41518877-99df088a-7279-11e8-964a-b618747e0285.png)

**Comment by oskarhinc** [comment]
It looks as expected, but I'll wait for @jo
 opinion about using Icons from the library before moving this issue to 'Done'.

**Comment by oskarhinc** [comment]
It looks as expected, but I'll wait for @johnhbenetech opinion about using icons from the library before moving this issue to 'Done'.

**Comment by johnhbenetech** [comment]
yes, using font awesome is totally fine. thanks

@oskarhinc @afijal
