### ISSUE TITLE
Students can't archive problem sets

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1227]

**Comment by alexrcabral** [comment]
Looks good, thanks @rupeshparab!

**Comment by abaranowska1** [comment]
**Tested with success:**

**Verified cases:**

- Now Students have 'More option' button
- Archive option is available 
- Students can archive problem sets 
- Students can restore archived problem sets

![Peek 2020-08-12 13-10](https://user-images.githubusercontent.com/61964176/90010419-1a291700-dca0-11ea-91fa-0198ce2c34b6.gif)


**Verified on:**

- Ubuntu 18.04 OS
- Staging QA environment
- Student user
- Firefox v.79.0
