### ISSUE TITLE
provide complete list of symbols

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#124]
provide the comprehensive list; not just the symbols/operations that are not available via the keyboard. 

This is to better serve students who prefer using the virtual keys or students with limited mobility using an eye gazer.

**Comment by sueannma** [comment]
Neil, please add to: https://docs.google.com/document/d/1vJZ4yWsoAtqeOplG1JAv1dgSxfA5VNXeJ7jZx7veaTc/edit?usp=sharing

**Comment by NSoiffer** [comment]
I'm working on an update to the linked document. For a talk I gave earlier, here is an (old style) palette for Calculus:
![image](https://user-images.githubusercontent.com/1545836/41832134-8d1ab47e-77ff-11e8-8838-a56a49d4d0d5.png)

It is possible that category layout (the layout of the groupings) we are using for Algebra doesn't work as well for Calculus and maybe other areas.

**Comment by NSoiffer** [comment]
See [this google doc](https://docs.google.com/document/d/1vJZ4yWsoAtqeOplG1JAv1dgSxfA5VNXeJ7jZx7veaTc) for listing of all symbols up through calculus that are used 99.95% of the time in the books I have analyzed.
