### ISSUE TITLE
Update Share Modals to Surface Link Text

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1241]
The “Share My Answers” modal and the “Share Problem Set” modal should be updated to include the surfaced link text, with the copy updated as listed below. The link should be surfaced within a text box, with ellipses for truncation (similar to how browsers handle longer URLs), followed by a button to Copy Link. 

### Share My Answers
New Copy: “Submit your answers to Google Classroom or Microsoft Teams, or share using the link below.”

<img width="607" alt="Mockup of 'Share My Answers' modal. The description is updated, and the surfaced URL is now in a textbox below the description, along with its accompanying button immediately to the right with the Copy icon and labelled 'Copy Link'. Beneath in the same column are the Google Classroom and Microsoft Teams buttons." src="https://user-images.githubusercontent.com/47576069/84204539-4043f800-aa60-11ea-844e-ec289126be99.png">

### Share Problem Set
New Copy: “Share your problem set through Google Classroom or Microsoft Teams, or share using the link below.”

<img width="613" alt="Mockup of 'Share Problem Set' modal. The description is updated, and the surfaced URL is now in a textbox below the description, along with its accompanying button immediately to the right with the Copy icon and labelled 'Copy Link'. Beneath in the same column are the Google Classroom and Microsoft Teams buttons." src="https://user-images.githubusercontent.com/47576069/84204564-4c2fba00-aa60-11ea-8c20-c56ee2ca4167.png">

----------

## Updates from 07/22: 

**Updates from the last accessibility standup**: There's a significant difference between truncation in the base case (fully expanded window, 100% zoom) and user-initiated truncation (shrinking the window, zooming in, or increasing font size). I've updated the original mockups & scope to incorporate this. 

The “Share My Answers” modal and the “Share Problem Set” modal should be updated to include the surfaced link text, with the copy updated as listed below. The link should be surfaced within a **text box of the same size as the link**, followed by a button to Copy Link. 

### Share My Answers
New Copy: “Submit your answers to Google Classroom or Microsoft Teams, or share using the link below.”

<img width="674" alt="Mockup of 'Share My Answers' modal, with the URL shown in full. The description is updated, and the surfaced URL is now in a textbox below the description, along with its accompanying button immediately to the right with the Copy icon and labelled 'Copy Link'. Beneath in the same column are the Google Classroom and Microsoft Teams buttons." src="https://user-images.githubusercontent.com/47576069/85351413-89606700-b4b8-11ea-9893-44dea5e2d79c.png">

### Share Problem Set
New Copy: “Share your problem set through Google Classroom or Microsoft Teams, or share using the link below.”

<img width="750" alt="Mockup of 'Share Problem Set' modal, with the URL shown in full. The description is updated, and the surfaced URL is now in a text box below the description, along with its accompanying button immediately to the right with the Copy icon and labelled 'Copy Link'. Beneath in the same column are the Google Classroom and Microsoft Teams buttons." src="https://user-images.githubusercontent.com/47576069/85352255-58813180-b4ba-11ea-92d3-e233150b767d.png">

If the link is shortened, the text box should overflow to a new line. 

Example:

<img width="507" alt="Screen Shot 2020-06-22 at 6 52 43 PM" src="https://user-images.githubusercontent.com/47576069/85351918-ac3f4b00-b4b9-11ea-9d1d-dce07e62e951.png">

**Comment by jscholes** [comment]
I'm not sure about truncation here.  How do users know which part(s) of the link they've highlighted if part of it is hidden?

**Comment by alexrcabral** [comment]
Users will be able to interact with the text box similarly to how they interact with a standard address bar on a browser. If users decide to highlight only a portion of the link, the displayed text follows the cursor when highlighting with a mouse or keyboard so they know where their selection stops.

**Comment by sinabahram** [comment]
Sorry, I don’t get it. We’re displaying the entire URL, right? if not, then this won’t work.

**Comment by alexrcabral** [comment]
@sinabahram What are the reasons this wouldn't work?

**Comment by sinabahram** [comment]
How is the text able to be copied in full if it is truncated?

**Comment by jscholes** [comment]
Truncating content is generally confusing, particularly when targeting users with any learning disabilities or other cognitive concerns.  Users may ask internal questions such as:

1. Is there something wrong with the website, the individual field, or both?  Should I report this?
2. Is there something wrong with my screen enlargement software/other assistive technology?  Who should I report this to?
3. If I hit copy, will the button only copy what is visible?  If so, how do I copy the whole thing?  If not, how do I know what it will copy?  

When users are being prompted to copy something to their clipboard, it is a best practice to ensure they know exactly what that is.  A screen reader must read the whole link regardless, which is non-negotiable and means that you now have divergence between what is visually displayed and available to a subset of people.

Finally, truncated URLs are terrible security hygiene.  All younger students, and particularly those with any additional learning difficulties, are less likely to question the safety of URLs, and the situation is not improved by using truncation.  Students should be encouraged to have access to a full URL which is a security best practice.

**Comment by alexrcabral** [comment]
@jscholes Solid, thank you for explaining your reasoning! I get where you're coming from that what is standard might not be the best way to address the issue (e.g. with truncated URLs as engendering too much trust in the safety of the URLs). 

How do you envision this adapting to different screen sizes, e.g. if someone shrinks their window to be smaller than the URL length, if a user has low vision and has the screen zoomed in 500%, or on a mobile screen? 

Having the text box expand vertically and the text overflow is one option, though it can be difficult to read when the link overflows multiple lines & reduce the discoverability of other share options. Internal scroll areas could also pose difficulties for voice navigation systems.

**Comment by alexrcabral** [comment]
**Updates from the last accessibility standup**: There's a significant difference between truncation in the base case (fully expanded window, 100% zoom) and user-initiated truncation (shrinking the window, zooming in, or increasing font size). I've updated the original mockups & scope to incorporate this. 

The “Share My Answers” modal and the “Share Problem Set” modal should be updated to include the surfaced link text, with the copy updated as listed below. The link should be surfaced within a **text box of the same size as the link**, followed by a button to Copy Link. 

### Share My Answers
New Copy: “Submit your answers to Google Classroom or Microsoft Teams, or share using the link below.”

<img width="674" alt="Mockup of 'Share My Answers' modal, with the URL shown in full. The description is updated, and the surfaced URL is now in a textbox below the description, along with its accompanying button immediately to the right with the Copy icon and labelled 'Copy Link'. Beneath in the same column are the Google Classroom and Microsoft Teams buttons." src="https://user-images.githubusercontent.com/47576069/85351413-89606700-b4b8-11ea-9893-44dea5e2d79c.png">


### Share Problem Set
New Copy: “Share your problem set through Google Classroom or Microsoft Teams, or share using the link below.”

<img width="750" alt="Mockup of 'Share Problem Set' modal, with the URL shown in full. The description is updated, and the surfaced URL is now in a text box below the description, along with its accompanying button immediately to the right with the Copy icon and labelled 'Copy Link'. Beneath in the same column are the Google Classroom and Microsoft Teams buttons." src="https://user-images.githubusercontent.com/47576069/85352255-58813180-b4ba-11ea-92d3-e233150b767d.png">


If the link is shortened, the text box should overflow to a new line. 

Example:

<img width="507" alt="Screen Shot 2020-06-22 at 6 52 43 PM" src="https://user-images.githubusercontent.com/47576069/85351918-ac3f4b00-b4b9-11ea-9d1d-dce07e62e951.png">

**Comment by alexrcabral** [comment]
@Sanjog1605 On this task please go through the comments on this issue to understand the requirements, then check over the accessibility of anything covered within the scope of this issue. This should include two different types of sharing modals, with some updated copy, a link surfaced within a text box, and the option to copy the link. 

These changes are pushed to QA which for reference is at https://mathshare-qa.diagramcenter.org/#/app

**Comment by Sanjog1605** [comment]
Good Morning Sir,

I was able to find the issue #1241 from the “Development Board” page on GitHub. I researched the QA Mathshare page and created two separate accounts, one as a student and other as teacher. I was able to find the “Share My Answer” button when I was logged in as a student. However, I am unable to find “Share Problem Set” button and therefore the modal.

So, sticking to “Share My Answers” modal, which I found on [,](https://mathshare-qa.diagramcenter.org/#/app/problemSet/solve/ZLRFUCPFEJROU) I would like to mention few things which are as follows:

Screen Reader: NVDA 2020.1
Browser: Mozilla Firefox 78.0.2
OS: Windows 10 Pro 1909

### Issues and Comments:

•	There is not enough visible focus on the edit box where the link is displayed. At least there should be a dotted rectangular focus box visible when the keyboard or mouse focus is on the edit field.

Now what I am asking is actually more of a doubt rather than an issue. As per my understanding, ‘Share My Answer’ is to be used for sharing the answer with a teacher/student. So, my question is why there is a necessity to display a url at all and why not just present the modal with three buttons – ‘Copy link’, ‘Share on Google Classroom and’, ‘Share on Microsoft Teams’. The edit box is just a read only box where one cannot edit the link so, is it a good choice to display the link at all? I am thinking from the point of view of a learning disabled or a person suffering from some cognitive disorder. I think if there are just buttons then, won’t it be simpler for them?

**Comment by Sanjog1605** [comment]
Adding to my previous comment, I found the "Share Problem Set" modal by following the steps given by Alex sir. I found the same issue in the modal as mentioned in my previous comment.

Alex sir, this issue can be solved by the method you mentioned, i.e., by highlighting the text but it  will again bring in a set of another guidelines related to contrast and highlight. One alternative can be to highlight the edit box itself. I noticed that the edit box which actually shows the URL does not have proper border to it. the text is difficult as of now. As a result, it will be hard for people with low vision to differentiate between the rest of the non-interactive text and the edit box.

**Comment by johnhbenetech** [comment]
HI @rupeshparab , this seems to be an issue of Firefox vs. Chrome - let's see if we can investigate why the visual focus is different

**Comment by alexrcabral** [comment]
Thanks @johnhbenetech for finding the Firefox/Chrome discrepancy. 

And thanks @Sanjog1605 for posting the full information. Best practice for text boxes (particularly those for copying a link) is having the full text highlighted when it receives focus, which allows greater ease of use, in this case copying the link. This also fulfills the 2.4.7 Focus Visible criterion. I'm not concerned about the highlight contrast since it's a standard highlight, which maintains a 14.09:1 contrast ratio. 

Just as clarification, this isn't an edit box, but a read-only text box (no characters can be added or deleted).

**Comment by rupeshparab** [comment]
I was able to replicate the issue on Firefox for Windows, have fixed the focus css for it.
Also, I have added text selection on input coming into focus

**Comment by Sanjog1605** [comment]
@rupeshparab  sir, I have also checked the focus issue in the modal. It is fine and the rest of the elements in the modal are also working fine. I have checked for the following issues:

1. Dismissal behavior, by pressing the escape key and by using the close button.
2. The "Google" and "Microsoft" buttons.
3. The copy link button and the alert that is announced by screen reader
4. The focus highlight on the read only edit box.

## Observations
1. The dismissal behavior is normal and working fine. The focus after dismissal lands on the same previous location as it should.
2. The URL edit box is highlighted when the screen reader focus and keyboard focus lands on it. However, when the screen reader focus is on the list items above the read only edit box, the highlight still remain inside it. (Refer to the figure below)
Note: I checked for keyboard focus by using the tab key for people using the machine with keyboard or a switch.

![Edit box highlight still remains even if the screen reader focus is somewhere else](https://user-images.githubusercontent.com/68078108/88617195-98d46080-d0b3-11ea-82ec-d7fd2d8d80fb.png)

3. The copy button also works fine and screen reader also announces an alert saying that the link has been copied to the clipboard.
4. 'Google' and 'Microsoft' buttons are also working as they should. However, a new window opens in my machine instead of a new tab. Screen reader says that a new tab will open.

**Comment by alexrcabral** [comment]
@rupeshparab According to scope: "The link should be surfaced within **a text box of the same size as the link**" 

As mentioned, there's a significant difference between truncation in the base case here, and truncation as user initiated (eg through zooming the screen, shrinking the window smaller than the modal, etc). Please adjust this. The window may need to be increased in size horizontally (e.g. to match the mockups), since it's important that the link is not truncated on a fully expanded browser window. 

Base case mockups for reference (no changes): 

<img width="674" alt="Mockup of 'Share My Answers' modal, with the URL shown in full. The description is updated, and the surfaced URL is now in a textbox below the description, along with its accompanying button immediately to the right with the Copy icon and labelled 'Copy Link'. Beneath in the same column are the Google Classroom and Microsoft Teams buttons." src="https://user-images.githubusercontent.com/47576069/85351413-89606700-b4b8-11ea-9893-44dea5e2d79c.png">

<img width="750" alt="Mockup of 'Share Problem Set' modal, with the URL shown in full. The description is updated, and the surfaced URL is now in a text box below the description, along with its accompanying button immediately to the right with the Copy icon and labelled 'Copy Link'. Beneath in the same column are the Google Classroom and Microsoft Teams buttons." src="https://user-images.githubusercontent.com/47576069/85352255-58813180-b4ba-11ea-92d3-e233150b767d.png">

**Comment by johnhbenetech** [comment]
@alexrcabral what should happen when the screen width is less than the margins+link text+copy button width?

**Comment by rupeshparab** [comment]
@alexrcabral 
there was a third mockup in the end of the original [post](https://github.com/benetech/MathShare/issues/1241#issue-635779999), not sure in which case that is intended to be used:
![image](https://user-images.githubusercontent.com/6897505/89941098-2ed1c480-dc38-11ea-9763-6e31e9a05e0a.png)

**Comment by alexrcabral** [comment]
@johnhbenetech In that case, the overflow should occur. @rupeshparab This would result in the third mockup which you've attached.

From the original copy: 
> If the link is shortened, the text box should overflow to a new line.

This shortening may occur through zooming in, shrinking the window, or having a particularly small screen size which results in the screen width being less than the margins+link text+copy button width. 

I want to stress that the overflow is **not the base case**. The modal, by default, should surface the full link, as described in the first two mockups. When shrunk beyond the ability to present the link in full, only then does the overflow take place.

**Comment by rupeshparab** [comment]
@alexrcabral 
I have pushed a fix to increase the modal width, such that the text won't overflow till it can fit the modal with 90% screen width, in other cases the height of text area will auto expand to fit the text overflow

**Comment by alexrcabral** [comment]
Thanks @rupeshparab!
