### ISSUE TITLE
Setup Intercom to send emails from our domain

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1252]
this will reduce the chances of our emails being marked as spam. Requires DKIM verification
Instructions:
https://www.intercom.com/help/en/articles/182-a-guide-to-sending-email-from-your-own-address

I want emails to come from mattn@benetech.org

**Comment by johnhbenetech** [comment]
@benetechMatt This would need to go through Benetech IT since it deals with the Benetech domain

**Comment by benetechMatt** [comment]
Request sent to IT 6-17-20

**Comment by benetechMatt** [comment]
IT help desk ticket https://bugs.benetech.org/browse/DSK-15170

**Comment by alexrcabral** [comment]
Update from the Jira thread: 

>I created the cname record and did the domain verification from the intercom.com admin settings. You should be good to go now to use your address.
>Greg

Is this resolved @benetechMatt?

**Comment by benetechMatt** [comment]
Confirmed that this is working and verified with a test email to myself and to users
