### ISSUE TITLE
Sharing My Answers doesn't work on MS Teams and Google Classroom 

### ISSUE THREAD

**Issue by abaranowska1** [benetech/MathShare#1255]
**Describe the bug**
Sharing My Answers doesn't work on Teams and Google Classroom. I noticed the fact that when I clicked "Share My Answer" button and I want to copy a link to the problem with answers - all works and I can see the steps in view mode, but when I want to share answers on Google Classroom or MS Teams I see only First step. Toggle "Include my work when sharing" should be = true to share answers on MS Teams or Google Classroom 

**To Reproduce**
1. Create a Problem Set and add a Problem
2. Add some steps, explanations to the Problem
3. Click "Share My Answer" button and choose MS Teams or Google Classroom 
4. Share a link for example on MS Teams Channel
5. Go to the link and check if answers are shown 

**Expected behavior**
After sharing a link with answers on MS Teams or Google Classroom steps should be shown 

**Screenshots**
![Peek 2020-06-15 09-56](https://user-images.githubusercontent.com/61964176/84747841-1aff3e80-afb8-11ea-8480-8733aac4ab59.gif)

**Desktop:**

- QA instance
- Ubuntu 16.04 OS
- Mozilla Firefox v. 77.0.1

**Comment by abaranowska1** [comment]
@rupeshparab I cannot log in to my testing accounts on teams - so I cannot check if this issue was fixed, do you think it could be related to this hotfix? 
![image](https://user-images.githubusercontent.com/61964176/85014438-90107680-b166-11ea-8f03-ca5ca8601d4e.png)

**Comment by johnhbenetech** [comment]
@rupeshparab I think this might be related to #1148. Teams requires HTTPS links, so we should adjust link for both teams and classroom to send the https version

**Comment by abaranowska1** [comment]
Ok, @rupeshparab now I can log in and share my answers on MS Teams Channel but only in Private Window / Incognito. I also see that answers/steps are shown in a view mode. 
![Peek 2020-06-19 14-07](https://user-images.githubusercontent.com/61964176/85131133-87877100-b236-11ea-90fa-5a5a1c2d27ca.gif)
![Peek 2020-06-19 14-09](https://user-images.githubusercontent.com/61964176/85131137-89e9cb00-b236-11ea-9753-87d7be839f65.gif)

**Comment by johnhbenetech** [comment]
@abaranowska1 can you try to clear your cache before using in non private browsing and see if that works?

Also are you hitting the "Share my Answers" button, because that is intended to show the view mode version.

The share solve version has moved under the three dots menu next to the problem set title

**Comment by abaranowska1** [comment]
@johnhbenetech It seems my issue was related to the old cookies, now it works also in nonprivate browsing mode. The second thing is fine, I know that it should be visible in the view mode, I wanted to confirm that, small misunderstanding :) 
I think we can close it.
