### ISSUE TITLE
Prompt highlighting bug

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1258]
Bug: The prompt text box is not being highlighted by clicking and dragging using a mouse or touchpad. (macOS 10.15.4) 

Double/triple clicking and keyboard highlighting functions fine.
This occurs both on problem set creation and during problem set solving.
The bug is present in both qa and live versions.

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- QA env
- Browsers:
-- Chrome v83.0.4103.116
-- Firefox v78.0.1
-- Safari v12.03.3

**Verified cases**
- Manipulating over the prompt field due to provoking highlight

**Summary**
The prompt field was highlighted as expected on every used browser.
