### ISSUE TITLE
Consolidate "assign" trigger in Intercom

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1259]
Currently assigning a problem set via google classroom, microsoft teams, and the link are recorded as separate actions to Intercom. In addition to those three options it would be helpful to have a single "assigned a set" event sent to Intercom. This event would be triggered any time an educator or "other" user clicks on any of the three problem set sharing options.

The current setup makes it difficult to filter users along with other factors.

**Comment by johnhbenetech** [comment]
@benetechMatt just to double check, for share to classroom for example - you would want two actions fired off - 'assigned a set' as well as 'assign via google'?

**Comment by benetechMatt** [comment]
@johnhbenetech that is correct

**Comment by rupeshparab** [comment]
I have added the event: 'assigned-a-set'

**Comment by abaranowska1** [comment]
**Tested**

- Event 'assigned-a-set' was added to the app 
![Selection_001](https://user-images.githubusercontent.com/61964176/90001817-31f99e80-dc92-11ea-8540-80a6666ded5e.png)

- After clicking share MS Teams button two actions fired off - 'assigned a set' and "assign-a-set-microsoft-team"
![Selection_003](https://user-images.githubusercontent.com/61964176/90001884-40e05100-dc92-11ea-8f34-76dbfbeaadd5.png)

- After clicking share Google Classroom button two actions fired off - 'assigned a set' and "assign-a-set-google-classroom"
![Selection_002](https://user-images.githubusercontent.com/61964176/90001902-450c6e80-dc92-11ea-98d6-a9e93147018c.png)

-After clicking Share My Answers ( google, ms teams ) button same two events fired off - 'assigned a set' and "assign-a-set-google-classroom", 'assigned a set' and "assign-a-set-microsoft-team"
![Selection_008](https://user-images.githubusercontent.com/61964176/90002060-72591c80-dc92-11ea-9135-29bfc32f0270.png)

 @rupeshparab Could you check it ?  cc @johnhbenetech
- After clicking Share Problem Set button two actions fired off - 'assigned a set' and "assign-a-set-link", but after clicking Copy link button nothing happens

![Selection_004](https://user-images.githubusercontent.com/61964176/90002084-7c7b1b00-dc92-11ea-86a7-b48533e59d09.png)

-After clicking Share My Answers actions 'assigned a set' and "assign-a-set-link" doesn't exist and also after clicking Copy link button nothing happens


**Verified on:**
- Ubuntu 18.04 OS
- Staging QA environment 
- Teacher and Other users
- Google Chrome v. 84.0.4147.125

**Comment by rupeshparab** [comment]
@abaranowska1 
assigned-a-set and assign-a-set-link events were being fired on opening the Problem Set modal, I have moved them to the Copy Link button

**Comment by abaranowska1** [comment]
@rupeshparab Now I can't see assigned-a-set and assign-a-set-link events anywhere, neither after clicking the share problem set button nor after pressing the copy link button.
![Peek 2020-08-13 09-00](https://user-images.githubusercontent.com/61964176/90103960-b48e6680-dd43-11ea-8489-a8bae23b137a.gif)

**Comment by rupeshparab** [comment]
@abaranowska1 
I had pushed a change for resizing the copy link text box (https://github.com/benetech/MathShare/issues/1241), it caused the copy link feature to break and its event wasn't being sent
I have pushed a fix for it, you should see events on clicking the copy link button, but I haven't added any event for opening the modal

**Comment by abaranowska1** [comment]
Thanks @rupeshparab, now all events are linked fine. 

**Tested with success**
- After clicking share MS Teams button two actions fired off - 'assigned a set' and "assign-a-set-microsoft-team"
- After clicking share Google Classroom button two actions fired off - 'assigned a set' and "assign-a-set-google-classroom"
- After clicking Copy link button two actions fired off - 'assigned a set' and "assign-a-set-link"

**Verified on:**

- Ubuntu 18.04 OS
- Staging QA environment
- Teacher and Other users
- Google Chrome v. 84.0.4147.125
