### ISSUE TITLE
make delete and undo buttons more prominent

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#126]
use more prominent symbols: 
icons in comments

**Comment by johnhbenetech** [comment]
You can use the following files:

![icons8_trash_104px](https://user-images.githubusercontent.com/12927553/41518743-edf3c880-7278-11e8-9db6-2ef61281de91.png)

![icons8_undo_104px](https://user-images.githubusercontent.com/12927553/41518759-00ebd126-7279-11e8-8f42-06cab0976f17.png)

**Comment by afijal** [comment]
Looks fine to me
