### ISSUE TITLE
TTS button on create problem set scrolls with outer div

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#1269]
Steps to reproduce:

* Go to create a new problem set
* add several problems (enough to make the add problem to problem sets modal scrollable)
* scroll

Result: TTS button moves with the scroll and becomes hidden behind other elements

Expected: Button stays aligned with Benetech Mathshare text

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on QA env.
Browsers:
- Chrome v83.0.4103.116
- Firefox v77.0.1 

**Verified issues**
- Creating numerous problem sets with checking it's appearance

**Summary**
The modal looks consistent, the TTS button is available at any moment and no other UI issues occured.

**Attachments**
Chrome:
![ms 1269 chrome](https://user-images.githubusercontent.com/51324797/86346760-ad147180-bc5d-11ea-919b-14dc9ee30584.gif)

Firefox:
![ms 1269 firefox](https://user-images.githubusercontent.com/51324797/86346782-b4d41600-bc5d-11ea-98dd-72361142b3c2.gif)

**Comment by abaranowska1** [comment]
@rupeshparab 
I found one small css issue. You can see that TTS button is in the wrong place when we want to create a new problem only on Firefox Browser. 
![image](https://user-images.githubusercontent.com/61964176/86349018-c965dd80-bc60-11ea-910a-cd0a92649674.png)

**Comment by rupeshparab** [comment]
@abaranowska1 
I have pushed a CSS fix for Firefox

**Comment by abaranowska1** [comment]
@rupeshparab 
Thanks for fix on the Create Problem Set Page , now it looks fine
![image](https://user-images.githubusercontent.com/61964176/86441864-28812c00-bd0d-11ea-8906-65b2b53c29bd.png)
but please take a look for it, because after fix I found CSS issue also only for firefox here: ( Problem Edit Page )
![image](https://user-images.githubusercontent.com/61964176/86441852-24550e80-bd0d-11ea-8da4-b1c800843621.png)

**Comment by bognasoldev89** [comment]
@rupeshparab I looked at solving problem page on firefox 77.0.1 and all of the TTS icons are gone:
![Screenshot from 2020-07-03 10-26-12](https://user-images.githubusercontent.com/51324797/86450226-7c920d80-bd19-11ea-9c49-7f07f9ee9dec.png)

**Comment by rupeshparab** [comment]
I am not able to replicate the issue with firefox, tried it on version 55 and 57
![image](https://user-images.githubusercontent.com/6897505/86471645-66a53c80-bd5b-11ea-85aa-8bf97395bab3.png)

@johnhbenetech Can you check if you are also facing any issues while using firefox?

**Comment by bognasoldev89** [comment]
@rupeshparab I checked it moment ago again and it's back. Version of firefox didn't change.

**Comment by abaranowska1** [comment]
@rupeshparab Weird, now is also ok from my side 
![image](https://user-images.githubusercontent.com/61964176/86473135-a3176f00-bd40-11ea-9630-3e1884f12a93.png)
So I think we can close this one. Maybe some cookies made this UI issues.
