### ISSUE TITLE
Localization of page elements

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#127]
consider ability to accommodate additional languages (text on page)

**Comment by johnhbenetech** [comment]
I'm breaking out TTS and STT localization into other tasks. This task will be for localizing text on page.

This will be an architectural task to (I assume) add some templating engine that can read translations from a data file and render on page. Once again, let me know if we should spend some time in the sprint to transition to a framework before this work.

We won't include actual translation work at this stage, but you guys can start with english and polish for testing purposes if you want (hopefully there wont be too many words to translate)

**Comment by kkrawczyk123** [comment]
As there are no other languages available right now, I was just looking for some regression connected to text elements and I didn't find any, so I am closing this ticket.
