### ISSUE TITLE
Merge work & steps

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#128]
combine the markings/work with the steps to avoid creating two steps whenever edits are applied - notice the difference in the history section for the versions below.

![image](https://user-images.githubusercontent.com/7883873/40878404-69f78b8c-6645-11e8-8b75-6382b9e57b22.png)

![image](https://user-images.githubusercontent.com/7883873/40878406-7725e81c-6645-11e8-9db9-362fdf61c01c.png)

**Comment by afijal** [comment]
@johnhbenetech 
I've noticed that there are some elements that have such a style so "only the screen reader user should hear this" and therefore they are invisible.
I wonder how should we handle it in the "merged" rows so it wouldn't be confusing for such a users.

Currently, hidden values that we read are: row ordinal (1st, 2nd etc.), "math:" prefix, "reason;" prefix, "Delete" prefix.
So, how should we handle them in both 1st sub-row and 2nd sub-row of merged row, any ideas? I guess we can leave everything but row ordinal, and I'm not sure what would be the best attitude here.

**Comment by NSoiffer** [comment]
How about something like "<nth> step, after <reason>". For example, "First step, after cleanup".

Note: in the first picture, I think both "Step 1" and "Step 4" should be on the line above as that marks the start of their work. The second line represents the cleaned up expression and isn't a step the user did.

**Comment by johnhbenetech** [comment]
Good catch Neil. I agree.

The ordinal steps should be the user input ones (the one's with cross outs) and should be label as Step 1, Step 2, etc.

The step that renders out the reduced/simplified form should be the cleanup steps and should be voiced by the screen reader as 'First step, after cleanup', etc.

**Comment by afijal** [comment]
![image](https://user-images.githubusercontent.com/2682379/41650230-d3c8cc60-747d-11e8-83b5-2c8e3d0f98f2.png)

**Comment by oskarhinc** [comment]
@afijal Shouldn't the '_cleanup_' text have more faded color?

**Comment by afijal** [comment]
@oskarhinc  yeah, I wonder whether we should make such UI changes during tasks like this one or we will have a separate ticket(s) for UI improvements?
cc @johnhbenetech

**Comment by afijal** [comment]
@oskarhinc 
I've fixed the issue
![image](https://user-images.githubusercontent.com/2682379/41779094-03ef9360-7631-11e8-837a-3036d71b6123.png)

**Comment by oskarhinc** [comment]
@afijal It looks fine now.
