### ISSUE TITLE
Cross out and replace isn't read by TTS

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#1282]
When cross out and replace is used, the replaced test isnt read while in the My Work area

**Comment by rupeshparab** [comment]
Moved https://github.com/benetech/MathShare/issues/1279 and https://github.com/benetech/MathShare/issues/1282 to product input to just verify if we can change the speech rules, PR to change speech rules has been merged: https://github.com/benetech/MathShare/pull/1288

**Comment by johnhbenetech** [comment]
Ideally if possible within MathLive/MathML, we would be able to show the replaced number as a constant. 

With focus: 
<img width="191" alt="Mockup of crossout, 7x minus 13, end cross out, blank, equals zero. The blank portion is outlined by a dotted square the size of a constant, and highlighted in blue." src="https://user-images.githubusercontent.com/47576069/87229821-4deee500-c360-11ea-9389-d0ef163f0025.png">

Without focus: 
<img width="190" alt="Mockup of crossout, 7x minus 13, end cross out, blank, equals zero. The blank portion is outlined by a dotted square the size of a constant, with no highlighting." src="https://user-images.githubusercontent.com/47576069/87229829-57784d00-c360-11ea-9bbe-e0d244b11c4f.png">

Having the "replace" portion is helpful for students who may otherwise be worried about removing numbers instead of simplifying them, particularly if they have memory or cognitive difficulties. E.g. if they cross out 2/4 will they remember to replace it with 1/2? 

However, based on our earlier discussion @johnhbenetech, if this isn't possible within MathLive/MathML and the reason it was presented as an exponent in the first place was the next best workaround, then we should remove Cross Out & Replace entirely.

**Comment by johnhbenetech** [comment]
@rupeshparab can you explore using cross out and replace using the \boxed or \bbox markup which is available via mathlive? Right now it breaks a lot of stuff including nothing being read after the box and even subsequent steps breaking due to the boxed content. I assume it's being handled weirdly in the LaTeX to mathml conversion.

**Comment by rupeshparab** [comment]
There was '^' in the latex which we were using, I have replaced '^' with space '\\,'

**Comment by alexrcabral** [comment]
Looks great! It both presents appropriately as a constant now, and reads out "crossed out", the crossed out content, and  "end cross out"

**Comment by abaranowska1** [comment]
**Tested with success**
It also looks great for me. After click TTS button it reads out  "crossed out", the crossed out content, and "end cross out".
![image](https://user-images.githubusercontent.com/61964176/88386279-57406e80-cdb0-11ea-8cb7-6235725d3add.png)
