### ISSUE TITLE
Bug: Inappropriate surfacing of tooltips

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1293]
Problem: As a user working through a problem, when I type a keyboard shortcut for tools in the leftmost palette containing general controls such as calculate, the tooltip pops up unexpectedly.

<img width="1440" alt="Screen shot of QA site showing both calculate and cross out tooltips as active, despite focus clearly being in the text area of the math editor." src="https://user-images.githubusercontent.com/47576069/87200524-956a6800-c2b1-11ea-9433-9edc8cf274b1.png">

Affected tools: 
- Cross Out
- Cross Out and Replace
- Stack Below
- Calculate

Solution: The tooltip for tools in the leftmost section of the math palette should no longer appear when the shortcut is typed out on a keyboard. In order to be consistent with the other tools in the math palette. The tooltip should continue to be present when receiving focus.

Acceptance criteria: 

Given that I'm a user working in the my work section, when I type in a keyboard shortcut, then the appropriate tool should be activated, with no tooltip being surfaced. When I hover over the tools, or use a keyboard or external device to give focus to the buttons in the palette, the tooltips should be surfaced.

**Comment by alexrcabral** [comment]
Looks good, thanks @rupeshparab

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- QA env
- Ubuntu 18.04.4
- browsers:
-- Chrome 83.0.4103.116
-- Firefox 79.0

**Verified cases**
- triggering in the last and in the middle step edit by keyboard:
-- cross out
-- cross out and replace
-- stack below
-- calc
-- a few other shortcuts for control

**Summary**
The tooltip indeed does not surface after using the keyboard shortcut in any case. All of the palette's sections behave consistently.

**Attachment**
Chrome example:
![ms 1293 1](https://user-images.githubusercontent.com/51324797/89992155-2d7ab900-dc85-11ea-9d5d-0184512740e7.gif)
