### ISSUE TITLE
Problem solving screen issue in Safari

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1301]
Reported by Surya during user testing
Mojave 10.14.4 and Safari 12.1

Problem solving page loads and then goes white/blank

Requested video of issue and trying again after clearing cache.  Will update

**Comment by benetechMatt** [comment]
video of issue https://www.youtube.com/watch?v=VbFVeMtbekE&feature=youtu.be

**Comment by johnhbenetech** [comment]
@benetechMatt and @alexrcabral can either of you reproduce on your versions?

One thing that would be helpful is if she can check for any JavaScript console errors:

https://www.wickedlysmart.com/hfjsconsole/

**Comment by benetechMatt** [comment]
Surya emptied cache and still had the issue. The issue does not happen when in "private" mode

**Comment by johnhbenetech** [comment]
@benetechMatt any progress on JS console errors or checking the cookie/cache settings?

**Comment by benetechMatt** [comment]
Screenshot from Surya
Failed to load resource: the server responded with a status of 401 ()
Intercom not initialized yet
![screenshot of browser](https://user-images.githubusercontent.com/49413678/87713920-95b2a980-c770-11ea-9801-ec8c802157c1.png)

**Comment by benetechMatt** [comment]
related issue that was closed without resolution #1174 

Issue happened for Jane H during an Interview.	Safari 12.1.2. Emailed to get browser version

**Comment by alexrcabral** [comment]
I was able to replicate this on Safari (macOS 10.15.5), persisting on changed Safari preferences:
- Block all cookies both checked and unchecked
- Prevent cross site tracking both checked and unchecked

https://youtu.be/ysZHIRGs7As

I navigated to the main dashboard (not logged in), and noted the lack of the Intercom overlay. Then I went to an example set, and clicked the first problem. It loaded fine, but it seemed that whenever my cursor dropped below the editor into the math palette tools, the screen would glitch out briefly. If I persisted, it then glitched out completely. This full glitch resulted in being able to scroll a long blank page with the footer at the top, and the main Mathshare content at the bottom.

**Comment by johnhbenetech** [comment]
Thanks @alexrcabral can you also check the JS console and share any output?

https://www.wickedlysmart.com/hfjsconsole/

**Comment by alexrcabral** [comment]
## JS Console Readout:
<img width="1259" alt="Screen shot of javascript console output, with one red warning saying Failed to load resource, and three yellow warnings saying Intercom not initialized yet." src="https://user-images.githubusercontent.com/47576069/88854904-e67dc580-d1a6-11ea-9d4e-6143de934cd8.png">

- [Log] found hostname: mathshare.benetech.org (main.js, line 6)
- [Log] using server URL: https://mathshare-api.benetech.org (main.js, line 6)
- [Error] Failed to load resource: the server responded with a status of 401 () (user, line 0)
- [Warning] Intercom not initialized yet (main.js, line 6)
- [Warning] Intercom not initialized yet (main.js, line 6)
- [Warning] Intercom not initialized yet (main.js, line 6)

**Comment by johnhbenetech** [comment]
hey @rupeshparab I guess my hunch hear is that the tooltip library is crashing something on safari. I dont have a mac handy so cant dig too deeply

**Comment by rupeshparab** [comment]
@johnhbenetech 
I have replaced all button icons with SVGs, it has fixed the issue on Safari

**Comment by alexrcabral** [comment]
Confirmed working well now on mine after replicating the steps listed above.

> I navigated to the main dashboard (not logged in), and noted the lack of the Intercom overlay. Then I went to an example set, and clicked the first problem. It loaded fine, but it seemed that whenever my cursor dropped below the editor into the math palette tools, the screen would glitch out briefly. If I persisted, it then glitched out completely. This full glitch resulted in being able to scroll a long blank page with the footer at the top, and the main Mathshare content at the bottom.

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- QA env
- Mojave 10.13 High Sierra
- Safari 12.03.3

**Verified cases**
I reproduced @alexrcabral steps and played a little. I was opening solving problem page as a non-logged user, student and teacher.

**Summary**
I haven't spotted a blank page nor any glitching.
