### ISSUE TITLE
"Undo" button doesn't undo the last action in "My work" field

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/MathShare#1304]
**Describe the bug**
I noticed that "Undo" button doesn't do anything. As far as I am concerned it should undo the last action, like removing activity chosen from the palette.
Noticed behavior apply to creating a new step and to editing step as well.

**To Reproduce**
1. Go to solving problem page
2. Provide some action to my work field, for example, cross out part of the equation or provide a fraction
3. Click undo button

**Expected behavior**
The last action should be undone.

**Screenshots**
![ms undo equation](https://user-images.githubusercontent.com/51324797/87787504-083c8b80-c83c-11ea-9378-2e04c5ce62b4.gif)

**Desktop**
 - OS: Ubuntu 18.04.4 LTS
 - Browser: Chrome
 - Version: 83.0.4103.116

**Additional context**
The issue was spotted on the QA environment.
I spotted a weird issue for some of the operations, it is issued here: #1305

**Comment by rupeshparab** [comment]
I wasn't able to replicate the placeholder issue mentioned in #1305 but I have fixed the other issues of undo not working

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:**
- After click "undo" button it removes the last action
- After providing some action to my work field, for example, cross out part of the equation or provide a fraction and click "undo" button - last action s removed

![Peek 2020-07-28 09-09](https://user-images.githubusercontent.com/61964176/88637877-01730b80-d0bb-11ea-9844-fcbd887c8aca.gif)

**Verified on:**
- QA environment
- Google Chrome Version 84.0.4147.89
- Firefox Version 78.0.2
