### ISSUE TITLE
TTS - while creating a new problem set, values from solving problems page visited before are read

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/MathShare#1335]
**Describe the bug**
I noticed that while the user is solving the equation (while using TTS) and next is going problem creation, on the problem creation modal the values from solving problem pages are read.
Important - I was able to reproduce this issue by actually adding a step during solving a problem.
I was not able to reproduce this issue in incognito mode.

**To Reproduce**
1. Open problem page
2. Do a little solving in "my work" section
3. Click TTS button for it
4. Add step
5. Click MathShare logo
6. Click "+Create a new problem set"
7. Choose a palette
8. Click "Add new problem"
9. Provide some equation as a new problem (don't add a new problem yet)
10. Click TTS button on it

**Expected behavior**
Provided content should be read aloud.

**Screenshots**
Link to recorded TTS:
https://drive.google.com/file/d/1dYGK780keWvmIvJ8VR_0Bbnmh82iLnS1/view?usp=sharing

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04.4 LTS
- Browser: 
-- Chrome 83.0.4103.116
-- Firefox 78.0.2

**Comment by abaranowska1** [comment]
**Tested with success**
I cannot reproduce this issue anymore, so I think it was fixed. Provided content was read aloud correctly every time. 
Here is a link to the video: https://drive.google.com/file/d/1oxOxOwyO7AGmSoQoJO23ukRaRHoQXtvR/view?usp=sharing

I met here an issue with not working buttons which I mentioned in #1348, but after refreshing the page all works fine.

**Verified on:**
- Ubuntu 16.04
- Firefox v.79.0
- Chrome v. 84.0.4147.105
