### ISSUE TITLE
support image-based math content

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#145]
this would be to support diagrams (e.g., geometry) and other image-based content

**Comment by johnhbenetech** [comment]
this could potentially be supported through the scratchpad (scratchpad could have pen tool, circle tool, rectangle, line, and even picture embed)

**Comment by dserkowski** [comment]
There is the possibility to load a local image to ScratchPad. To do this we need:
1. Run ScratchPad, click the open image button and then choose an image:
![screenshot from 2018-07-02 10-45-43](https://user-images.githubusercontent.com/29867015/42154510-3c4f6d18-7de6-11e8-802f-12205c9616a5.png)
2. If you already have any content in ScratchPad the following menu will be displayed:
![screenshot from 2018-07-02 10-56-10](https://user-images.githubusercontent.com/29867015/42154709-bf1eed9a-7de6-11e8-80b4-4f546e1b0a40.png)
3. You can write something new on pasted images
There is the possibility to draw something manually ('Brash' option), line, filled or not filled geometry (rectangles, circles, elipses). 
![screenshot from 2018-07-02 11-05-19](https://user-images.githubusercontent.com/29867015/42155138-d9114670-7de7-11e8-9bf4-3a7b895bc5c8.png)

**Comment by dserkowski** [comment]
In addition to that, the content of ScratchPad is attached to particular step (when we try to edit an existing one the current ScratchPad is saved and the content of editing step is loaded)

**Comment by kkrawczyk123** [comment]
@johnhbenetech, I have a question according to a type of image files which user should be able to attach using sketchpad panel. Are there any requirements for that? I am able to add .jpg file on all browsers but for example safari doesn't allow choosing a .png file

**Comment by kkrawczyk123** [comment]
@johnhbenetech thank you for the quick answer. 

So as I am able to attach jpg and png in a sketch pad, add it to the step edit it, paste another image in 4 different combinations using chrome, egde, firefox and jpg on safari. Since inability of adding png file is a separate issue I think that we can close this one.
