### ISSUE TITLE
Unassociated "Recent Sets" showing up in Student Accounts

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1509]
Bug: A new student account is showing a lot of recent sets not associated with the account

<img width="992" alt="Screen shot showing many problem sets under recent sets, including example problem set titles, a problem set titled Transforming Formulas Practice (Literal Equations), and 9 instances of Solve for X." src="https://user-images.githubusercontent.com/47576069/98160201-b1ae9800-1e92-11eb-8c98-5cb90bdebd3a.png">

Clearing cache got rid of it, but the problem sets surfacing prior to the clear were not previously accessed and not associated with account, device, or session. 

@abaranowska1 Could you take a look at this and see if you can reproduce?

**Comment by abaranowska1** [comment]
@alexrcabral I logged in to my empty account and I picked that I'm a student and also today I created a new google account, in both cases, I cannot reproduce it your issue, but I will observe it.

**Comment by alexrcabral** [comment]
Thanks for checking @abaranowska1, I'll close this issue since it seems like it may be a weird edge case. If it ever repeats we can look into it further
