### ISSUE TITLE
Change cross-out/replace/calc color from red to blue

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#154]
Red is often associated with something being "wrong" or "incorrect," so use a more neutral color for the cross-out x's.

**Comment by johnhbenetech** [comment]
@sueannma 
take a look at these options and let us know which you prefer:

Green
![image](https://user-images.githubusercontent.com/12927553/41542429-c6fa1d82-72c9-11e8-892e-3dbffeb1b1bc.png)

Grey
![image](https://user-images.githubusercontent.com/12927553/41542449-d7ce327e-72c9-11e8-8829-2067bad54e15.png)


Black
![image](https://user-images.githubusercontent.com/12927553/41542476-e692b0aa-72c9-11e8-8e80-72f12a372ab6.png)

Blue
![image](https://user-images.githubusercontent.com/12927553/41542508-f7f7510c-72c9-11e8-8a50-d697c0767e46.png)

**Comment by pgesek** [comment]
@johnhbenetech is the final decision to use green?

**Comment by sueannma** [comment]
Let's go with blue - thanks!

**Comment by dserkowski** [comment]
I have tested it. It works correctly on Chrome and Firefox.
Result:
![screenshot from 2018-07-02 11-54-17](https://user-images.githubusercontent.com/29867015/42158112-d678ce58-7def-11e8-8c32-1477b7038c37.png)
