### ISSUE TITLE
Add new background image to design

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#156]
Update the background to match mockup as so:
![image](https://user-images.githubusercontent.com/12927553/41552574-03230930-72e4-11e8-8c79-a6abac17b374.png)

Several versions of the file(PNG,JPG,SVG) can be found in attached zip.

[paper.zip](https://github.com/benetech/MathEditor/files/2112328/paper.zip)

**Comment by oskarhinc** [comment]
I've found a way to avoid using a background image, and just use CSS to create paper sheet look. I think it's a better solution. Additionally, I've adjusted the look of the UI to be more natural and readable - I've removed bottom-border lines between steps, rounded the work area corners and separated it from the window edges. I'm attaching a screenshot to show how it looks now. I hope it's ok.

**Comment by oskarhinc** [comment]
@johnhbenetech How the buttons "undo" and "delete" should be displayed now? As the background changed, their previous color doesn't look perfect (see screenshot). Can I use for them the same color what's used in 'Discard', 'Done' and 'Clear all' buttons, or you have a better vision of it?
![btn colors](https://user-images.githubusercontent.com/19305104/41722846-e72b7824-7569-11e8-880e-d2996cbe181c.png)

**Comment by johnhbenetech** [comment]
Lets go with this for now:
![image](https://user-images.githubusercontent.com/12927553/41751093-74449510-7574-11e8-8433-b16ebc6cc4c5.png)

We can hide the 'Discard' button for now (since the user can clear all if they wish). I think we will add a 'back' button in the upper left of the page that will act more like the discard button.

I will create a different task for that.
