### ISSUE TITLE
Shift button palette to be configurable through data definition

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#162]
This task is a foundation task to allow for:

A. Different palettes to be rendered by choosing an option in the page itself
B. Associate a default palette for a problem set (i.e. this is an algebra problem set, this is a trigonometry problem set, so those button groups should appear)
C. If/when we get to some sort of 'user account' allowing a per-user default palette. These might be palettes 

This task will be to construct the necessary data model to allow for multiple configurations to be rendered on page. As a first goal, we can try to reproduce the single, current palette through a data driven approach.

I'm looking for help from Soldevelo to develop the best data structure for the job, but my assumption would be something like a JSON for each palette that would allow definition of:

1. The specific buttons that should be included
2. How the buttons should be grouped and how the groups should be labeled
3. The associated CSS styling for the button group (color for example)
4. Associated labels, screen reader labels, key shortcuts, LaTeX mark up, for each button

After this JSON is constructed (and probably stored as a file in the directory), the page will need to read it and render out the selected palette.

I'm not sure if this would be better suited once we get a proper framework in place, so let me know and I can prioritize this post the framework rewrite.

**Comment by oskarhinc** [comment]
@johnhbenetech using JSON file to store the configuration of the buttons palette is a good idea. I've checked it and it works fine, even without a framework. However, during exporting keyboard shortcuts to the configuration file, I've found some issues.

At first, there are shortcuts that can be used, but are not described in buttons palette - Shift+Backspace performs cross out, as well as Shift+Delete, but if nothing is highlighted it also highlights the previous character, before crossing it out. Shift+Delete act similar but with the next character. It works also when holding Ctrl key (cross out & replace).
If we're making shortcuts configurable, there shouldn't be hidden shortcuts, as they might not be allowed in a specific palette. Currently, I decided to always allow users to use Shift+Backspace and Shift+Delete, but only to highlight the previous/next character, in case shortcut is not allowed. If this solution sounds good to you, I can additionally add Shift+Backspace shortcut to the button, so it will always be visible and clear to a user.

An additional problem I encountered is with Ctrl+Enter shortcut - it's not working currently. There is code for handling it properly, but what I see is that Ctrl and Enter keys are never delivered in one event. I suggest to change this shortcut, so it would work properly.

I'm also wondering about the different type of shortcuts, where you're providing a command (like \cdot) and confirms it with the Enter key, or it's even replaced automatically without confirmation (like sqrt). Those shortcuts/commands are described in the mathlive library, so I think we won't change them and I would just stay with displaying proper buttons for a problem set, so those shortcuts could be seen when needed. Are my assumptions correct?

**Comment by afijal** [comment]
@oskarhinc Please make sure that every button has a invisible span like

`<span class="sr-only">title</span>`

while title = title from json

connected with #52

**Comment by oskarhinc** [comment]
Thanks for reminding @afijal

**Comment by oskarhinc** [comment]
@johnhbenetech Would that be OK for you if I would create a separate issue for adjusting those keyboard shortcuts improvements I mentioned, so we could test this one and mark it as done if everything works properly?

**Comment by johnhbenetech** [comment]
@oskarhinc yes, please do

**Comment by oskarhinc** [comment]
https://github.com/benetech/MathShare/issues/285 - issue to resolve those shortcuts assumptions and improvements

**Comment by kkrawczyk123** [comment]
Closed via https://github.com/benetech/MathShare/issues/285
