### ISSUE TITLE
Hide steps scrollbar when not used

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#168]
Scrollbar next to steps list could be hidden if it's not necessary (no enough steps to scroll).
![scrollbar](https://user-images.githubusercontent.com/19305104/41666137-0e507212-74aa-11e8-82a9-554cb8bdc867.png)

**Comment by johnhbenetech** [comment]
thanks for this Oskar. I always appreciate you guys pointing stuff out!
