### ISSUE TITLE
Indent steps to line up the left side with the red lines of paper

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#169]
I'd like to see how this looks and maybe get a round of user feedback to see if we keep it.

Let me know if you need clarification and I can provide a mock-up.

We should ensure that it is responsive and also works reasonably when the page is magnified/zoomed.

**Comment by oskarhinc** [comment]
@johnhbenetech Should 'My Steps' header be Indented as well, so then the steps would not stick to the red line perfectly? Or should we indent only steps? See screenshots.
![169](https://user-images.githubusercontent.com/19305104/41716784-e25ad13a-7557-11e8-8f1a-3d14e3bb5106.png)
![169 2](https://user-images.githubusercontent.com/19305104/41716785-e276e7a8-7557-11e8-8061-97837972f4d9.png)

**Comment by johnhbenetech** [comment]
I think the first one is closer. Line up the left edge of all the steps as well as "My Steps" with like a 5-10px padding off the red line (whichever looks better).

@oskarhinc I have an annoying question. This would be a separate task to revisit, but I'd like to hear how possible you think it is (please break it out into a backlog task if you think its doable):

I think it would be interesting to see if we could line up the work steps to always be within the lines on the pages. The lines wouldn't need to be regularly spaced (look at step 4 in the mockup below). I imagine something like  CSS psuedo elements like ::before and ::after could be used.

![image](https://user-images.githubusercontent.com/12927553/41761144-195a392a-75ab-11e8-8152-d24efee6c41b.png)

**Comment by oskarhinc** [comment]
@johnhbenetech I was thinking about it before a lot. It would improve the UI in an effective way. I think it's doable, and I've created backlog task for it - #189 where I described one of the possible ways of achieving this. I'm not sure if there won't be problems with it, but I think it's achievable.

**Comment by pawelcieszko** [comment]
I have tested a solution of this issue.
The steps are indented to line up the left side with the red lines of paper:
- using different screen display configuration 
- with many sample steps 
- after saving workspace and reopen

It seems it works as expected
