### ISSUE TITLE
Allow for user to create view-only sharable link for a problem 'answer'

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#175]
When a user is finished 'answering' a problem (either through the generic blank endpoint, or in response to a problem set), the user should be able to share their work by generating a link to a view only version of their work.

The link should only be associated with the state of the work at the moment the share button was clicked (as to avoid someone changing their answers after submission). If a student makes changes and hits the share button again, a completely new link should be created with the new state.

I haven't decided if a second click should destroy the first link, but I'm leaning towards that it should be preserved.

In addition to the backend work here, we will need to add a Share button as well as a way to display the link(s) to the user.

**Comment by johnhbenetech** [comment]
I think the URL would be something like mathshare.diagramcenter.org/edit/[long string]

the long string could be something like a SHA256. To be clear these SHAs should be unrelated to the SHA in the edit link (as to not allow a different user to easily access the edit view).

**Comment by oskarhinc** [comment]
I think the previously generated links can't be destroyed, as the user might want to create both links intentionally - for example to share both answers and ask which one is correct.

**Comment by kkrawczyk123** [comment]
I am able to generate different share view only url address after adding each step and I am able to open them in new tab/window - they display the correct amount of added steps.
