### ISSUE TITLE
Add back button to answer page

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#180]
This would bring the user to the main page. If work has been added since last save, the user should receive an alert (similar to what the previous 'discard' button did)

**Comment by kkrawczyk123** [comment]
@afijal, functional back button has been added but there is no alert message as mentioned in the description above.

**Comment by kkrawczyk123** [comment]
@johnhbenetech, dialog message has been added and it looks like:
![screenshot from 2018-08-28 15-40-50](https://user-images.githubusercontent.com/33342488/44726819-dfd90600-aad8-11e8-9662-5fade3c4ebd3.png)
And now we have the situation in which there are two Save buttons which cause different behavior:
- Save button from the problem page  - Success Problem Saved alert is displayed, edit url is generated, the user stays on the problem page.
- Save button from the dialog message -  Success Problem Saved alert is displayed and the user is moved to the homepage. 
I was thinking about unifying it somehow but we are not sure what would be the best solution, what is your opinion about that?

**Comment by afijal** [comment]
Just to clarify 
> edit url is generated
It is being generated earlier, we only display it after first save, not generate a new one

**Comment by johnhbenetech** [comment]
Maybe for now we can do the following:

No changes since last save:
Back button -> PSet page


Unsaved changes:
Back button -> Confirmation Dialog
Discard Changes -> PSet page
Save Changes -> Keeps you on answer page so you see edit URL
