### ISSUE TITLE
Ensure equation and explanation boxes are responsive regardless of window size or input size

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#181]
Related to #113 and #75 

Currently there are several issues where things break down visually based on window resizing, input size expansion, text magnification, or simply large input size. We need to prevent these as much as possible. The goal shouldn't be to have something fully mobile-friendly (i think there is too much going on at this stage), but to potentially enforce something like a minimum width for divs.

I think a preliminary step could be to split the input/palette area into a container of a single row with two columns. The left column (input & palette) can have a larger width, the right (explanation box and buttons) can be smaller. 

As always i'm open to suggestions!

**Comment by dserkowski** [comment]
I think reorganization HTML and splitting existing row into columns with rows will be a bit difficult. I have found another solution for that -> I can use flex property (CSS) and use it properly to prevent breaking these elements.

**Comment by pawelcieszko** [comment]
The sections are displayed properly -> using different window size
![image](https://user-images.githubusercontent.com/29859787/41924507-87f46b86-796a-11e8-883c-49ab0f7aeca2.png)

![image](https://user-images.githubusercontent.com/29859787/41924532-9b9562bc-796a-11e8-8cc2-a9f49e493190.png)

When a window is smaller than minimum width - the sections are not broken. A user just have to scroll horizontally
![image](https://user-images.githubusercontent.com/29859787/41924577-b15097fc-796a-11e8-970d-fed834c7a06f.png)

**Comment by pawelcieszko** [comment]
@johnhbenetech What's your opinion about this solution. May I mark this issue as 'Done'?

**Comment by johnhbenetech** [comment]
Looks good! We can close this task.

 I think we will need to revisit zooming in a later issue. The MathLive shortcuts overriding the standard Ctrl+,Ctrl- zoom shortcuts feels wrong to me.
