### ISSUE TITLE
Line up the work steps to always be within the lines on the pages

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#189]
The work steps should always be within the lines on the pages. The lines wouldn't need to be regularly spaced (look at step 4 in the mockup below).
![189](https://user-images.githubusercontent.com/19305104/41844872-e11f2254-7871-11e8-9df7-a8113687b206.png)

A possible way to do it is to treat steps as a list elements and use  CSS properly. Here's an example of similar work: https://css-tricks.com/how-to-create-a-notebook-design-with-css/ and its result: http://jsfiddle.net/chriscoyier/KVjFQ/1/ but this solution might easily affect the actual background if it won't be fitted properly after the last line, so don't forget to handle it.

**Comment by kkrawczyk123** [comment]
@oskarhinc, I like this feature very much. Confirmed that my work steps fit into the lines on the page.

**Comment by kkrawczyk123** [comment]
Confirmed that the current solution looks much better than the previous one.
