### ISSUE TITLE
Step with cleanup should be considered as one step

### ISSUE THREAD

**Issue by pawelcieszko** [benetech/MathShare#192]
Currently, the cleanup/calculate steps are considered separately as the real steps (despite the fact they are displayed as we expect). It should be changed - cleanup/calculation steps should be considered as one step. It will eliminate problems with their edition/deletion.  The cleanup/calculate should not increment an additional step since this would be part of a "set" of work applied by the student.

Cases:
1. If a user edits step 2 of 5, but adds a calculation in that step - the steps will not need renumbering because the calculate doesn't increment the count.

2. If a user edits a previous step that already had a calculate/cleanup associated with it, the original cleanup row should be removed, and re-added if needed after the user saves their edits (if they still have a calculate for instance).

Acceptance criteria:

- [ ] Calculation/cleanup steps are not treated separately
- [ ] Edit/delete steps works properly for single steps (without calculations/cleanups) and for combined ones (with calculations/cleanups)

**Comment by johnhbenetech** [comment]
Part 1 replaces  #391

**Comment by afijal** [comment]
Together with @oskarhinc  we've decided that we would like to change the scope of this task and NOT merge those two steps into one, but instead add a flag that would indicate that step is a cleanup one. We believe that it will require less work and have the same output

**Comment by oskarhinc** [comment]
In fact, after rethinking it, we'll leave the scope as it is. The solution with merging steps into one might cause fewer troubles if we would like to expand it.

**Comment by kkrawczyk123** [comment]
Confirmed that issue has been fixed.
