### ISSUE TITLE
Red lines appearing on top of palette box

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#214]
After recent development red lines now appear on top of palette

![image](https://user-images.githubusercontent.com/12927553/42170994-fb22f436-7dcc-11e8-8616-0d1156b23392.png)

**Comment by pawelcieszko** [comment]
After the changes, it works as expected:
![image](https://user-images.githubusercontent.com/29859787/42225801-aae32cd6-7edd-11e8-9461-1699604b47f1.png)

![image](https://user-images.githubusercontent.com/29859787/42225741-8da8d184-7edd-11e8-8a84-a4944ce158d0.png)

![image](https://user-images.githubusercontent.com/29859787/42225782-a0bbe2b6-7edd-11e8-919b-a2b026858e9f.png)

**Comment by kkrawczyk123** [comment]
I confirm that on Chrome and Firefox the issue doesn't occur, but it is still visible on Safari browser.
Screenshot attached:
![screenshot from 2018-07-04 14-28-24](https://user-images.githubusercontent.com/33342488/42277267-1790d0ae-7f97-11e8-80f7-f161719633a5.png)

**Comment by kkrawczyk123** [comment]
I confirm that the issue has been fixed on the development branch.
