### ISSUE TITLE
Top of my work box should be static when opening sketchpad

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#215]
I think the top position of the 'My Work' section should be statically defined to always allow for 'My steps to be shown'

Currently, when a user clicks on the sketchpad button, the sketchpad expands and causes the 'My Work' box to move up and cover the My Steps section on smaller screens.

https://youtu.be/LtqMEo8XA64

I think we should ensure some space is always preserved for the My Work section, even if this means the user needs to scroll down to use the sketchpad

**Comment by kkrawczyk123** [comment]
The top of the My Work area is static after opening sketchpad and it doesn't overlap My Steps section anymore.
