### ISSUE TITLE
Prevent wrapping rows of steps history to the next row.

### ISSUE THREAD

**Issue by dserkowski** [benetech/MathShare#216]
I have found an issue with the responsiveness of the step history.

Before decreasing the size of a browser window it looks like this:
![screenshot from 2018-07-02 16-43-55](https://user-images.githubusercontent.com/29867015/42206780-68fbed2e-7ea8-11e8-9b23-e1c4d8790305.png)

But after that:
![screenshot from 2018-07-02 16-44-26](https://user-images.githubusercontent.com/29867015/42206785-6b9d0748-7ea8-11e8-8f28-eb20f49eb8d8.png)

### Acceptance criteria:

- [ ] rows should not be wrapped to the next line

**Comment by kkrawczyk123** [comment]
Confirmed that buttons are in single line and edition works, I suggested small improvements in https://github.com/benetech/MathShare/issues/435.
