### ISSUE TITLE
Content of "cleanup" steps disappear after edition.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#235]
Reproduction steps:
1. Open one of the problems and add some steps - cleanup steps should appear.
2. Click on the edit button next to one of the cleanup steps.
3. No matter if edit it or not click on Update step button.

The step should be updated but except that content of it disappears and (cleanup) is displayed instead, screenshot attached:
![screenshot from 2018-07-04 16-00-05](https://user-images.githubusercontent.com/33342488/42281532-153404ae-7fa4-11e8-9e99-a482ccc89ab9.png)

**Comment by johnhbenetech** [comment]
I think we should just not display the edit/delete buttons on the 'cleanup' automatic steps. 

If the user edits the parent step with the calculation, the cleanup step should be deleted and then recomputed to reflect the changes.

**Comment by johnhbenetech** [comment]
I think we should just not display the edit/delete buttons on the 'cleanup' automatic steps. 

If the user edits the parent step with the calculation, the cleanup step should be deleted and then recomputed to reflect the changes.

This is reflected in #192, so im gonna close this for now
