### ISSUE TITLE
Transition sketchpad to React component

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#236]
Transition sketchpad to React component

**Comment by oskarhinc** [comment]
@afijal after pressing a sketchpad button, the whole page becomes sketchpad editor.

**Comment by afijal** [comment]
@oskarhinc  I've created #292 and decided to put fixing painterro size on hold untilwe are sure that we can fix other issues

**Comment by kkrawczyk123** [comment]
I confirm that the sketch pad works in the same way as on qa instance. I have noticed one issue connected with safari browser as it also occurs on qa instance I have reported it as a separate issue: https://github.com/benetech/MathShare/issues/310
