### ISSUE TITLE
"Any work on this problem will NOT be saved" should be displayed only when user add some work to an exercise.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#237]
Reproduction steps:
1. Open one of problems (1,2,3,4,6 or 7)
2. Click on Discard button 
"Any work on this problem will NOT be saved" dialog message appears
3. Open problem number 5
4. Click on Discard button
Dialog message doesn't appear.

The warning should be displayed only when user add some work to an exercise not if he chooses Discard button just to go back to the homepage.

**Comment by johnhbenetech** [comment]
This may become irrelevant once dismiss button is removed

**Comment by oskarhinc** [comment]
But there will still be 'back button', so I guess it should warn the user anyway

**Comment by kkrawczyk123** [comment]
I agree that it is a bit outdated issue as alert connected to back button will be added in https://github.com/benetech/MathShare/issues/180 and probably @afijal has already started to work on that.

**Comment by afijal** [comment]
Yeah we already have #180 and #399

**Comment by afijal** [comment]
@johnhbenetech I believe we can close this now
