### ISSUE TITLE
Help panel improvement. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#239]
The step 3 of help panel should concern Discard button, now it is visible in the top left corner, screenshot attached:
![screenshot from 2018-07-04 16-41-48](https://user-images.githubusercontent.com/33342488/42283409-a14b080c-7fa9-11e8-97f7-60b98b648348.png)

The step 4 of help panel is aligned to left and the number of the step is not visible, screenshot attached:
![screenshot from 2018-07-04 16-46-04](https://user-images.githubusercontent.com/33342488/42283470-dc066ca2-7fa9-11e8-8896-1b06526cb896.png)

**Comment by oskarhinc** [comment]
I think it can be made as a part of https://github.com/benetech/MathShare/issues/336
