### ISSUE TITLE
Split to homepage and problem page using react

### ISSUE THREAD

**Issue by afijal** [benetech/MathShare#251]
This will be needed to be done anyway, so split our page to homepage and problem page.

**Comment by oskarhinc** [comment]
@afijal page refreshing is not handled yet.

**Comment by afijal** [comment]
@oskarhinc This is more complex and we will be able to solve it when we will have backend ready I guess:
https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writting-manually

**Comment by oskarhinc** [comment]
@afijal OK, so create a task for it, and we can deal with it later

**Comment by kkrawczyk123** [comment]
Issues described in a comment to https://github.com/benetech/MathShare/issues/264 can be connected to splitting action.

**Comment by afijal** [comment]
@kkrawczyk123 please see the comment in #264

**Comment by kkrawczyk123** [comment]
Homepage and problem page are separate pages. The issue mentioned above will be handled in https://github.com/benetech/MathShare/issues/292.
