### ISSUE TITLE
Transition MyWork to React Component

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#252]
Transition MyWork to React Component. It should contain previously made component - palette buttons.

**Comment by kkrawczyk123** [comment]
The red margin overlaps My work area and this behavior is the same on all 4 browsers, screenshot attached:
![screenshot from 2018-07-10 12-40-42](https://user-images.githubusercontent.com/33342488/42505371-d927b7a4-843e-11e8-830a-95e823cb4ba6.png)

Screenshot of expected result from qa instance:
![screenshot from 2018-07-10 12-41-42](https://user-images.githubusercontent.com/33342488/42505463-1345d114-843f-11e8-8f77-2945a376989f.png)

I have also noticed that Add step button is green but on qa instance it is blue so the colors should be unified. 
![screenshot from 2018-07-10 12-47-04](https://user-images.githubusercontent.com/33342488/42505571-65ffbbf4-843f-11e8-8e6d-6e57c55c758f.png)
![screenshot from 2018-07-10 12-47-14](https://user-images.githubusercontent.com/33342488/42505578-69f6b76c-843f-11e8-85cd-bfa5a421af69.png)

**Comment by oskarhinc** [comment]
@kkrawczyk123 it should work properly now
