### ISSUE TITLE
Transit problem page to React component

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#254]
There should be one component for whole problem page, containing all other components. Additionally, as a part of this task, there should be created a component for buttons stored in Problem component, to simplify the usage of buttons CSS styles. Notice that it should be available also in Homepage component.

**Comment by kkrawczyk123** [comment]
I confirm that the problem page on Chrome, Edge, Safari and Firefox is compliant with the problem page from qa instance.
