### ISSUE TITLE
Make data loaded in react components dynamic

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#256]
Make use of React states - all data should be loaded dynamically: -steps history
-problems set
-problems in each problem set
-palette buttons

**Comment by oskarhinc** [comment]
Loading problems set dynamically is not currently visible, due to lack of using bootstrap components (dropdown 'Problem sets' it this case). I've moved this requirement to the https://github.com/benetech/MathShare/issues/276.

**Comment by kkrawczyk123** [comment]
Buttons undo Add Step and Display/hide sketch pad are distributed too tight, screenshot attached:
![screenshot from 2018-07-16 15-23-49](https://user-images.githubusercontent.com/33342488/42761130-f64e5e32-890c-11e8-916d-9bad6bb8a39a.png)

In My work field, there should be problem to solve but there is an empty space and I am unable to input text there on chrome, firefox and safari, surprisingly I am able to input text on edge, screenshot attached:
![screenshot from 2018-07-16 15-23-58](https://user-images.githubusercontent.com/33342488/42761241-3c1a471e-890d-11e8-83ea-7fd3dfed96ef.png)

A comment text field goes beyond my work frame on firefox and edge browsers, screenshot attached:
![screenshot from 2018-07-16 15-21-19](https://user-images.githubusercontent.com/33342488/42761403-b65fe59c-890d-11e8-8f07-796390a3dcb4.png)

**Comment by kkrawczyk123** [comment]
There is no line which divides work area and comment area, screenshot from qa instance:
![screenshot from 2018-07-17 10-08-25](https://user-images.githubusercontent.com/33342488/42804870-887d2a0c-89aa-11e8-909d-dfe003e66eb9.png)

There is no focus on comment field after clicking on it on firefox and edge, screenshot form chrome attached:
![screenshot from 2018-07-17 10-09-01](https://user-images.githubusercontent.com/33342488/42804932-acb962dc-89aa-11e8-879f-4f97ee49c27b.png)

**Comment by oskarhinc** [comment]
@kkrawczyk123 I've fixed issue you've pointed out. My work field will be filled as a part of https://github.com/benetech/MathShare/issues/272, so it might not be visible yet.

**Comment by kkrawczyk123** [comment]
I confirm that issues have been fixed. The issue connected with the content of My Work field will be verified in https://github.com/benetech/MathShare/issues/272.
