### ISSUE TITLE
Align the bottom buttons with math buttons

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#259]
Align the buttons 'Discard', 'Done' and 'Clear all' with the math buttons in one row, so that we can gain additional space and show at least one additional row of the problem solution.

**Comment by kkrawczyk123** [comment]
Verified on the development branch. I confirm that Discard, Done and Clear all buttons are at the same level as math buttons, and additional space has been removed. The result is compliant on all 4 browsers.

**Comment by kkrawczyk123** [comment]
@dserkowski, as mentioned above by @oskarhinc those changes are still not visible on branch 207.

**Comment by dserkowski** [comment]
Ok. Now it is available on 207 branch

**Comment by kkrawczyk123** [comment]
Confirmed on all 4 browsers.
