### ISSUE TITLE
Add state to React history component

### ISSUE THREAD

**Issue by afijal** [benetech/MathShare#272]
Also add connected metods like 'add step'

**Comment by kkrawczyk123** [comment]
@afijal I am able to input text to my work, comments and add steps but the content of the comment fields is not cleared after adding each step. Also when adding steps notebook background is cut - issue occurs on all browsers. Screenshot attached. 
![screenshot from 2018-07-19 14-05-27](https://user-images.githubusercontent.com/33342488/42941555-693e6458-8b5d-11e8-8e6f-34ff48577eb8.png)

**Comment by kkrawczyk123** [comment]
Adding step works correctly, comments are cleared between steps and it is not possible to add a step without input comment - the warning is displayed. As a background issue is a lower priority I reported it with other minor ui issues in https://github.com/benetech/MathShare/issues/329
