### ISSUE TITLE
Allow using bootstrap components in React

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#276]
Allow using bootstrap components in React. Dropdowns are one of them so if 'Problem sets' dropdown will work properly, it should not be problematic to use any different one of them in the future. While adding logic to 'Problem Sets' dropdown, make sure the problems displayed on the main page are dynamically shifted.

**Comment by kkrawczyk123** [comment]
Problem Sets are displayed correctly on the homepage but when I choose each problem to open from Set 2 or 3 I can still see that problems from the first page are displayed.

**Comment by kkrawczyk123** [comment]
The problems are displayed correctly right now except problem nr 8 on Set 2 and 3 empty page appears and problem/undefined is displayed in url. 
Shouldn't Set 2 and 3 be displayed as subpages so user will be able to go back to each set when he chooses to go back to homepage - currently when click on show previous page set 1 is always displayed?

**Comment by kkrawczyk123** [comment]
I confirm that issues have been already fixed.
