### ISSUE TITLE
Transition keyboard shortcuts usage to React

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#277]
Transition keyboard shortcuts usage to React. If there will be any doubts about the behavior of specific shortcuts, see discussion https://github.com/benetech/MathShare/issues/162 for clearance. There were described current problems with keyboards and assumptions made to resolve them.

**Comment by kkrawczyk123** [comment]
Shortcuts are active after react transition I have noticed only the same bugs that have been already reported in https://github.com/benetech/MathShare/issues/285. After fixing them they will be tested also in #285.
