### ISSUE TITLE
Transition Google Analytics to React

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#279]
There is a lot of 'GoogleAnalytics' usages method in the code. The code responsible for using GA should not be duplicated, so find the best way to use it in all those components.

**Comment by oskarhinc** [comment]
@johnhbenetech regarding to our meeting - should we focus on this task and continue using GA for statistic purposes, or just remove all GA calls from our code?

**Comment by oskarhinc** [comment]
@johnhbenetech OK, thanks.

**Comment by oskarhinc** [comment]
@johnhbenetech I've transitioned GA to React, but we have no access to that Analytics. I've verified it by attaching the local server to my GA Account ID, but could you confirm that it's working also for you? I think the best time to verify it is when React will be deployed for the QA instance.

**Comment by johnhbenetech** [comment]
@oskarhinc I updated the analytics javascript to direct it to a clean analytics bucket on benetech's side. I can confirm it works.

Make sure to merge the conflicts when pushing to development branch.

**Comment by oskarhinc** [comment]
Thanks @johnhbenetech. It was merged today, and we made sure that the access ID is correct.
