### ISSUE TITLE
Handle usage of 'new editor' page in React

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#280]
As there is a possibility to open the editor without a problem - 'try your own problem', we should handle it properly. For now, it should just display empty editor page (see screenshot) without any errors in a console.
![try-your-own-problem](https://user-images.githubusercontent.com/19305104/42753210-74b0e7b2-88f0-11e8-8bf1-0ff4f8b97c91.png)

**Comment by kkrawczyk123** [comment]
I am able to open problem nr 8 after react transition it looks exactly like on qa instance - according to the current approach.
