### ISSUE TITLE
Copy/paste of selected area doesn't work on Safari browser.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#310]
Reproduction steps:
Open sketch pad on safari browser
Choose Select area button 
Select some area and use copy keyboard shortcut and then paste keyboard shortcut.

Expected result:
The user should be able to copy and paste selected area on safari browser as he is able to do it on other browsers.

**Comment by afijal** [comment]
I've checked it and it seems like issue no longer exists

**Comment by oskarhinc** [comment]
I confirm it's working well.
