### ISSUE TITLE
Set up the Dockerfile for Backend

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#315]
Set up a Dockerfile for the Backend application

**Acceptance Criteria:**
* The container should run the boot application and log its output.
* The yml and logging configuration should be possible to using environment vars 
* A docker compose should be added - this compose should spin the app alongside a PostgreSQL container instance

**Comment by pawelcieszko** [comment]
Please update the wiki page (Configuration variables)

**Comment by pawelcieszko** [comment]
Add maintainer information to dockerfile

**Comment by pgesek** [comment]
I had to fix a path issues, but this now works as intented
