### ISSUE TITLE
Start a Wiki with configuration variables for the Backend

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#318]
Start a Wiki page that describes  the configuration variables for the backend. The variables should be presented in a table: name, description, default value. The wiki page should also explain how to change these variables.

**Comment by oskarhinc** [comment]
@pawelcieszko I think it would be nice if we'd describe the logging.level variable itself. We can mention that adding a class (with package name) will apply those level to the specific class, but adding a description for every class in the future is pointless. What do you think? Additionally, could we divide this table in some kind of categories?

**Comment by pawelcieszko** [comment]
@oskarhinc Good point, I will extend a description of logging level. So far, there are not many variables and we are not forced to divide them into categories. In the future if the count of variables increased we may consider separating them.

**Comment by oskarhinc** [comment]
@pawelcieszko it looks fine now.
