### ISSUE TITLE
Add static code analysis tools

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#319]
**Acceptance Criteria:**
* Add Checkstyle
* Add PMD
* Add Findbugs
* Use latest versions, use the guidelines from https://github.com/SolDevelo/static-code-analysis-rules as much as possible (and contribute back if they are outdated, please)

**Comment by oskarhinc** [comment]
FindBugs is no longer supported for Java 10, so I used it's successor https://spotbugs.github.io/.
