### ISSUE TITLE
Url generator

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#321]
A class should be added responsible for generating the codes for URLs. Generally speaking only this code should be stored in the database and data should be retrieved based on it.

**Comment by oskarhinc** [comment]
@johnhbenetech the approach we've chosen with generating URLs - converting a pseudo-random long number with base32 encoding might result in generating multiple codes with duplicated "A" or "7" characters - according to Data Encoding Specification http://www.ietf.org/rfc/rfc4648.txt. For example "AAAAAABAKTWFG" or "P777777777776". From my point of view, it's something we would like to avoid. However, there are still some characters that are not used in the encoding algorithm - "0", "1", "8" and "9" Would you like us to convert the codes with duplicated characters in a more user-friendly form, with not-used characters? For example, we could wrap "P777777777776" as a "P0B6" (11x7 was replaced with special character "0" and hexadecimal B), or "AAAAAABAKTWFG" with "16BAKTWFG".

**Comment by johnhbenetech** [comment]
@oskarhinc lets leave it as is for now. I think we will need to revisit this eventually after we do several pilots.

At that point if we move to an account based system this will be irrelevant. There are also a few non-account options we can explore like using word hashes (what3words).
