### ISSUE TITLE
Endpoint for retrieving problem sets - edit url

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#322]
This endpoint will allow a teacher to retrieve a problem set for editing.

Acceptance Criteria:

* Should be a REST endpoint that calls the ProblemService which should interact with the repositories
* This should always retrieve the latest version of the problem set for editing
* The service should retrieve the problem sets in a form presentable as the rest response
* Should retrieve the problem set based on the url path param
* The endpoint should return 200 response alongside the problem set as body
* Rest MVC test should be added for this endpoint

**Comment by dserkowski** [comment]
Before this, I need to add the mapstruct addon

**Comment by oskarhinc** [comment]
It's working as expected.
