### ISSUE TITLE
Solutions - backend and versioning

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#324]
Add methods and classes for dealing with versioning of solutions.

Acceptance Criteria:

* It should be possible to retrieve solution either in a specific version (share url) or the latest for editing (edit url)
* It should be possible to save a new version of the problem set preserving the old version
* Replaced by should properly populate
* See the database schema for more information

**Comment by oskarhinc** [comment]
There was a small, single issue I've reported to #323, and it will be fixed there. The rest of the logic works as expected so I'm closing the issue.
