### ISSUE TITLE
Endpoint for retrieving solutions - read url

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#325]
This should should allow reading solutions.

Acceptance Criteria:

* Should be a REST endpoint that calls the SolutionService which should interact with the repositories
* Versioning implications should be handled - the code from the url will point to a specific version, not the latest version of the solution
* The service should return the solutions in a form presentable as the rest response
* Should retrieve the solution based on the url path param
* The endpoint should return 200 response alongside the soution as body 
* Rest MVC test should be added for this endpoint

**Comment by oskarhinc** [comment]
It works as expected.
