### ISSUE TITLE
Endpoint for retrieving solutions - edit url 

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#326]
This endpoint will allow a teacher to retrieve a problem set for editing.

Acceptance Criteria:

* Should be a REST endpoint that calls the SolutionService which should interact with the repositories
* This should always retrieve the latest version of the solution for editing
* The service should retrieve the solutions in a form presentable as the rest response
* Should retrieve the solution based on the url path param
* The endpoint should return 200 response alongside the solution as body
* Rest MVC test should be added for this endpoint

**Comment by oskarhinc** [comment]
It's working as expected.
