### ISSUE TITLE
Put problem set endpoint

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#330]
This is the endpoint that will be used to update problem sets. The put endpoint should allow updates as well as creation of new problem sets.

Acceptance Criteria:

* This should be a new put endpoint
* The put endpoint should allow creation and update of problem sets
* The endpoint should return the latest version of the problem set after the update
* Note that updates should not allow updates of readonly properties such as the code for the url
* it should return 201 created as the response code, for updates 200 ok
* Rest MVC test should be added for this endpoint

**Comment by oskarhinc** [comment]
It looks fine, but it was only tested on mocked data. It'll be fully tested when there will be a possibility to update/create the problem set from the UI.
