### ISSUE TITLE
Solution put endpoint

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#331]
This will the endpoint used to edit the solutions. The put endpoint should allow updates as well as creation of new problem sets.

Acceptance Criteria:

* This should be a new put endpoint
* The put endpoint should allow creation and update of solutions
* The endpoint should return the latest version of the solution after the update
* Note that updates should not allow updates of readonly properties such as the code for the url
* it should return 201 created as the response code, for updates 200 ok
* Rest MVC test should be added for this endpoint

**Comment by oskarhinc** [comment]
It works as expected now
