### ISSUE TITLE
Find best option for "guided tour" help tips. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#336]
Help panel is not active after react transition.

**Comment by afijal** [comment]
@johnhbenetech 
Issue is partially fixed. Introduction works, but seems like it doesn't show tooltips associated with buttons. I've tried to fix it and although eveything looks fine, I couldn't get it to work for now, especially as you've mentioned that I shouldn't spend too much time on it. So I decided that a partial fix will be better for now than no introduction at all.

**Comment by kkrawczyk123** [comment]
Help panel isn't identical as on qa instance - it consists of 3 steps not 5, but as @afijal mentioned it is a temporary solution.

**Comment by oskarhinc** [comment]
This issue requires that all steps are displayed properly, so https://github.com/benetech/MathShare/issues/239 should be done as a part of this issue.
