### ISSUE TITLE
Improve the look of the confirmation dialogs

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#338]
The look of confirmation dialogs needs to be improved. Using some react library is highly recommended. Accessibility needs to be preserved. The screenshot shows current dialog:
![old-confirm-dialog](https://user-images.githubusercontent.com/19305104/43303745-7df2bb5a-9171-11e8-972f-42f983c052e5.png)

**Comment by afijal** [comment]
@oskarhinc  I guess we can close this now as we have confirmation modal, ri
ght?

**Comment by oskarhinc** [comment]
Sure, it's outdated.
