### ISSUE TITLE
Undo last action/Clear all issues on Edge browser

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#341]
Reproduction steps:
1. Go to edge browser
2. Open problem, add some steps
3. Delete the last added step
4. Click on Undo last action button

App freezes and a blank page is displayed, there is an error in console, screenshot attached:
![error_edge](https://user-images.githubusercontent.com/33342488/43313734-3bd6be22-9191-11e8-9781-c9763d659a10.png)

- The same situation occurs when Click on Clear All button. 
It might have been connected to scroll fixes which are not visible on the edge browser - after adding a few steps, the scroll appears but the page is not scrolled - my work area is cut.

**Comment by kkrawczyk123** [comment]
There is visible another issue connected only with Edge browser.
Reproduction steps:
1. open one of the problems 
2. No matter if you add some steps or not - click on Done button. 
On homepage there is displayed:
![screenshot from 2018-07-30 14-12-24](https://user-images.githubusercontent.com/33342488/43396862-464010e2-9403-11e8-99b0-727c95143f8b.png)

Problem occurs on all Problem Sets.

**Comment by oskarhinc** [comment]
I've fixed this issue when I was working on the issue with a blank page on the Microsoft Edge. scrollTo method is not supported on Microsoft Edge yet. @afijal please verify if it's working for you as well.
