### ISSUE TITLE
Improvement of display degrees and pi number on the homepage.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#346]
On the Problem Set 2, there are problems connected with geometry - degrees and pi number are not displayed correctly. This issue occurs on qa instance also so it wasn't fixed before. It is no a high priority issue right now but it would be good to eventually fix it. 
Screenshot attached:
![screenshot from 2018-07-30 14-19-14](https://user-images.githubusercontent.com/33342488/43397233-644af7cc-9404-11e8-9a0a-f4c72209e2ed.png)

**Comment by oskarhinc** [comment]
I've added the possibility to insert math equations to the problem title. It can be done by simply adding "$$" before and after the mathlive piece, see screenshot:

![screenshot from 2018-08-31 11-38-48](https://user-images.githubusercontent.com/19305104/44906182-7fcea380-ad14-11e8-93fc-71b64b029aed.png)

And here's the result:
![screenshot from 2018-08-31 11-39-25](https://user-images.githubusercontent.com/19305104/44906195-88bf7500-ad14-11e8-822c-75f9d45aff43.png)

**Comment by kkrawczyk123** [comment]
@oskarhinc, I know that the issue concerns a homepage only and the display of those symbols is fixed there, but it would be good not to display $$ on add problems page and on problem page header too, screenshots attached:
![screenshot from 2018-09-04 09-55-19](https://user-images.githubusercontent.com/33342488/45018792-165bd700-b02b-11e8-9f19-cf1f2f87c2ac.png)
![screenshot from 2018-09-04 09-52-26](https://user-images.githubusercontent.com/33342488/45018793-165bd700-b02b-11e8-8f2f-709a09f427cc.png)

**Comment by kkrawczyk123** [comment]
@oskarhinc issue is still visible when I am using both items in one title on add problem page which is not a very impossible case. Screenshot attached:
![screenshot from 2018-09-06 14-56-48](https://user-images.githubusercontent.com/33342488/45159252-91b5b800-b1e6-11e8-81bc-ac4945f3f82e.png)
Separately they look fine.

**Comment by kkrawczyk123** [comment]
Confirmed that issue has been fixed.
