### ISSUE TITLE
First image upload is failing on Edge browser. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#353]
Reproduction steps:
1. Open mathShare app on the Edge browser.
2. Open one of the problems from the homepage. 
3. Click on Display/Hide sketch pad button and then Open image button.
Choose in the file manager a picture and click on open button.
The picture is not added.
Try another time with the same image - it's still not added.
Try to add a different picture - it is added.

**Comment by oskarhinc** [comment]
This is a bug in the painterro library, but I'm not sure why it's happening, so I'll try to add a custom button to handle this functionality.

**Comment by afijal** [comment]
@oskarhinc For me issue still exists

**Comment by oskarhinc** [comment]
@afijal does the issue still exists or it's working properly for you now?
