### ISSUE TITLE
Improve the layout of MyWork footer buttons

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#365]
The layout of those buttons doesn't look very well (see screenshot). Especially when the "undo" button appears. Provide a new proposition and implement if after it'll be accepted. The 'Done' button should probably not be here at all - it might be converted to "save" and moved to the header.

![screenshot from 2018-08-14 08-21-03](https://user-images.githubusercontent.com/19305104/44075159-e734ca08-9f9b-11e8-864d-1040eb31be98.png)

**Comment by oskarhinc** [comment]
Here's my proposition: 

![screenshot from 2018-08-24 13-55-27](https://user-images.githubusercontent.com/19305104/44583434-95d4e500-a7a5-11e8-9762-c0cb1f476e48.png)

Discard button would be replaced by the back arrow in the upper-left corner. Done button would be replaced by the save button in the page header. And the scratchpad button would be converted to a toggle-type button and moved left, to the palettes area. It could stay in this area, maybe in a separate line so there would be more space, but I'm not sure if it looks well:

![screenshot from 2018-08-24 14-08-53](https://user-images.githubusercontent.com/19305104/44583889-6fb04480-a7a7-11e8-8346-290cae0cbd52.png)

@johnhbenetech please tell me what you think about this layout?

**Comment by johnhbenetech** [comment]
@oskarhinc 

What do you think of this? Clicking the tabs on the right would switch between modes

Symbol selected:
![image](https://user-images.githubusercontent.com/12927553/44684612-5bb25000-a9fe-11e8-8362-cd2184f533da.png)

Sketch selected:
![image](https://user-images.githubusercontent.com/12927553/44685160-a2ed1080-a9ff-11e8-97f4-3af3afa04569.png)

**Comment by oskarhinc** [comment]
@johnhbenetech the sketchpad indeed looks much better, but I'm not sure if there should be an empty space at the top of the right space. Maybe we should move the 'Clear all' button upwards, with 'undo' button as well, and leave 'Add step' at the bottom? 

I guess I should change the colors of the buttons as well, but I would like to confirm it.

**Comment by johnhbenetech** [comment]
I think we can leave the empty space for now. I think it might be useful later on.

I'm still not 100% on where clear all should go. Since it affects the entire problem set (and not just one step) I feel like it should be in the page header (with the other whole set actions).

The header is getting pretty crowded though, any thoughts?

**Comment by afijal** [comment]
Yeah it's getting too crowded. 
The only idea I've came across is to place here
![image](https://user-images.githubusercontent.com/2682379/44734042-45cd8980-aae9-11e8-94d6-57446a569a3e.png)
Something like Reset setps/Clear all button

**Comment by johnhbenetech** [comment]
Good idea. Let's go with that for now.
