### ISSUE TITLE
Resolve issue with displaying the math equation

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#367]
In the editor area, the problem equation is randomly cropped (see screenshot). It happens both in the steps list and in the title. 
![screenshot from 2018-08-14 07-34-14](https://user-images.githubusercontent.com/19305104/44076089-36793916-9f9f-11e8-96f6-1a16fdbe7db5.png)

**Comment by afijal** [comment]
We can either add scroll or expand the header. Scroll looks bad so I've decided to go with the first option.
Example screenshot doesn't look great but it is purposely exaggerated to make the change obvious and it is highly unlikely that such an equation will exist in real life (at least I guess so)
![image](https://user-images.githubusercontent.com/2682379/44593860-df80f800-a7c4-11e8-879a-afebd78f2e0f.png)

**Comment by kkrawczyk123** [comment]
Added elements are not cropped and the header on the problem page expands to problem content.
