### ISSUE TITLE
Add possibility to select specific palettes for the problem set

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#368]
The logic for showing only allowed palettes on the UI is already done, but there is no possibility to specify which palettes are available in each problem sets - so as default, all of them are available in all problems sets. Palettes are filtered at the frontend side, as it's just a facilitation to not showing unneeded palettes. It's filtered to show only palettes with labels that are available in allowedPalettes list, so for example, for allowedPalettes=['xxx', 'yyy'] - palettes with labels 'xxx' and 'yyy' will be shown to the user. 

Acceptance criteria: 
* Add possibility to specify allowed palettes on the UI for each problem set
* Hold information about allowed palettes in the db
* Load only allowed palettes for each problem in the problem set

**Comment by afijal** [comment]
So I Will leave this until we will get a brand new Index Page and an ability to create new Problem Sets.
For now I've created Palette Chooser component for future use, and it look like that:
(discard is actually replaced with cancel)
![image](https://user-images.githubusercontent.com/2682379/44733023-fc7c3a80-aae6-11e8-94d1-20b4deca1cba.png)

**Comment by afijal** [comment]
@johnhbenetech 
So I believe it can be moved to the backlog until we have index page or adding new problem sets ready, right?

**Comment by johnhbenetech** [comment]
yep! ill move it now

**Comment by kkrawczyk123** [comment]
@afijal, I can see some issues connected to choosing palettes for problem set:
- math buttons should be disabled on that view - they are not being used there but clicking on them causes errors in console.
- When choosing random palettes which don't occur one by one on the problem page buttons from different palettes are mixed up, screenshot attached: 
![screenshot from 2018-09-07 12-25-06](https://user-images.githubusercontent.com/33342488/45215475-d4869700-b29d-11e8-977e-2243ffe61aef.png)
![screenshot from 2018-09-07 12-59-33](https://user-images.githubusercontent.com/33342488/45215496-e10aef80-b29d-11e8-8846-ce564233a94f.png)
That can be difficult to reproduce. Proper buttons are restored when switching the view to sketchpad but after refreshing page they are mixed again. Please, investigate.
