### ISSUE TITLE
Allow users to customize problems set

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#369]
When a user reaches the edit link of the problem set - he should be able to customize it - add new problems or remove some of them, and share the result later. All changes should be probably committed to the DB, so the edit link will always reflect the newest version. See #364 for mockups. There is no need to attach logic to creating new problem page, as it'll be done in #370. We should only ensure here that the button is available for solution edit link, and not visible for share link.

**Comment by kkrawczyk123** [comment]
The user is able to add and delete steps then share a link with a view mode, not edit mode. Error handling feature will also concerns problem set url https://github.com/benetech/MathShare/issues/389
