### ISSUE TITLE
Add possibility to attach image/scratchpad data to problem

### ISSUE THREAD

**Issue by afijal** [benetech/MathShare#376]
In case if teacher would like to add some kind of graph or drawing.
Related to #364 and #370 a

**Comment by johnhbenetech** [comment]
as discussed these also need to be stored in the database

**Comment by kkrawczyk123** [comment]
The feature is currently not working, @oskarhinc please investigate.

**Comment by kkrawczyk123** [comment]
Adding and preview picture when creating a problem works fine when adding one picture but there is a bug connected to adding more than one image and pasting it. I consulted it with @oskarhinc and we decided to report it as separate issue https://github.com/benetech/MathShare/issues/414 and fix it there.
