### ISSUE TITLE
Allow for sorting of problems within problem set

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#380]
After a problem set is created, a teacher should have the ability to move the problems around within the set (and have them automatically renumbered).

I imagine we can do this in two ways (probably both):

1. In the 'add problem' dialogue. All existing problems can be shown. The user can add problems to the bottom of the list. Each problem row will have an up-arrow & down-arrow that allows the problem to be resorted. This can likely be made accessible.

2. From the problem set overview screen, after a teacher hits 'edit' the problems become draggable. The teachers can drag the problems around to resort them in the grid (and automatically renumber).

**Comment by kkrawczyk123** [comment]
Confirm that both ways of sorting problems have been implemented and working well.
