### ISSUE TITLE
Generate and display thumbnail of previous steps

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#381]
After a user adds a response step with scratch pad input, that step should appear in the history with a thumbnail of the scratch pad.

**Comment by afijal** [comment]
![image](https://user-images.githubusercontent.com/2682379/45643549-a124e300-babb-11e8-9976-6c7baf232d4e.png)
Image is clickable and opens in a new tab

**Comment by oskarhinc** [comment]
It works well and looks super nice!
