### ISSUE TITLE
Display thumbnail on problemset overview 

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#382]
For problems that have scratch pad input attached, a thumbnail should be displayed on the problemset overview.

**Comment by afijal** [comment]
@johnhbenetech So for now I've used the proposed solution, when there is no problem title but there is problem image, we show it.
![image](https://user-images.githubusercontent.com/2682379/45297599-32b5b300-b506-11e8-9103-1440e8a34d99.png)
On the screenshot problem #7 has both and #8 has only an image. Should I try to squeeze both at once into a Problem Card?

**Comment by kkrawczyk123** [comment]
Confirmed that this new display looks very good. Screenshot attached:
![screenshot from 2018-09-14 14-47-11](https://user-images.githubusercontent.com/33342488/45551267-9ce39600-b82d-11e8-8882-d88d2479208d.png)
