### ISSUE TITLE
Error handling of invalid url addresses.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#389]
Invalid sharing url are not recognized according to both problem and problem sets. The page is loading and it is not stopping when I try to open url with a random id.
Screenshot attached:
![screenshot from 2018-08-27 14-18-18](https://user-images.githubusercontent.com/33342488/44659791-ab484a00-aa05-11e8-9767-819709e9569f.png)

**Comment by afijal** [comment]
@oskarhinc 
Seems like not every case works
![image](https://user-images.githubusercontent.com/2682379/45638361-45ebf400-baad-11e8-864a-136906ffc9fa.png)
Sometimes wrong edit/view code works, is this expected behavior?

**Comment by oskarhinc** [comment]
@afijal Sometimes the change of the URL is not recognized. But if you focus on the URL and press enter once again (or refresh the page) it should look for the new problem/problem-set. Is 404 page loaded then?

**Comment by afijal** [comment]
@oskarhinc Yeah I know, but it occurs even if put it in new incognito window so I guess that's not the case here

**Comment by oskarhinc** [comment]
@afijal Ok, thanks. I'll take a look.

**Comment by afijal** [comment]
@oskarhinc 
Works as desired now
