### ISSUE TITLE
Step numeration issue when there are cleanup steps.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#391]
cleanup steps weren't considered as steps before, old screenshot attached: 
![screenshot from 2018-08-27 15-50-19](https://user-images.githubusercontent.com/33342488/44663465-ebf99080-aa10-11e8-99b6-59df53934794.png)

now cleanup steps are considered as separate steps, and in the numeration of added steps there are missing steps where cleanups are added, here Step 4 and Step 7, screenshot attached:
![screenshot from 2018-08-27 15-48-44](https://user-images.githubusercontent.com/33342488/44663592-4eeb2780-aa11-11e8-95aa-ae22b6f46359.png)

**Comment by johnhbenetech** [comment]
this can be handled in #192. closing for now
