### ISSUE TITLE
Use H2 database for tests

### ISSUE THREAD

**Issue by pgesek** [benetech/MathShare#392]
We should make our test code use a file based database as h2. Thanks to this we will avoid using the database installed on the host when running tests. Currently I need to switch the password in the file before I run the tests, which will not happen if we will use h2 for testing.

**Comment by johnhbenetech** [comment]
Duplicate of #377. This will be the task

**Comment by pawelcieszko** [comment]
It works as expected also on Windows. Dockerized environment behaves as expected - no additional database starrtup is required. I've updated the readme file.
