### ISSUE TITLE
After clicking 'Edit', while in edit mode header text should from 'Edit' to 'Finish Edit'

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#396]
From #388 

This would switch back to the display mode

**Comment by afijal** [comment]
@johnhbenetech So just to confirm, currently edit switches to share. we would like to also add Finish Edit button (only when editing ofc) that would open the view url (which is being displayed in a modal after pressing share)?

**Comment by kkrawczyk123** [comment]
Confirm that Finish Edit button has been added.

**Comment by johnhbenetech** [comment]
I see your point. Let's keep it as is for now and see how testing goes.

**Comment by johnhbenetech** [comment]
Cool, I'll keep an eye on this in testing and see if finish edit is clear
