### ISSUE TITLE
Add scratchpad to each step

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#403]
We need to store scratchpad for each step in the state and save it in the database so it'll be available later. Don't forget to handle the situation where no changes were applied to the scratchpad, so we won't send an empty scratchpad content in base64 to the backend - we should send null in this case. On the other hand, if scratchpad is null for a step - it should display as an empty one.

**Comment by johnhbenetech** [comment]
This is related to #350, so ill close that one in favor of this.

**Comment by kkrawczyk123** [comment]
@oskarhinc, I have noticed a small issue connected to clearing the sketchpad content. Try a case: use sketchpad, change to symbols and when you go back to sketch again the content of the sketchpad is cleared then. 

@johnhbenetech I have a question according to save and clear the sketchpad content. As we have little difference in behavior and we are not sure which one is preferred more. The first one is that when I start to work on the next step and I draw something in a sketchpad and I suddenly choose to edit some of the steps no matter if I cancel edit or update the step sketchpad content is cleared. The second one is when I start to work on the next step and I draw something in a sketchpad and I decide to delete lat added step - the sketchpad content is saved. Which one sounds better for you?

**Comment by johnhbenetech** [comment]
@kkrawczyk123 lets go with the first option

**Comment by kkrawczyk123** [comment]
Confirmed that issues have been fixed.
