### ISSUE TITLE
Canceling adding problem issue. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#416]
Reproduction steps:
1. Open add problem window.
2. Input equation and annotation 
3. Click on add problem button.
4. Click on Cancel.
5. Open Add problem panel again.

We might consider two approaches here, first loosing added not saved problems when clicking on Cancel button or softer one to add the possibility to delete added but not saved problems which are displayed above Add problem to the set window. It would help to avoid the situation that user would have to save a faulty problem (add to problem set) and then be able to delete it. Delete and also Edit icon would look good in the right of the list with added but not yet saved problems. @johnhbenetech what approach sounds better for you?

I can see that the annotation content is saved when canceling the process without adding the step.
to reproduce:
1. Open add problem window.
2. Input equation and annotation 
3. Click on Cancel. 
4. Open Add problem panel again.

**Comment by afijal** [comment]
@oskarhinc  I agree, works well now
