### ISSUE TITLE
Unify a name of Annotation and title.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#417]
When open add problem window there are Equation and Annotation field titles displayed. 
When you try to add problem without input Annotation and click on Add problem button on the dialog message there is "Please provide a problem title" It would be good to unify those names.

**Comment by johnhbenetech** [comment]
Let's go with 'Title' across the board

**Comment by kkrawczyk123** [comment]
Confirmed that names has been unified.
