### ISSUE TITLE
Background flashing issue when delete problems on problem set. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#419]
Problem set is displayed correctly:
![screenshot from 2018-08-30 16-00-23](https://user-images.githubusercontent.com/33342488/44856587-185e1880-ac6e-11e8-88e1-a171a33e6a66.png)

When I click on detele button on the one of problems I see:
![screenshot from 2018-08-30 16-00-35](https://user-images.githubusercontent.com/33342488/44856622-2d3aac00-ac6e-11e8-8990-adc87361aced.png)

When I click Cancel or Yes correctly displayed Problem set page is restored.

**Comment by afijal** [comment]
@kkrawczyk123 If you meant that math expressions weren't rendered properly when there was a modal opened, then this issue has been fixed some time ago and you can close this issue.
Otherwise, please add better explanation.

**Comment by kkrawczyk123** [comment]
yes, @afijal this is exactly what I meant. I confirmed that issue has been fixed, so I am closing that issue.
