### ISSUE TITLE
Shortcut suggesting feature.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#421]
I have noticed that when input shortcuts into my work area some suggesting/helping window is showing up randomly. Screenshots attached:
![screenshot from 2018-08-31 09-44-26](https://user-images.githubusercontent.com/33342488/44899625-910eb480-ad02-11e8-81e9-43691b136697.png)
![screenshot from 2018-08-31 09-44-01](https://user-images.githubusercontent.com/33342488/44899626-91a74b00-ad02-11e8-8971-84088216c7a5.png)
![screenshot from 2018-08-31 09-43-45](https://user-images.githubusercontent.com/33342488/44899627-91a74b00-ad02-11e8-8bc3-af3613006357.png)

I think that suggesting idea is a good one but it will require handling it. @johnhbenetech what are your thoughts?

**Comment by johnhbenetech** [comment]
Yes, we should try to match MathLive as much as possible. so i think we should try to display these correctly

**Comment by afijal** [comment]
Seems like it was a MathLive issue, I've fixed this in our project and created a pr to MathLive repo https://github.com/arnog/mathlive/pull/107.

Behavior isn't ideal when the popup shows and we scroll the page, but this is how it works in the library

**Comment by kkrawczyk123** [comment]
Good job @afijal ! Commands are suggested, user is able to change them using up and down arrows and popover is displayed right below input text, not randomly like before. I agree that it is not perfect when scrolling the page but it is not a very common use case either.
