### ISSUE TITLE
Undo last action clears added comments.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#423]
Reproduction cases 1:
1. Add step
2. Click on undo last action button
3. Click on add step
The step with the blank comment is added it should not be allowed.

Reproduction cases 2:
1. Add step
2. Delete added step
3. Click on Undo last action
The step is added again but with a blank comment.

Reproduction cases 3:
1. Add a few steps
2. Click on Clear All button
3. Click on Undo last action
Steps are restored but without comments.

**Comment by oskarhinc** [comment]
I've moved this issue to 'Next up' as I'll be working on 'undo' action anyway (with #358) and it seems important to fix.

**Comment by kkrawczyk123** [comment]
Confirmed that issue with clearing comments has been fixed.
