### ISSUE TITLE
Another problem is deleted from problem set not intended one. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#428]
Reproduction steps:
1. Open homepage and edit mode
2. Click on delete button next to random problem except the first one in the list.

The first problem from the list is deleted every time not intended one.

**Comment by oskarhinc** [comment]
@kkrawczyk123 Could you verify if the error still occurs? It's working for me, and I think it was already fixed lately.

**Comment by kkrawczyk123** [comment]
Confirmed that issue doesn't occur anymore.
