### ISSUE TITLE
Fix MathShare build & startup issues on Windows

### ISSUE THREAD

**Issue by pawelcieszko** [benetech/MathShare#432]
There is a need to fix MathShare build & startup issues on Windows. 

Reproduction steps

1. Install Docker, Docker-Compose, NPM, Maven on Windows
2. Download the repositories (MathShare & MathShareBackend)
3. Run the MathShareBackend application in Docker Quickstart Terminal (follow Readme - no issues so far)
4. Build and run (via docker-compose)
5. Run _npm install_ . There are warnings – but they are all for optional dependencies:
* fsevents not supported on windows
* npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none was installed.
* npm WARN enzyme-adapter-react-16@1.3.1 requires a peer of enzyme@^3.0.0 but none was installed.

6. Run _npm start_. There are warnings: 
* Compiled with warnings: multiple modules with names that only differ in casing
* @ ./src/components/Index.js
* @ ./src/components/index.js
* @ ./src/index.js
7. The app attempts to load, but it actually completely crashes the browser

**Comment by johnhbenetech** [comment]
this seems to have been resolved.
