### ISSUE TITLE
Improve decreasing browser's window. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#435]
As a continuation of https://github.com/benetech/MathShare/issues/216 it would be good to add a horizontal scroll when decreasing browser's window. 
Add step button and Annotation field don't fit to My Work area when browse window is decreased, screenshot attached:
![screenshot from 2018-09-04 10-21-19](https://user-images.githubusercontent.com/33342488/45021031-cd0e8600-b030-11e8-9c3f-dcaab094eaef.png)

**Comment by johnhbenetech** [comment]
Maybe we can just have a min-width instead of adding more scroll bars? what do we think?

**Comment by afijal** [comment]
I've tried to reproduce it but it seems like the issue no longer occurs

**Comment by kkrawczyk123** [comment]
Confirmed that issue no longer occurs.
