### ISSUE TITLE
Clear All button is present and active on non-editable problem view.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#436]
Reproduction steps:
1. Open problem, add some steps
2. Copy the view link
3. Open view link
Screenshot attached:
![screenshot from 2018-09-04 11-41-20](https://user-images.githubusercontent.com/33342488/45023804-b0298100-b037-11e8-9b8e-414c45df796d.png)

**Comment by afijal** [comment]
@kkrawczyk123 Closing it as it was fixed earlier (double checked)

**Comment by kkrawczyk123** [comment]
Confirmed.
