### ISSUE TITLE
Wrap the title content on the Problem set page

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#452]
Titles are not wrapped on the problem Set page and they don't fit into problem buttons, screenshot attached:
![screenshot from 2018-09-07 09-08-28](https://user-images.githubusercontent.com/33342488/45203969-23bccf80-b27e-11e8-96fa-8ca630e46111.png)

**Comment by afijal** [comment]
@kkrawczyk123  How should we handle it? Break the text or add "..." like in equations

**Comment by johnhbenetech** [comment]
can we try to break the text to the next line(s)?

**Comment by afijal** [comment]
Sure, I wrap it, and when it contains some math, then we add "..." (we haven't found way to wrap mathlive fields)

**Comment by kkrawczyk123** [comment]
Confirmed that issue has been fixed.
