### ISSUE TITLE
Double fraction display on Problem Set page.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#454]
When adding/editing problem with double fraction it is displayed only with part of the equation before that fraction, the part after a double fraction is ignored and it is no displayed at all. 
As an example:
Display from problem set:
![screenshot from 2018-09-07 09-05-39](https://user-images.githubusercontent.com/33342488/45205854-b744cf00-b283-11e8-97dc-bd31b12f7b51.png)
A real display after editing problem:
![screenshot from 2018-09-07 09-06-25](https://user-images.githubusercontent.com/33342488/45205870-c461be00-b283-11e8-85b3-190be3729707.png)
![screenshot from 2018-09-07 09-06-07](https://user-images.githubusercontent.com/33342488/45205871-c4fa5480-b283-11e8-9079-9d3d1fd3a29b.png)

**Comment by afijal** [comment]
@oskarhinc 
I hate being picky and I know that this issue follows us for some time but it still doesn't look good in some situations:
![image](https://user-images.githubusercontent.com/2682379/45636797-002d2c80-baa9-11e8-857c-447dabc009e1.png)
Maybe we should try a different attitude than adding "...", but personally I can't think of anything else than scrollbar which would look awful>
Any ideas @johnhbenetech ?

**Comment by afijal** [comment]
@oskarhinc As you see sometimes text is too long and sometimes it is cut in a wrong place exposing mathlive syntax

**Comment by afijal** [comment]
@oskarhinc Looks a lot better now
