### ISSUE TITLE
MS Edge - blank page

### ISSUE THREAD

**Issue by pawelcieszko** [benetech/MathShare#463]
The main page of MathShare is not loading at all on MS Edge browser. The console errors suggest issues with the html closing markups. Chrome on Windows works properly.

![image](https://user-images.githubusercontent.com/29859787/45298052-9ee4e680-b507-11e8-9597-5852be39620c.png)

![image](https://user-images.githubusercontent.com/29859787/45298071-ac01d580-b507-11e8-9c49-63c2583b842e.png)

**Comment by afijal** [comment]
@oskarhinc Would it be possible to make it so the autoscroll would work on edge as well?

**Comment by oskarhinc** [comment]
@afijal I'll try to find a walkaround.
