### ISSUE TITLE
Sketchpad content disappears when edit problem in problem set. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#489]
Reproduction steps:
1. Add new problem with sketchpad content to the problem set.
2. Click on Edit button of that problem - click on Sketchpad 
The content of sketchpad is empty - but it shouldn't be.
Edit problem (equation or title) and Save it. 
I encountered scenarios where image icon disappeared from problem set and when it didn't - after clicking on image icon - empty page displayed.

**Comment by afijal** [comment]
I confirm that it's fixed
