### ISSUE TITLE
Undo last action issues.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#490]
I have noticed three cases where undo action requires some fixes.

Reproduction steps:
1. Edit one of the added steps.
2. Click on Undo button.
Comment of the last added step is visible in the comment of edited step - it should only reverse edit action.

Reproduction steps:
1. Add some steps
2. Clear all steps
3. Click on Undo button. 
Comment of the last added step is visible in the description field - description field should have its default/initial content.

Reproduction steps:
1. Add some steps
2. Click on Edit button next to one of the added steps
3. Cancel the Edit process.
Comment of this step is displayed now in the description field - description field should have its default/initial content.

**Comment by oskarhinc** [comment]
None of the above issues occur anymore.
