### ISSUE TITLE
Space in My work area issue. 

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#495]
After adding Text button it is possible to add text into my work area. Using the space button seems to be a bit problematic. When input \text{sometext} and press enter button, text is added to my work area, to use space I used ctrl+space button - space is not visible there but when adding another word it is visible and displayed correctly on the problem set (problems 10 and 11). 
When I used ctrl+space double times as I wasn't sure it did work, space was visible but when I saved problems to the problem set it wasn't displayed properly (problem 9 and 12 on the screenshot). 
![screenshot from 2018-09-14 12-29-46](https://user-images.githubusercontent.com/33342488/45545510-c7782380-b81a-11e8-9b5e-36c1c1234f6d.png)

It would be good to investigate using space button or if can be dificult at least improve the display after adding dobule space.

**Comment by afijal** [comment]
This is no logner relevant and was fixed
