### ISSUE TITLE
Square roots are cut off in My work area.

### ISSUE THREAD

**Issue by kkrawczyk123** [benetech/MathShare#497]
Square roots are cut off in My work area. They are displayed correctly in My steps section, screenshot attached:
![screenshot from 2018-09-14 14-27-41](https://user-images.githubusercontent.com/33342488/45550256-a3bcd980-b82a-11e8-9214-211ad9c0648b.png)
It can be confusing for the user as he won't know when square ends.

**Comment by NSoiffer** [comment]
This appears to have been fixed in mathlive. I no longer see it happening.
