### ISSUE TITLE
Issue with share URLs in current deploy

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#505]
In the current version deployed at:
https://mathshare-qa.diagramcenter.org

After either creating a problem set and sharing, or answering a problem set and sharing, you are shown  URL that looks something like:
https://mathshare-api-qa.diagramcenter.org/problem/view/J6CZBZ5WULD4Y

This seems to be pointing to the server and not the frontend. Is there a configuration or config variable needed to make this link creation work?

**Comment by oskarhinc** [comment]
@johnhbenetech there's no config variable for this. I'm glad you've created this issue, as it's indeed important to fix. I guess we should avoid a variable for this, and get the frontend base URL from the app, if it's possible.

**Comment by oskarhinc** [comment]
It's working properly now
