### ISSUE TITLE
Improve footer alignment

### ISSUE THREAD

**Issue by afijal** [benetech/MathShare#507]
Currently it is a little off on wider displays
Test other resolutions and scaling too
![image](https://user-images.githubusercontent.com/2682379/45642288-1393c400-bab8-11e8-9203-3b41a8aa918c.png)

**Comment by oskarhinc** [comment]
@afijal It still looks weird on wider display, maybe we need to add an auto scroll here?

**Comment by oskarhinc** [comment]
I've fixed it. @afijal please verify if it's working for you also on tight display.

**Comment by afijal** [comment]
@oskarhinc yeah, works great
