### ISSUE TITLE
Add aws service for sync highlighting

### ISSUE THREAD

**Issue by NSoiffer** [benetech/MathShare#541]
We have an AWS account that is meant to be used for math speech. It probably could also be used for speech recognition so that the microphone button will work in all browsers (#129).

See the [mathlive documentation](https://github.com/arnog/mathlive/tree/master/examples/speech) for details on what needs to get set up.  In summary we need to add
```
<head>
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.249.1.min.js"></script>
    <script>
        AWS.config.region = 'eu-west-1';
        AWS.config.accessKeyId = 'YOUR-KEY';
        AWS.config.secretAccessKey = 'YOUR-SECRET';
    </script>
</head>
```
but if this goes into the client code, our secret key isn't so secret. At one point, I did some minor encryption of the keys so that was in the file was a weakly encrypted key, but I don't recommend that approach. Hopefully this can be on the server somehow or someone knows how to deal with the AWS keys better.

The other thing to do is to change `local` to `amazon` in `components\Editor\components\MyWork\components\MyWorkEditorArea\index.js` (comment indicates where)

**Comment by johnhbenetech** [comment]
Adding Polly/Cognito example per our email exchange. You can change the extension to .html if you want to test it locally.


[index.txt](https://github.com/benetech/MathShare/files/2862422/index.txt)

**Comment by johnhbenetech** [comment]
also you can/should change TextType from "text" to "ssml" if you want to use the ssml tags here:

https://docs.aws.amazon.com/polly/latest/dg/supported-ssml.html

**Comment by NSoiffer** [comment]
John's solution appears to be good enough, so I'm closing this.
