### ISSUE TITLE
explain difference between share & save

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#545]
As a student, it is confusing what the difference between the share and save button are. 

There should be a short warning on the share & save popups explaining the difference between the two functions.

Share Text: "Use this link to share your finished work. If you want to continue working on it later, use the "Save" button instead. 

Save Text: "Use this link to save your work and return to it later. If you want a link to submit your finished work, use the "Share" button instead." 

Location in popup: 

![share link popup showing filler text added below the URL](https://user-images.githubusercontent.com/47576069/53191731-6a4e7e00-35c1-11e9-9d74-853348ebb8aa.png "Share Popup")

**Comment by johnhbenetech** [comment]
From conversation with Alex:
First 'save' action should result in popup with the save text. Subsequent saves should only display current alert

**Comment by benetechMatt** [comment]
@alexrcabral 
What about "turn in" or "submit".  Those are the words most used in other education programs and "share" can imply using it for purposes besides turning in their assignment.  
Google classroom "turn in"
Canvas: "submit assignment"
Schoology: "submit"

**Comment by benetechMatt** [comment]
should remove "share" at the top bar.  Have added "Finish" button at bottom of problems and leaving "save" button at top.
On the problem set page students have a new option to submit their whole set.
These changes are currently completed on QA.
