### ISSUE TITLE
turn (?) into a help menu

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#548]
have the question mark icon bring up a menu including: 

- "Getting Started" (an expandable menu item containing items  "Tutorial", "Tools & Icons", and "How to Create Problem Sets") 
- "FAQ"
- "Feedback"

Edit: look to bookshare and how it sets up its instructional videos

**Comment by benetechMatt** [comment]
Change ? icon to a drop down with:
Tutorial - current action when users click on the ?
Tools and Icons - new modal with summary of icons (see other task) @alexrcabral 
Help center - https://intercom.help/benetech/en
Feedback - opens current feedback form/modal

![image](https://user-images.githubusercontent.com/49413678/61252208-682cbd80-a722-11e9-96b5-1665c39ac0fa.png)
