### ISSUE TITLE
UX improvement for displaying question/prompt on work page

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#565]
Based on feedback from @rupeshparab 

We should potentially rethink the way the problem prompt is displayed on the main work view.

Currently the problem prompt is displayed in two locations:

* In the header

![image](https://user-images.githubusercontent.com/12927553/56439278-333bd680-62ab-11e9-8cba-0d93eb451aa1.png)

* As 'Step 1' on the student work section:

![image](https://user-images.githubusercontent.com/12927553/56439448-b78e5980-62ab-11e9-8d69-07caa0c116f4.png)

A few reasons why we might want to redesign this approach:

* General cognitive load of so many elements
* The header is extremely crowded at this point
* Large prompts make the header a nightmare, showing this twice exacerbates that

![image](https://user-images.githubusercontent.com/12927553/56439643-7480b600-62ac-11e9-8158-ce13aa771a85.png)

* There's no clear 'first thing to look at visually' that helps guide the student as to where to start

As a temporary hold-over Rupesh has introduced a new button to bring up a scroll-able view of the prompt - but this doesn't address the issues around how to make the 'first focal point' stand out. @alexrcabral would love to get your opinion on this

![image](https://user-images.githubusercontent.com/12927553/56439838-26b87d80-62ad-11e9-9a4a-abce97145f6f.png)

**Comment by johnhbenetech** [comment]
I was thinking something like this:

![image](https://user-images.githubusercontent.com/12927553/56441070-5f5a5600-62b1-11e9-9888-a83c1982e25a.png)


But obviously would love to get @alexrcabral and @benetechMatt on this. I think another big question is how do we handle if a problem has a picture-based prompt. Currently we use a icon to open the image in a new screen:

 
![image](https://user-images.githubusercontent.com/12927553/56441272-2a9ace80-62b2-11e9-9631-d7885260ecb7.png)

**Comment by benetechMatt** [comment]
I like your proposal John. Clearly separates the problem and student's work and the page actions.
I think images should show by default either below or to the side. There could be a "hide" button for the image. Some students may not click on the image to view and other times it may be helpful to see the image while working on the problem
