### ISSUE TITLE
QA: screen reading broken for math entry box (reads out xml tags instead)

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#616]
Problem: As a screen reader user (VoiceOver), trying to read out the content of the math editor box outputs nonsense xml rather than the math itself. AWS commands can be used and speak out the math, but VoiceOver speaks XML over the top whenever form focus is originally given, or when arrow keys are used to navigate through the math equation. 

<img width="649" alt="form focus on math editor with VoiceOver window showing xml tags" src="https://user-images.githubusercontent.com/47576069/58988253-1e9d9a00-8796-11e9-8c34-a63d1262ffb8.png">

The VoiceOver output says “start of math field: ?xml version=1.0? speak version=1.1 xmlns="http://www.w3.org/2001/10/synthesis" prosody rate="100%" mark name="cfiq8y"/ italic 7 
 break time="250ms"/

Solution: Fixing the speech output on Mac so AWS speech commands can be used without being overridden by VoiceOver speaking xml

<img width="646" alt="form focus on math editor, with VoiceOver window outputting the correct math 7x minus 13=1" src="https://user-images.githubusercontent.com/47576069/58988038-a46d1580-8795-11e9-860d-4166b6b66bab.png">

**Comment by johnhbenetech** [comment]
@alexrcabral Re: @NSoiffer email, can you clarify how you would like it to work and how it would be used in coordination with the synchronized highlighting?

**Comment by alexrcabral** [comment]
@johnhbenetech thanks for the ask, apparently Outlook was still sending the emails to a junk folder but that should be fixed now 

I was thinking the standard screen reader would be used for navigation of the site, with extra commands (eg AWS speech commands, and options for things like synchronized highlighting) would be available when in the main editor box 

Just sent a clarifying email as well
