### ISSUE TITLE
Allow teachers to copy problems sets made by others/example pre-made problem set

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#712]
Aha! Link: https://diagramlabs.aha.io/features/B-156

**Comment by benetechMatt** [comment]
Add a "copy" button next to the title of the problem set.
The options icon has the same abilities (duplicate, share)
![image](https://user-images.githubusercontent.com/49413678/62161448-cee1d780-b2db-11e9-9b92-331dbe8ea00b.png)

**Comment by benetechMatt** [comment]
Edit and delete icons are not available on sets that you do not "own"

**Comment by alexrcabral** [comment]
Why a copy button? Would it be better to have it under the options already to the right of the problem set name?

**Comment by benetechMatt** [comment]
There needs to be a dedicated way to determine if the set being viewed is meant to be for other teachers to see and then copy if they choose.  This could be through a URL scheme /share/
When viewing that the teacher cannot edit or assign the set until they copy it.

@alexrcabral the copy button should be obvious and more actionable to encourage users to click it

Assign and editing functions should be grayed out because the viewer must copy the set first.

**Comment by alexrcabral** [comment]
Ah ok, that makes sense. In that case it could be good to move the copy button closer to assign so the greyed out assign/edit buttons are associated with the copy button, since it has to be copied first

**Comment by benetechMatt** [comment]
addressed by #1025
