### ISSUE TITLE
Bring back Edready alpha problem sets

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#737]
Ahrash reported that Lauren's problem sets from the alpha don't work anymore.  They would like access to those again.  The links are broken

Aha! Link: https://diagramlabs.aha.io/features/B-137

**Comment by benetechMatt** [comment]
@johnhbenetech here are three URLs that I have received so far.  Can they be retrieved and made accessible in the new Mathshare?
https://mathshare-staging.diagramcenter.org/#/problemSet/view/TIYT4URT4H5FK
https://mathshare-staging.diagramcenter.org/#/problem/view/FNODZJ5TBGD3C
https://mathshare-staging.diagramcenter.org/#/problem/view/IEL2NBIBRL2KM

**Comment by johnhbenetech** [comment]
@benetechMatt If you think you can get the actual content (like what the problems were) that would be easiest. I'll dig around in the database and see what I can find

**Comment by benetechMatt** [comment]
Full list of problem sets

- https://mathshare-staging.diagramcenter.org/#/problemSet/view/TIYT4URT4H5FK
- https://mathshare-staging.diagramcenter.org/#/problem/view/FNODZJ5TBGD3C
- https://mathshare-staging.diagramcenter.org/#/problem/view/IEL2NBIBRL2KM
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/F77PURS2BYTZS
- https://mathshare-staging.diagramcenter.org/#/problem/view/HJIIQMLKWR3BE
- https://mathshare-staging.diagramcenter.org/#/problem/view/AJNYNI37WAMX2
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/EWN4UIWHPLEDG
- https://mathshare-staging.diagramcenter.org/#/problem/view/QW6S7UJTO6HEC
- https://mathshare-staging.diagramcenter.org/#/problem/view/HP3TH53546YVE
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/WWHBZLSH3VSM4
- https://mathshare-staging.diagramcenter.org/#/problem/view/MT5LUYKKJMYNI
- https://mathshare-staging.diagramcenter.org/#/problem/view/V6EC6I4T64XRS
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/TILTXG3GCZKFC
- https://mathshare-staging.diagramcenter.org/#/problem/view/ZLF5GUAZIUKM2
- https://mathshare-staging.diagramcenter.org/#/problem/view/Y4OT3ZTSUSXDY
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/MY2OMBVKSMS7W
- https://mathshare-staging.diagramcenter.org/#/problem/view/GDXTPRVAWXMLI
- https://mathshare-staging.diagramcenter.org/#/problem/view/BX4MAY3D7K2UM
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/G5AQIKCRHKYH2
- https://mathshare-staging.diagramcenter.org/#/problem/view/VG25KPZDNRVSY
- https://mathshare-staging.diagramcenter.org/#/problem/view/IYACFZMQ3T7AU
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/72KQCAPWAJOMG
- https://mathshare-staging.diagramcenter.org/#/problem/view/OWTW5OVURJDTK
- https://mathshare-staging.diagramcenter.org/#/problem/view/26JGV2S4476FO
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/OOPJFM3DSCDQU
- https://mathshare-staging.diagramcenter.org/#/problem/view/DCFQSGR3V7ATS
- https://mathshare-staging.diagramcenter.org/#/problem/view/YXFKNFIOBCM6C
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/NOFPRGDHPLI2M
- https://mathshare-staging.diagramcenter.org/#/problem/view/6TRG2D7Q22QHM
- https://mathshare-staging.diagramcenter.org/#/problem/view/X2JOFVN7RXQBE
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/YYDQR2JYTJGBG
- https://mathshare-staging.diagramcenter.org/#/problem/view/4PRQEEU67CJDI
- https://mathshare-staging.diagramcenter.org/#/problem/view/LHHHLD643PZC6
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/EIM6WNY3J4DM2
- https://mathshare-staging.diagramcenter.org/#/problem/view/GKLIXTBIDX5KC
- https://mathshare-staging.diagramcenter.org/#/problem/view/KB6UZQXFMOP5M
- https://mathshare-staging.diagramcenter.org/#/problemSet/view/6BH5T36HVS6EU
- https://mathshare-staging.diagramcenter.org/#/problem/view/VHKG63VS2OHYE
- https://mathshare-staging.diagramcenter.org/#/problem/view/CMTARZNC2OQMW

**Comment by johnhbenetech** [comment]
resolved
