### ISSUE TITLE
Text Not Integrated Into Localization System 

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#746]
A high number of strings have not been integrated into the localization system for the application, instead being hardcoded in the component JSX files.  Identifying every point in the codebase where this occurs is outside the scope of this document, but they include a number of accessible labels for controls, and all text strings explicitly sent to a screen reader for announcement. 
 
Currently the application is only available in English, but any future localization attempts would be rendered ineffective due to the high amount of textual content which is not in a translatable state.

#### Suggested Solution 
 
Ensure that all strings which are used to communicate content to users, be it via screen reader speech, visible text or both, are integrated into the localization system (for instance by having entries in strings.js).

**Comment by alexrcabral** [comment]
Strings appear to now be correctly integrated in the localization system. This is a bit harder to double-check on the product side, but looking through the code it seems to be effectively fixed

**Comment by jscholes** [comment]
Closing as fixed via https://github.com/benetech/MathShare/commit/f82cc20b21116ac95b326612dc3b18ebee786653.  Outstanding instances of non-localised strings can be addressed as we find them (if there are any).
