### ISSUE TITLE
provide horizontal scroll bar when math equation extends beyond the edit box

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#75]
This appears in MathLive as well. Could we use MathML/MathJax to wrap equations at logical points or4 insert a horizontal scroll bar once content extends beyond the allocated space (similar to the annotations and history where vertical scroll appears when needed)? 

This is not a huge issue since introductory Algebra content tends to be relatively short.

![math extends beyond editor box](https://user-images.githubusercontent.com/7883873/33446318-7de1ce36-d5b4-11e7-85d6-4962af2653ff.PNG)

![mathlive editor space](https://user-images.githubusercontent.com/7883873/33446408-c797d3f4-d5b4-11e7-971d-126adca0ee0e.PNG)

**Comment by NSoiffer** [comment]
Line breaking is hard. Neither MathType nor Wiris support. Instead, they use a horizontal scrollbar when the expression gets bigger. That's what we should do in the near term (at least a year).

Adding linebreaking support to MathLive would probably be at least a one month project. Maybe three months.

**Comment by BenetechSchwab** [comment]
This is almost done but it isn't working 100%...  It's kind of wonky as it is.  Lets review when we're all back in town.

**Comment by dserkowski** [comment]
I have checked it on Chrome and Firefox. It works correctly.
Result:
![screenshot from 2018-07-02 11-29-34](https://user-images.githubusercontent.com/29867015/42156560-ad6489ac-7deb-11e8-86e7-f19fe8f6e3a7.png)
