### ISSUE TITLE
Home -> ButtonsPaletteChooser: Ineffective Modal Title

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#753]
The Palette Chooser modal has an accessible title of “demo one”.  This text is completely uninformative and gives screen reader users no indication of the purpose of the modal or its contents. 
 
Suggested Solution 
 
Update the titleText property of the AriaModal container, so that the dialog’s title accurately reflects its purpose.  For example, “Select Button Palettes” or “Choose Available Button Palettes”.  This title should also be integrated into the application’s localization system with an entry in strings.js.

**Comment by alexrcabral** [comment]
Checked using VoiceOver and it correctly announces the new modal title

**Comment by jscholes** [comment]
Fixed.

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/f9d0666b63cbe6aa88a278dec5031dcf72bacd82.
