### ISSUE TITLE
Home -> Footer: Problematic Heading Placement 

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#756]
This component begins with an off-screen level 2 heading with the text: “Footer”.  This is problematic when the overall footer section includes the SiteMapFooter component, rendered before this one (as is the case on the Landing Page).  The “Footer” heading ends up being placed in the middle of the footer content rather than at the start of it.  If a screen reader user navigates by heading to locate the footer content, they will bypass any content which incorrectly precedes the heading altogether. 
 
Suggested Solution 
 
Instead of rendering the “Footer” heading as part of this component, move it into the main index.js file just below the opening <footer> tag. 
 
File: src/components/index.js 
 
`<footer id="footer">  <h2 className="sROnly"> {Locales.strings.footer} </h2> `
 
Then, remove it from the main Footer component (file: src/components/Home/components/Footer/index.js).

**Comment by benetechMatt** [comment]
verified

**Comment by jscholes** [comment]
@johnhbenetech this needs the a11y label but the interface to add those doesn't seem to work with a screen reader.

**Comment by johnhbenetech** [comment]
@jscholes added!

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/c09b9ea61714828eb896258faf894fd7f439a0d7.
