### ISSUE TITLE
Home -> Navigation -> Problems: Incorrect Modal Dismissal Behavior

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#765]
When the “Add new Problem” button is activated, a modal dialog opens allowing the new problem(s) to be defined.  When this dialog is closed, keyboard focus does not return to the triggering button.  Instead, it is placed on the Benetech MathShare logo image in the header. 
 
Suggested Solution 
 
When a modal dialog is closed, keyboard focus should almost always return to the control which was used to invoke it.  In this case, place keyboard focus back on the “Add new Problem” button.

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/dda0ca24d5b1402098600d88c9cb493dcbbcc394.
