### ISSUE TITLE
Home -> NewProblemsForm: Ineffective Modal Title

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#766]
The New Problem modal has an accessible title of “demo one”.  This text is completely uninformative and gives screen reader users no indication of the purpose of the modal or its contents. 
 
Suggested Solution 
 
Update the titleText property of the AriaModal container, so that the dialog’s title accurately reflects its purpose.  For example, “Add New Problem” or “Add to Problem Set”.  This title should also be integrated into the application’s localization system with an entry in strings.js.

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/cce5710d2723d12f722fbae69180cb01637e8ab0.
