### ISSUE TITLE
Home -> SiteMapFooter Problematic Line Break

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#772]
The text, “Mathshare is a Benetech Initiative”, contains a line break < br /> tag before the word “Benetech”.  This results in screen reader users needing to press the down arrow key twice to read a single short piece of text. 
 
Suggested Solution 
 
Separate the content from its presentation, by wrapping the text using CSS declarations.  Then, remove the < br /> tag and replace it with a space.

**Comment by jscholes** [comment]
@rupeshparab - the `<br />` has been removed, but the text is now spread across two `<p>` elements which has exactly the same effect as the original mark-up.

**Comment by johnhbenetech** [comment]
we can just keep it on one line (assuming the css is relatively responsive)

**Comment by rupeshparab** [comment]
I have moved the text in the same container, it will appear on the same line now

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/014666732da3de3f3e3b488c55354be26c44e678.
