### ISSUE TITLE
Home -> SocialFooter Incorrect Text Case

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#775]
The Social Footer includes links to the MathShare YouTube channel and Twitter profile.  The text of the accessible labels for these links is entirely in lower case, which causes problems such as some speech synthesizers mispronouncing the word YouTube. 
 
Suggested Solution 
 
Apply correct casing to the text, using upper case letters in their appropriate positions.

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/8d3e670b937ddfb829d14e5e7f7ffca10337f4f4.
