### ISSUE TITLE
Home -> SocialFooter Unnecessary Link Label Prefix 

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#776]
The text of the YouTube and Twitter link labels include the word “to” as a prefix (“to MathShare twitter”).  This is unnecessary and, when read in combination with the elements’ link role, produces slightly confusing speech sequences. 
 
Suggested Solution 
 
Change the wording of the link labels to remove this prefix.  Simply using the name of the target social media network as the link text (“Twitter” and “YouTube”) would be a good solution.

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/12ace13db0106e39ac987cb85c8b37ab988d70ab.
