### ISSUE TITLE
LandingPage Content Boundaries

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#779]
Instead of using < hr> elements to separate the application features in the DOM, we would suggest using CSS to create the same visual effect.  Once headings are in place, users of screen readers will gain nothing from the inclusion of these < hr> elements

**Comment by jscholes** [comment]
Related to #778.

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/b88092ce95aebcab1e21acfa112f4d8644e7b470.
