### ISSUE TITLE
LandingPage Ineffective Link Text 

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#781]
The link to launch the application has the text: “Try now”.  This does not sufficiently describe the link’s purpose or destination. 
 
Suggested Solution 
 
Determine a more effective textual label for the link, which describes where the user will be taken when they click it.  For example, “Launch MathShare”, “View Math Problem Sets”, etc.

**Comment by johnhbenetech** [comment]
@alexrcabral @benetechMatt Can we get a different label suggestion?

**Comment by alexrcabral** [comment]
"Open Mathshare" could be good 

Launch suggests external software, while "View Problem Sets" suggests a more specific page 
redirection

**Comment by johnhbenetech** [comment]
@rupeshparab sounds like we're going with 'Open MathShare'

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/b98482dd56db591e3e3638578557997254eac54d.
