### ISSUE TITLE
NotFound Duplicate and Unnecessary Headings

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#782]
There are three headings on the Not Found page: 
 
• Level 1: “Page Not Found” 
• Level 2: “We are sorry but the page you are looking for does not exist.” 
• Level 3: “Please visit the homepage or contact us about the problem.” 
 
Each of the above headings is duplicated and appears twice, resulting in six headings overall.  This problem has slipped through the cracks because the first instance of each heading is visually hidden and only appears to screen reader users.  In truth, though, only the first level 1 heading is required, and the rest should just be marked up as text because they have no content following them. 
 
Suggested Solution 
 
Remove the off-screen headings, and mark up the level 2 and level 3 headings as text-only nodes (< div>, < p>, etc.).

**Comment by jscholes** [comment]
This ticket accidentally encompassed two separate issues.  Split out into #811.

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/0c7ab711ae0ec64d5fb0a169a4787d6738d1188d.
