### ISSUE TITLE
Partners Uninformative Link Text 

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#785]
The link to the Mathshare Contact Form has the text: “complete this form”.  This doesn’t indicate the link’s purpose or destination outside of its surrounding context. 
 
Suggested Solution 
 
Update the link text so that it clearly communicates where the link goes and why users would want to click it.  For example: “Submit a partnership request through our contact form”.

**Comment by rupeshparab** [comment]
@johnhbenetech 
This is the Contact Form:
https://docs.google.com/forms/d/e/1FAIpQLSeDijluYj0wyTz6OexPppVt9enX1QXpXSMPUflkdCtTBtv6HA/viewform

**Comment by johnhbenetech** [comment]
@benetechMatt @alexrcabral Suggestion for this link?

**Comment by alexrcabral** [comment]
@benetechMatt I'll leave this one up to you because I'm not sure what your intent is with this form. (The "Purpose" section suggests partnerships, but the rest suggests general feedback)

**Comment by johnhbenetech** [comment]
@benetechMatt thoughts on this?

**Comment by benetechMatt** [comment]
Link is from the partnerships page
https://mathshare.benetech.org/#/partners

Change link text to "Submit a partnership request through our contact form" and link to the contact form as it does now

**Comment by benetechMatt** [comment]
add a "." at end of the last sentence

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/6a09f42d6b3f9d2635bac275e3fa99ac6a967ce9.
