### ISSUE TITLE
UserDetails Ineffective Accessible Control Label 

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#795]
The < select> dropdown following the text, “Which best describes your role?” has no accessible label.  The question text is present, marked up inside a < div> element, but this isn’t sufficient to programmatically connect it to the < select> as its label.  Nor is the text of the first item (“Choose one”) appropriate to describe how users should operate this control. 
 
This issue is in fact picked up by the jsx-a11y ESLint plug-in, but its detection is ignored inside the component’s index.js file: 
 

`{/* eslint-disable-next-line jsx-a11y/label-has-associated-control */} `
 

The purpose of the jsx-a11y plug-in is to catch errors like this, so that common accessibility problems have a higher chance of being avoided.  But it’s rendered useless if valid warnings are just disabled instead of a fix being implemented. 

Suggested Solution 
 
Think twice before disabling linter accessibility warnings.  Here, the warning is completely accurate, because the < select> has no associated < label>. 
 
Add a < label> which includes the question text, and programmatically connect it to the dropdown by providing the dropdown’s DOM ID as the value of an htmlFor property on the < label>. 
 
Note: do not add a < label> in addition to the < div> which already contains the question text.  Users should only encounter the question text once, so move the question out of the < div> and into the < label>.  Alternatively, apply a unique ID to the current < div>, and then supply that as the value of an aria-labelledby attribute on the opening tag of the < select> dropdown.

Aha! Link: https://diagramlabs.aha.io/features/B-123

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/219f54b4a8795339ea2c4521aa11864753c316e8.
