### ISSUE TITLE
Explore Canvas Oauth possibilities

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#809]
Now that we have finally solved the user account issues, we are able to explore other oauths. The supported options are all here:

http://www.passportjs.org/packages/

It supports base Oauth 2.0, so many LMS providers offer this

Aha! Link: https://diagramlabs.aha.io/features/B-110

**Comment by benetechMatt** [comment]
@johnhbenetech is this issue still relevant or should we close it?

**Comment by johnhbenetech** [comment]
@benetechMatt I think it's obviated by #609 so we can close

**Comment by alexrcabral** [comment]
Closing the issue since obviated by #609
