### ISSUE TITLE
Home  -> Navigation -> Problems: List Semantics Removed by CSS Declaration

### ISSUE THREAD

**Issue by jscholes** [benetech/MathShare#813]
In commit https://github.com/benetech/MathShare/commit/125671aa6fd22fa7e5a6cc15ac456edd554af0fd, the following declaration was added to [src/components/Home/components/Navigation/Problems/styles.scss](https://github.com/benetech/MathShare/blob/development/src/components/Home/components/Navigation/Problems/styles.scss):

```
    ol {
        display: contents;
    }
```

In Chrome (and potentially other browsers), this also impacts how the accessibility tree is constructed.  Screen reader users will no longer be exposed to the list container, meaning that the problems won't appear to be marked up as a list at all.

Arguably, this represents incorrect browser behaviour, but must be fixed in MathShare regardless.  Alternative declarations must be used to creat any desired visual layout without using `display: contents;`.

**Comment by jscholes** [comment]
@johnhbenetech - could you please add the a11y label?

**Comment by rupeshparab** [comment]
I have changed display from contents to flex, it seems to rendering a similar visual layout

**Comment by jscholes** [comment]
@rupeshparab - works for me.  I'll close this, and it can be reopened if there are any design issues.

Fixed in https://github.com/benetech/MathShare/commit/6eb8c233e7846f5db240c9de0a0c85f085793a26.
