### ISSUE TITLE
Not Found: Duplicate "Skip to Main Content" links

### ISSUE THREAD

**Issue by jscholes** [benetech/MathShare#817]
On the NotFound page, there are two consecutive "Skip to Main Content" links: one inside the `<header>` section and one outside of it.  There should only be one, inside the `<header>` region.

**Comment by rupeshparab** [comment]
I have removed the duplicate skip link

**Comment by jscholes** [comment]
Fixed in https://github.com/benetech/MathShare/commit/6aae41696a8680d309f6afc64c0f7c863eaed657.
