### ISSUE TITLE
Separate sign up and log in

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#829]
Create a separate Sign Up page from the Log In page.  Log in goes to the Log in page.  The "Sign Up" button on the homepage goes to Sign Up.

Aha! Link: https://diagramlabs.aha.io/features/B-97

**Comment by benetechMatt** [comment]
/login has the wording "Log In Using"
/signup has the wording "Sign Up Using"

**Comment by benetechMatt** [comment]
Marketing will be using these within landing pages and emails.  More specific verbage helps click through rates

**Comment by johnhbenetech** [comment]
hey @benetechMatt, as we currently only have Oauth - the login and signup are the same flow. Can you clarify the requirements?

**Comment by benetechMatt** [comment]
I explained that to Ben and he said users feel more comfortable when the phrasing the same as what they read in an email/landing page.  Sign in and sign up are similar, but Ben said it can confuse some users and cause them to not click.

________________________________

**Comment by johnhbenetech** [comment]
So is there any task on our side or can we simply just have both buttons/links point to the same endpoint?

**Comment by benetechMatt** [comment]
They can point to the same end point.  Two copies of the same page but slightly different wording

________________________________

**Comment by benetechMatt** [comment]
For both pages, the "continue without signing in" link takes the user back to the hompage.  The link should let the user continue to the dashboard.

Remove "sign up" from the upper right of the homepage.  only have "sign in" in the upper right

**Comment by johnhbenetech** [comment]
@benetechMatt So how does the user get to Sign-up?

**Comment by benetechMatt** [comment]
Let's add a button that says "Sign Up" in the same style as the "Open Mathshare" button.  Place it between "accessible to all learners" and the "LMS Integration" sections.

**Comment by benetechMatt** [comment]
there are two lines of text saying similar things for the sign in and sign up.
Sign in page:
Currently the sign in page says "Sign in" and on the next line "Login using" 
Change to "Sign in using" only

Sign up page:
Currently the sign up page says "Sign Up" and on the next line "Sign Up using"
Change to "Sign up using" only

**Comment by rupeshparab** [comment]
This comment has the final change implemented in the task - https://github.com/benetech/MathShare/pull/935#issuecomment-620303445

**Comment by jscholes** [comment]
@benetechMatt 

> Let's add a button that says "Sign Up" in the same style as the "Open Mathshare" button. Place it between "accessible to all learners" and the "LMS Integration" sections.

I assume this is no longer the plan?

**Comment by benetechMatt** [comment]
@jscholes Correct. While we haven't moved to the new wordpress based site, I'll close this issue as it will be resolved soon with the new site.

**Comment by jscholes** [comment]
> new wordpress based site

I think we need to talk about this some more (although not on this ticket).  The only thing we've heard about this so far is via https://github.com/benetech/MathShare/issues/1076, but I was under the impression that you'd shelved that effort for now.  There are technology choice concerns (i.e. why WordPress is required for a single page when the rest of the app will live outside of it).  But also accessibility implications.  This page should 100% be born accessible, not made without our input and then spot checked.

**Comment by alexrcabral** [comment]
> I think we need to talk about this some more (although not on this ticket)

@jscholes  I've set aside some time for us to talk about this during the accessibility meeting this week
