### ISSUE TITLE
Delete user account

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#836]
robin.eckelberry@ppcc.edu requested to have their account deleted as they signed in with the wrong email account and are concerned about the permissions granted when signing in with Google

Aha! Link: https://diagramlabs.aha.io/features/B-93

**Comment by benetechMatt** [comment]
correction, signed in with microsoft

**Comment by johnhbenetech** [comment]
@benetechMatt They should be able to go to https://microsoft.com/consent themselves and revoke our access from their side

**Comment by benetechMatt** [comment]
The user would like their account completed removed from our system

**Comment by benetechMatt** [comment]
resolved
