### ISSUE TITLE
Changes to microsoft sign in

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#837]

**Comment by benetechMatt** [comment]
![screenshot of permissions screen when signing in for the first time with microsoft account](https://user-images.githubusercontent.com/49413678/70084469-e9062c00-15d3-11ea-835c-0ee020757b1a.png)


Mathshare Production needs your permission to:
View your basic profile
Mathshare Production will be able to see your basic profile (name, picture, user name).
Maintain access to data you have given Mathshare Production access to
Allows Mathshare Production to see and update the data you gave it access to, even when you are not currently using the app. This does not give Mathshare Production any additional permissions.
Read your mail
Mathshare Production will be able to read email in your mailbox.
Accepting these permissions means that you allow this app to use your data as specified in their terms of service and privacy statement. The publisher has not provided links to their terms for you to review. You can change these permissions at https://microsoft.com/consent. Show details


We should add a link to our privacy policy
can we remove permissions to read email?

**Comment by johnhbenetech** [comment]
Fixed.
