### ISSUE TITLE
microsoft sign in permissions issue

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#839]
Aha! Link: https://diagramlabs.aha.io/features/B-92

**Comment by benetechMatt** [comment]
A user (mattkennedy@dbqschools.org) was not able to sign in because their admin had to grant access. when their admin tried to do this they responded with this

"There looks to be an issue with the application that MathShare will need to correct. It *should* be requesting the below 4 rights when granting administrative approval.

However, the admin approval only grants partial access instead.

Since it is only granting partial access, you still get the prompt. I'm not sure if there is anything further that I can do here to fix this."

The email matt sent to his IT

"Could this website be opened for me to sign in with my Microsoft account? We already use the company's other product for accessible books. I'm interested in looking at the new math tool they created.

https://mathshare.benetech.org/#/signUp"

**Comment by johnhbenetech** [comment]
What does 'the below 4 rights' mean? Is there meant to be a picture attached?

**Comment by johnhbenetech** [comment]
@benetechMatt See comment above. It's possible the permission change we pushed might help this? But it's hard to test since we dont know their exact domain set-up. Would you feel comfortable reaching out and asking them to try again

**Comment by benetechMatt** [comment]
Did not hear back from the user, emailing again to test this

**Comment by johnhbenetech** [comment]
I'm gonna close this until we hear otherwise
