### ISSUE TITLE
Always prompt students to sign in

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#973]
When students open a new set ask them to sign in if they are not. If they decline ask them to add a name. The name is stored with the student responses and will show up in the teacher’s dashboard (other task)

**Comment by benetechMatt** [comment]
![mockup of screen asking students to sign in.  Problem set page with a modal and background grayed out.  Modal has the text "sign in to save where you left off" and a google classroom and microsoft teams sign in buttons. in the next line below of to the right is a button that says "no thanks"](https://user-images.githubusercontent.com/49413678/75602061-46046780-5a87-11ea-8337-e54b3ac301ba.png)

**Comment by benetechMatt** [comment]
![mockup of screen if users select "no thanks" in previous modal asking users to sign in.  Background is grayed out with a modal containing the text "Enter your name". A text box is below that with the text "name" and a button below that with the text "submit"](https://user-images.githubusercontent.com/49413678/75602097-9b407900-5a87-11ea-9c6b-e1ed47bfba26.png)

**Comment by alexrcabral** [comment]
1) Is this only when opening a new set through an LMS? 
2) How is the name being used/stored within the system? 
3) If they add a name but are not signed in, will they be able to view or edit their problem set in a later session? 
4) If they add a name but are not signed in, does the problem set automatically show up in the teacher's dashboard, or does the student have to submit the finished problem set within the same session?

**Comment by alexrcabral** [comment]
If #975 is being combined with this issue, there should also be mention in this issue of how students are instructed on how to change settings later after sign-in.

**Comment by johnhbenetech** [comment]
Point 2-4 would make me uncomfortable. I'm fine prompting for sign in - but we won't do any free text names. Too many students can be sharing computers, using multiple devices, etc. I'm also not sure of privacy considerations.

We can build out our own username/password system - but the name thing feels like a non starter

**Comment by benetechMatt** [comment]
1. This happens whenever students open a link to the problem set.  Doesn't matter if it's from an LMS or from an email, etc.
2. stored similar to how signed in users are connected with solutions.  Connect he entered name with the set.
3. They will not be able to reopen the set if they did not sign in.  I don't believe we currently use cookies for tracking sessions.  We should use cookies to track user sessions so that if a user enters a name and doesn't sign in we assume it's that user when they return.
4. Yes, sets will show up for teachers even if students only left a name and did not sign in.  It is possible that students will have multiple sets with different questions answered.  


@johnhbenetech We could require signing in, but that will cause issues with schools that require teachers to get permission before using any tools that collect student information.
What if we changed it to "nickname" instead of "name"?  we could randomly generate names but without a key, teachers won't know who the students are. 

By connecting student names with sets, I hope to reduce the number of students that lose their work and track the success of students and completing sets.

**Comment by johnhbenetech** [comment]
@benetechMatt We won't do this full-stop unless there is explicit legal sign-off, Privacy Policy updates, etc. This is directly protected under FERPA

**Comment by benetechMatt** [comment]
Let's remove the enter a name portion and just stick with prompting students to sign in.  We'll work through alternatives to students signing in a different issue later

**Comment by alexrcabral** [comment]
Sounds good. Regarding prompting students to sign in -- why does the modal in your mockup differ from the existing sign-in prompt that is actively clicked into? 

<img width="508" alt="Screen shot of the existing sign in page. At the top is the Mathshare logo followed by sign in / log in using Google or Microsoft, or continue without signing in." src="https://user-images.githubusercontent.com/47576069/77458272-2a0c9100-6dbb-11ea-98ac-eec75c385d48.png">

**Comment by jscholes** [comment]
> We could require signing in, but that will cause issues with schools that require teachers to get permission before using any tools that collect student information.

@johnhbenetech has already strongly made a case against this.  But just to flag that a student's name is student information, so isn't an alternative to proper authentication in that way.

#### "No Thanks" Text

I'm not sure this is the most usable label, for a couple of reasons:

1. It's non-standard.  Users are accustomed to "Yes/No" or "Cancel" buttons, but not this.
2. The other controls in the modal are actionable, i.e. they are phrased as controls to sign in to some service.  "No Thanks" is not an action.

How about just "Cancel", or "Continue without signing in"?

**Comment by benetechMatt** [comment]
We'll borrow the same modal as used when users sign up and modify the text as suggested by Alex. 
Mathshare logo at top
"Save where you left off, sign in"
Google Sign in button, Microsoft Sign in button
Continue without signing in link

**Comment by benetechMatt** [comment]
made the "continue without signing in" link a smaller font size and right aligned to visually give it less emphasis

![Mockup of sign in modal. 'Save where you left off, sign in'](https://user-images.githubusercontent.com/49413678/77600323-91b6ff00-6ed5-11ea-8836-1daf1cdcf92c.png)

**Comment by alexrcabral** [comment]
@benetechMatt The copy on this final mockup differs from the final mockup in #1067. Which is the true final version?

**Comment by benetechMatt** [comment]
This issue and #1067 are for different scenarios but both can benefit from the wording used in this issue.  We'll adopt https://github.com/benetech/MathShare/issues/973#issuecomment-604173153 for both to encourage users to sign up.

**Comment by benetechMatt** [comment]
This should not show up for the /review/ URL

**Comment by jscholes** [comment]
@johnhbenetech I was assigned to this issue, but I'm not sure what I should be commenting on?

**Comment by johnhbenetech** [comment]
@jscholes I think @alexrcabral Wants to discuss on your next a11y call about better options other than an aggressive modal

**Comment by alexrcabral** [comment]
Since #1132 was approved and merged, moving to Product Sign-Off

**Comment by jscholes** [comment]
@alexrcabral Can we schedule a modal-related check-in/chat for an upcoming call?

**Comment by alexrcabral** [comment]
Sure thing, I'll make a note of it for the meeting the week after next (06/03)

**Comment by abaranowska1** [comment]
@johnhbenetech @rupeshparab 
After read all comments above I'm a little confused about what is an expected result. 
I can see sign in pop up window when:
- I open a Problem set from a shared link and I'm not signed in 
- I open Example Problem Sets and I'm not signed in 
I cannot see this sign in window when I'm creating a new Problem and I'm not signed in 
If it is  expected I can close this issue
![Peek 2020-05-22 13-48](https://user-images.githubusercontent.com/61964176/82665462-2323c280-9c34-11ea-8091-b16ec123ce06.gif)

**Comment by johnhbenetech** [comment]
@abaranowska1 you can close it. Product signed off on approach
