### ISSUE TITLE
Any messages asking students to sign in have the link “benefits of signing in” article in help center. Article explains the benefits for signing in

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#976]
help center article explanaing the benefits
https://intercom.help/benetech/en/articles/3754980-benefits-of-having-a-user-account

**Comment by benetechMatt** [comment]
help center article explanaing the benefits
https://intercom.help/benetech/en/articles/3754980-benefits-of-having-a-user-account

**Comment by alexrcabral** [comment]
The article should also be updated during this task. Currently it only says "Work is started at the same time every morning."

**Comment by rupeshparab** [comment]
Currently there is just 1 place where we are asking users to Sign In on Dashboard page.
I have added the benefits link below it, attaching its screenshot:

![image](https://user-images.githubusercontent.com/6897505/79590609-e4f72880-80f4-11ea-9853-1b1bc7890d9a.png)

Please let me know if the link needs to be added anywhere else and if any styling changes are needed for the link

**Comment by johnhbenetech** [comment]
@benetechMatt @alexrcabral Take a quick look at this to confirm this is what you intended

**Comment by benetechMatt** [comment]
updated help center page text

**Comment by benetechMatt** [comment]
The link should also be placed on the sign in page. Below the google and microsoft buttons
https://mathshare-qa.diagramcenter.org/#/signIn

**Comment by rupeshparab** [comment]
Thanks for confirming, I have moved it to the Login page

![image](https://user-images.githubusercontent.com/6897505/79594047-fe4ea380-80f9-11ea-9b4e-b8ccf420ba7f.png)

**Comment by johnhbenetech** [comment]
@rupeshparab I believe we actually want it in both places (the dashboard and the sign in page itself). Kicking back to you for quick fix.

**Comment by rupeshparab** [comment]
I have kept the benefits of signing in link on both pages

**Comment by abaranowska1** [comment]
@johnhbenetech @rupeshparab 
In my opinion, it will look better when "benefits of signing in" link will start from the capital letter like " Continue without signing in"  
![image](https://user-images.githubusercontent.com/61964176/80599296-03312280-8a2b-11ea-88a0-7060f64999d9.png)

**Comment by johnhbenetech** [comment]
@rupeshparab Yes let's capitalize the letter

**Comment by rupeshparab** [comment]
I have capitalised the text

**Comment by abaranowska1** [comment]
**Tested with success**
Verified on Mozilla Firefox v.75.0 

Verified cases:

- "Benefits of signing in" link is displayed on the log in window and also on the homepage for unauthorized users. 
![image](https://user-images.githubusercontent.com/61964176/81790077-249f0d80-9505-11ea-8e22-af9861f2a4b5.png)
![image](https://user-images.githubusercontent.com/61964176/81790085-28cb2b00-9505-11ea-95a2-6b7b29fd2a27.png)
![image](https://user-images.githubusercontent.com/61964176/81790091-2c5eb200-9505-11ea-86ea-3634b85f7233.png)
