### ISSUE TITLE
Story: students need TTS to help them process the question

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#994]
As a student who has difficulty reading and processing information at the same time
I want to have the text and math read aloud to me and the words highlighted so I can follow along
So that I can think about the problem.

### Current problem:
No TTS built into mathshare
Mathshare is not compatible with most TTS browser extensions

### Dependencies:
TTS personalization settings #1004 

### Tasks:
#995 
#996 
#997 
#998 
#999 
#1000 
#1001 
#1002 
#1003

**Comment by alexrcabral** [comment]
@benetechMatt Moving to product review since most of the adjoining issues are there.

**Comment by alexrcabral** [comment]
Closing this as the majority of issues have been addressed with release v1.4.0. Any remaining have been triaged appropriately within the product board
